/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package example

// Generated by tools/r-parity/generate_multiscale.py; data only.
// format: off
object ConsumerFixtures:
  val csv = """participant,image,phase,fixation,x_px,y_px,onset_us,duration_us,sample_count
s1,a,encode,0,0.5,0.5,0,100000,100
s1,a,encode,1,1.5,0.5,110000,200000,200
s1,a,encode,2,0.5,1.5,320000,200000,200
s1,a,encode,3,1.5,1.5,530000,400000,400
s1,b,encode,0,0.5,0.5,0,400000,400
s1,b,encode,1,1.5,0.5,410000,200000,200
s1,b,encode,2,0.5,1.5,620000,200000,200
s1,b,encode,3,1.5,1.5,830000,100000,100
s1,c,encode,0,0.5,0.5,0,200000,200
s1,c,encode,1,1.5,0.5,210000,400000,400
s1,c,encode,2,0.5,1.5,620000,100000,100
s1,c,encode,3,1.5,1.5,730000,200000,200
s2,a,encode,0,0.5,0.5,0,200000,200
s2,a,encode,1,1.5,0.5,210000,100000,100
s2,a,encode,2,0.5,1.5,320000,400000,400
s2,a,encode,3,1.5,1.5,730000,200000,200
s2,b,encode,0,0.5,0.5,0,100000,100
s2,b,encode,1,1.5,0.5,110000,400000,400
s2,b,encode,2,0.5,1.5,520000,200000,200
s2,b,encode,3,1.5,1.5,730000,200000,200
s2,c,encode,0,0.5,0.5,0,400000,400
s2,c,encode,1,1.5,0.5,410000,100000,100
s2,c,encode,2,0.5,1.5,520000,200000,200
s2,c,encode,3,1.5,1.5,730000,200000,200
s1,a,recall,0,0.5,0.5,0,100000,100
s1,a,recall,1,1.5,0.5,110000,200000,200
s1,a,recall,2,0.5,1.5,320000,200000,200
s1,a,recall,3,1.5,1.5,530000,400000,400
s1,b,recall,0,0.5,0.5,0,200000,200
s1,b,recall,1,1.5,0.5,210000,400000,400
s1,b,recall,2,0.5,1.5,620000,100000,100
s1,b,recall,3,1.5,1.5,730000,200000,200
s1,c,recall,0,0.5,0.5,0,400000,400
s1,c,recall,1,1.5,0.5,410000,200000,200
s1,c,recall,2,0.5,1.5,620000,200000,200
s1,c,recall,3,1.5,1.5,830000,100000,100
s2,a,recall,0,0.5,0.5,0,400000,400
s2,a,recall,1,1.5,0.5,410000,100000,100
s2,a,recall,2,0.5,1.5,520000,200000,200
s2,a,recall,3,1.5,1.5,730000,200000,200
s2,b,recall,0,0.5,0.5,0,100000,100
s2,b,recall,1,1.5,0.5,110000,400000,400
s2,b,recall,2,0.5,1.5,520000,200000,200
s2,b,recall,3,1.5,1.5,730000,200000,200
s2,c,recall,0,0.5,0.5,0,200000,200
s2,c,recall,1,1.5,0.5,210000,100000,100
s2,c,recall,2,0.5,1.5,320000,400000,400
s2,c,recall,3,1.5,1.5,730000,200000,200
"""
  val gaussianTargets = Vector(
    0.5 -> Map("s1/1/recall" -> 0.1743044709757272, "s1/2/recall" -> -0.060545313662938104, "s1/3/recall" -> -0.00733147001308712, "s2/1/recall" -> 0.01113108514342614, "s2/2/recall" -> 0.17854319875208205, "s2/3/recall" -> 0.006032493437884438),
    1.0 -> Map("s1/1/recall" -> 0.01977499307113894, "s1/2/recall" -> -0.006620888466436306, "s1/3/recall" -> -8.76723281699786e-05, "s2/1/recall" -> 0.0007998419114576185, "s2/2/recall" -> 0.016578560718144154, "s2/3/recall" -> 0.0033581979231937066),
    2.0 -> Map("s1/1/recall" -> 0.0012977635373891574, "s1/2/recall" -> -0.00043271267263442475, "s1/3/recall" -> -3.744805141168537e-07, "s2/1/recall" -> 4.835638721694465e-05, "s2/2/recall" -> 0.0010594336776245327, "s2/3/recall" -> 0.00023903616953714014),
  )
// format: on
