import org.typelevel.sbt.gha.JavaSpec
import org.typelevel.sbt.gha.{GenerativePlugin, PermissionValue, Permissions}

import scala.io.Source

// ---------------------------------------------------------------------------
// Versions
// ---------------------------------------------------------------------------

// Uniform compiler baseline, including downstream specimens. PRD B-1;
// owner decision bead bd-01M2R7AH4XBQVR0C9F1AGSZ74X. No frame4s integration implied.
val Scala3 = "3.7.4"

// eyes4s-kernel's ONLY external dependency is cats-core. There is deliberately
// no `algebra` and no Spire: `algebra` has no vector-space abstraction to
// inherit, and Spire is not published for Scala Native 0.5 and defines a
// length-zero `zero` for arrays, which is incompatible with a per-grid carrier.
// The module structure on Signed[U] is defined here instead -- see PRD O-12 and
// the "Core defines its own Module" resolution in eyes4s.md.
val catsV            = "2.13.0"
val circeV           = "0.14.16" // eyes4s-codec only
val munitV           = "1.3.4"
val munitScalacheckV = "1.3.0"
val disciplineMunitV = "2.0.0"
val scalacheckV      = "1.19.0"
val catsLawsV        = "2.13.0"
val catsEffectV      = "3.7.0"   // eyes4s-fs2 / eyes4s-io only
val fs2V             = "3.13.0"  // eyes4s-fs2 / eyes4s-io only
val munitCatsEffectV = "2.1.0"   // eyes4s-fs2 tests only

// ---------------------------------------------------------------------------
// Build-wide settings
// ---------------------------------------------------------------------------

ThisBuild / tlBaseVersion    := "0.1"
ThisBuild / organization     := "io.github.canardlapin"
ThisBuild / organizationName := "canardlapin"
ThisBuild / startYear        := Some(2026)
ThisBuild / licenses         := Seq(License.Apache2)
ThisBuild / developers       := List(
  tlGitHubDev("canardlapin", "canardlapin")
)

ThisBuild / scalaVersion       := Scala3
ThisBuild / crossScalaVersions := Seq(Scala3)
// Scala.js macro dependencies can otherwise retain an older JVM stdlib alongside
// the JS stdlib, colliding at scala.caps. Keep both on the compiler baseline.
// https://github.com/scala/scala3/issues/22890
ThisBuild / dependencyOverrides += "org.scala-lang" % "scala3-library_3" % Scala3
ThisBuild / tlJdkRelease                           := Some(11)

ThisBuild / githubWorkflowJavaVersions := Seq(
  JavaSpec.temurin("17"),
  JavaSpec.temurin("21")
)

// Code health, security submission, and publication have different trigger and
// permission boundaries. Generate them as separate files from the same
// sbt-github-actions model so a missing credential cannot turn a green code
// check red, and a branch push can never enter the release path.
ThisBuild / githubWorkflowPublishTargetBranches := Seq.empty
ThisBuild / githubWorkflowTargetTags            := Seq.empty
ThisBuild / githubWorkflowAddedJobs             := Seq.empty
ThisBuild / githubWorkflowPermissions           := Some(
  Permissions.Specify.defaultRestrictive.withPackages(PermissionValue.None)
)

lazy val trustWorkflowContents =
  taskKey[Map[String, String]]("Render every generated eyes4s workflow.")

// A project's module name as sbt-github-dependency-submission computes it
// (GithubDependencyGraphPlugin.getModuleName), paired with publish / skip.
lazy val submissionModule = Def.task {
  val crossVersion =
    CrossVersion((artifactName / scalaVersion).value, (artifactName / scalaBinaryVersion).value)
  crossVersion(projectID.value).name -> (publish / skip).value
}

def bundledCleanWorkflow: String = {
  val stream = Option(GenerativePlugin.getClass.getResourceAsStream("/clean.yml"))
    .getOrElse(sys.error("sbt-github-actions clean.yml resource is unavailable"))
  val source = Source.fromInputStream(stream, "UTF-8")
  try source.mkString
  finally source.close()
}

def eyeLinkPerformanceWorkflow: String =
  """# This file is generated by the githubWorkflowGenerate task in build.sbt.
    |# Do not edit it directly.
    |
    |name: EyeLink Performance
    |
    |on:
    |  workflow_dispatch:
    |  schedule:
    |    - cron: '23 4 * * 1'
    |
    |permissions:
    |  contents: read
    |
    |concurrency:
    |  group: eyelink-performance-${{ github.ref }}
    |  cancel-in-progress: true
    |
    |jobs:
    |  scheduled:
    |    name: Scheduled bounded-memory court
    |    runs-on: ubuntu-22.04
    |    timeout-minutes: 60
    |    steps:
    |      - name: Checkout current revision
    |        uses: actions/checkout@v6
    |        with:
    |          fetch-depth: 0
    |
    |      - name: Setup sbt
    |        uses: sbt/setup-sbt@v1
    |
    |      - name: Setup Java
    |        uses: actions/setup-java@v5
    |        with:
    |          distribution: temurin
    |          java-version: 21
    |          cache: sbt
    |
    |      - name: Record source identity
    |        shell: bash
    |        run: |
    |          echo "SOURCE_REVISION=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
    |          git archive HEAD | shasum -a 256 | awk '{print "SOURCE_DIGEST=" $1}' >> "$GITHUB_ENV"
    |
    |      - name: Run two-hour EyeLink performance court
    |        run: >-
    |          sbt "ioJVM/Test/runMain eyes4s.io.EyeLinkAscPerformanceMain
    |          --profile scheduled
    |          --source-revision $SOURCE_REVISION
    |          --source-digest $SOURCE_DIGEST
    |          --source-dirty false
    |          --hardware github-hosted-ubuntu-22.04-x64
    |          --output target/eyelink-performance-scheduled.tsv"
    |
    |      - name: Upload measured validation rows
    |        uses: actions/upload-artifact@v4
    |        with:
    |          name: eyelink-performance-${{ github.sha }}
    |          path: target/eyelink-performance-scheduled.tsv
    |          if-no-files-found: error
    |""".stripMargin

// The full API audit (compileAll plus one JaCoCo-instrumented sbt launch per module)
// and the published-artifact consumer (publishLocal plus an isolated JVM/JS build) are
// too slow for every push. They run weekly and on demand; the per-push Checks keep
// the fast, platform-aware documentation evidence check.
def scheduledEvidenceWorkflow: String = {
  def job(id: String, name: String, command: String, artifact: String, paths: Seq[String]) =
    s"""|  $id:
        |    name: $name
        |    runs-on: ubuntu-22.04
        |    timeout-minutes: 120
        |    steps:
        |      - name: Checkout current revision
        |        uses: actions/checkout@v6
        |        with:
        |          fetch-depth: 0
        |
        |      - name: Setup sbt
        |        uses: sbt/setup-sbt@v1
        |
        |      - name: Setup Java
        |        uses: actions/setup-java@v5
        |        with:
        |          distribution: temurin
        |          java-version: 17
        |          cache: sbt
        |
        |      - name: $name
        |        run: $command
        |
        |      - name: Upload evidence
        |        if: always()
        |        uses: actions/upload-artifact@v4
        |        with:
        |          name: $artifact-$${{ github.sha }}
        |          path: |
        |__PATHS__
        |          if-no-files-found: warn
        |""".stripMargin.replace("__PATHS__", paths.map("            " + _).mkString("\n"))

  """|# This file is generated by the githubWorkflowGenerate task in build.sbt.
     |# Do not edit it directly.
     |
     |name: Scheduled Evidence
     |
     |on:
     |  workflow_dispatch:
     |  schedule:
     |    - cron: '41 5 * * 1'
     |
     |permissions:
     |  contents: read
     |
     |concurrency:
     |  group: scheduled-evidence-${{ github.ref }}
     |  cancel-in-progress: true
     |
     |jobs:
     |""".stripMargin +
    job(
      "api-audit",
      "Audit public API inventory and executed evidence",
      "python3 tools/api-audit/run.py",
      "api-audit",
      Seq("target/api-audit/")
    ) + "\n" +
    job(
      "artifact-consumer",
      "Check the isolated published-artifact consumer",
      "python3 tools/check-docs.py --platform none --run-consumer",
      "artifact-consumer",
      Seq(
        "target/documentation-consumer.log",
        "target/study-consumer/publish.log",
        "target/study-consumer/consumer.log",
        "target/study-consumer/receipt.json"
      )
    )
}

trustWorkflowContents := {
  val sbtCommand      = githubWorkflowSbtCommand.value
  val basePermissions =
    Permissions.Specify.defaultRestrictive.withPackages(PermissionValue.None)

  val checks = GenerativePlugin.compileWorkflow(
    "Checks",
    githubWorkflowTargetBranches.value.toList,
    Nil,
    githubWorkflowTargetPaths.value,
    githubWorkflowPREventTypes.value.toList,
    Some(basePermissions),
    githubWorkflowEnv.value,
    githubWorkflowConcurrency.value,
    githubWorkflowGeneratedCI.value.toList,
    sbtCommand
  )

  // The submission graph is the published artifacts' graph. Every unpublished
  // project (the root aggregates, the guide, and the Studio projects, whose
  // Intaglio and scaladock pins exist only after studio.yml publishes them) is
  // ignored by the module name sbt-github-dependency-submission matches on.
  val unpublishedModules = submissionModule
    .all(ScopeFilter(inAnyProject))
    .value
    .collect { case (name, true) => name }
    .distinct
    .sorted

  val dependencySubmission = WorkflowJob(
    "dependency-submission",
    "Submit Dependencies",
    githubWorkflowJobSetup.value.toList ::: List(
      WorkflowStep.DependencySubmission(
        workingDirectory = None,
        modulesIgnore = Some(unpublishedModules.toList),
        configsIgnore = Some(List("test", "scala-tool", "scala-doc-tool", "test-internal")),
        token = None
      )
    ),
    sbtStepPreamble = Nil,
    cond = Some("github.event_name == 'push' && github.ref == 'refs/heads/main'"),
    permissions = Some(basePermissions.withContents(PermissionValue.Write)),
    oses = githubWorkflowOSes.value.toList.take(1),
    scalas = Nil,
    javas = githubWorkflowJavaVersions.value.toList.take(1)
  )

  val security = GenerativePlugin.compileWorkflow(
    "Security",
    List("main"),
    Nil,
    Paths.None,
    githubWorkflowPREventTypes.value.toList,
    Some(basePermissions),
    githubWorkflowEnv.value,
    githubWorkflowConcurrency.value,
    List(dependencySubmission),
    sbtCommand
  )

  val releaseJob = WorkflowJob(
    "release",
    "Publish Version Tag",
    githubWorkflowJobSetup.value.toList :::
      githubWorkflowPublishPreamble.value.toList :::
      githubWorkflowPublish.value.toList :::
      githubWorkflowPublishPostamble.value.toList,
    sbtStepPreamble = Nil,
    cond = Some("github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')"),
    permissions = Some(basePermissions),
    oses = githubWorkflowOSes.value.toList.take(1),
    scalas = Nil,
    javas = githubWorkflowJavaVersions.value.toList.take(1),
    timeoutMinutes = githubWorkflowPublishTimeoutMinutes.value
  )

  val release = GenerativePlugin.compileWorkflow(
    "Release",
    List("release-workflow-disabled"),
    List("v*"),
    Paths.None,
    githubWorkflowPREventTypes.value.toList,
    Some(basePermissions),
    githubWorkflowEnv.value,
    githubWorkflowConcurrency.value,
    List(releaseJob),
    sbtCommand
  )

  Map(
    "checks.yml"      -> checks,
    "security.yml"    -> security,
    "release.yml"     -> release,
    "clean.yml"       -> bundledCleanWorkflow,
    "performance.yml" -> eyeLinkPerformanceWorkflow,
    "evidence.yml"    -> scheduledEvidenceWorkflow,
    "studio.yml"      -> studioWorkflowContents.value
  )
}

githubWorkflowGenerate := {
  val outputDirectory = baseDirectory.value / ".github" / "workflows"
  val rendered        = trustWorkflowContents.value
  IO.createDirectory(outputDirectory)
  rendered.foreach { case (name, contents) => IO.write(outputDirectory / name, contents) }

  // ci.yml was the old mixed-permission workflow. Removal is part of the
  // generated migration, not a hand edit to generated YAML.
  IO.delete(outputDirectory / "ci.yml")
}

githubWorkflowCheck := {
  val outputDirectory = baseDirectory.value / ".github" / "workflows"
  val rendered        = trustWorkflowContents.value
  rendered.foreach { case (name, expected) =>
    val file = outputDirectory / name
    if (!file.exists()) sys.error(s"$name is missing; run githubWorkflowGenerate")
    val actual = IO.read(file)
    if (actual != expected)
      sys.error(s"$name is stale; run githubWorkflowGenerate")
  }
  val obsolete = outputDirectory / "ci.yml"
  if (obsolete.exists())
    sys.error("ci.yml still mixes code, security, and release jobs; run githubWorkflowGenerate")

  def requireText(workflow: String, required: String): Unit = {
    if (!rendered(workflow).contains(required))
      sys.error(s"$workflow is missing required generated content: $required")
  }

  def forbidText(workflow: String, forbidden: String): Unit = {
    if (rendered(workflow).contains(forbidden))
      sys.error(s"$workflow contains forbidden generated content: $forbidden")
  }

  List(
    "project: [rootJS, rootJVM]",
    "name: Compile all modules",
    "name: Test",
    "name: Run published law suites",
    "name: Check headers and formatting",
    "name: Check binary compatibility",
    "name: Generate API documentation",
    "name: Check module and kernel boundaries"
  ).foreach(requireText("checks.yml", _))
  requireText("checks.yml", "python3 tools/check-docs.py --platform jvm --skip-consumer")
  requireText("checks.yml", "python3 tools/check-docs.py --platform js --skip-consumer")
  forbidText("checks.yml", "tlCiRelease")
  forbidText("checks.yml", "sbt-dependency-submission")
  // Slow evidence belongs to evidence.yml, never to the per-push matrix.
  forbidText("checks.yml", "tools/api-audit/run.py")
  forbidText("checks.yml", "--run-consumer")

  requireText("security.yml", "contents: write")
  requireText("security.yml", "scalacenter/sbt-dependency-submission@v2")
  forbidText("security.yml", "tlCiRelease")
  List("eyes4s-studio-viz_3", "eyes4s-studio-viz_sjs1_3", "eyes4s-studio-desktop_3")
    .foreach(m => requireText("security.yml", s" $m"))

  requireText("release.yml", "tags: [v*]")
  requireText("release.yml", "startsWith(github.ref, 'refs/tags/v')")
  requireText("release.yml", "sbt tlCiRelease")
  forbidText("release.yml", "sbt-dependency-submission")

  requireText("performance.yml", "schedule:")
  requireText("performance.yml", "EyeLinkAscPerformanceMain")
  requireText("performance.yml", "--profile scheduled")
  requireText("performance.yml", "actions/upload-artifact@v4")

  requireText("evidence.yml", "schedule:")
  requireText("evidence.yml", "workflow_dispatch:")
  requireText("evidence.yml", "python3 tools/api-audit/run.py")
  requireText("evidence.yml", "python3 tools/check-docs.py --platform none --run-consumer")

  // Studio CI lives in its own workflow; the library matrix never runs it.
  requireText("studio.yml", "xvfb-run -a")
  requireText("studio.yml", "studioAll studioStyleCheck")
  requireText("studio.yml", "paths: [studio/**")
  requireText("studio.yml", "macos-15")
  requireText("studio.yml", "EYES4S_STUDIO_SMALL_DISPLAY: skip")
  forbidText("checks.yml", "studio")
}

// Both boundary invariants run in CI, not just on a developer's machine.
// A rule that is only checked locally is a rule that is checked when it is
// convenient. See bead fnd-boundaries, PRD B-9.
ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List("compile"),
  name = Some("Compile all modules")
)

ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List("lawsJVM/test", "lawsJS/test"),
  name = Some("Run published law suites"),
  cond = Some("matrix.project == 'rootJVM' && matrix.java == 'temurin@17'"),
  preamble = false
)

// The library half of checkBoundaries: resolving a studio project needs the scaladock
// and Intaglio pins, which only studio.yml publishes, so the studio resolved-graph
// rules (studioBoundaries) run there.
ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List("checkLibraryBoundaries"),
  name = Some("Check module and kernel boundaries")
)

ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List("docs/tlSite"),
  name = Some("Compile examples and build the public guide"),
  cond = Some("matrix.project == 'rootJVM' && matrix.java == 'temurin@17'"),
  preamble = false
)

// Each matrix project checks only the test reports it produced: rootJVM also owns the
// rendered site; rootJS owns the Scala.js reports. The published-artifact consumer and
// the API audit run in the scheduled evidence.yml workflow.
ThisBuild / githubWorkflowBuild += WorkflowStep.Run(
  List("python3 tools/check-docs.py --platform jvm --skip-consumer"),
  name = Some("Check public documentation coverage (JVM evidence)"),
  cond = Some("matrix.project == 'rootJVM' && matrix.java == 'temurin@17'")
)

ThisBuild / githubWorkflowBuild += WorkflowStep.Run(
  List("python3 tools/check-docs.py --platform js --skip-consumer"),
  name = Some("Check public documentation coverage (Scala.js evidence)"),
  cond = Some("matrix.project == 'rootJS' && matrix.java == 'temurin@17'")
)

ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List(
    "ioJVM/Test/runMain eyes4s.io.EyeLinkAscPerformanceMain --profile smoke --hardware github-actions-ubuntu-22.04-x64"
  ),
  name = Some("Run EyeLink performance smoke court"),
  cond = Some("matrix.project == 'rootJVM' && matrix.java == 'temurin@17'"),
  preamble = false
)

// Execution responsiveness (UI-X6, docs/EXECUTION_RESPONSIVENESS.md): the smoke
// profile reports step and cancellation times without asserting them, and fails
// only if a run breaks its outcome contract.
ThisBuild / githubWorkflowBuild += WorkflowStep.Sbt(
  List(
    "fs2ModuleJVM/Test/runMain eyes4s.fs2.ExecutionResponsivenessMain --profile smoke --hardware github-actions-ubuntu-22.04-x64"
  ),
  name = Some("Run execution responsiveness smoke profile"),
  cond = Some("matrix.project == 'rootJVM' && matrix.java == 'temurin@17'"),
  preamble = false
)

// Scala Native is deferred post-1.0 (bead q-app-target: the application target
// is a local JVM process serving a browser UI, so Native buys nothing). Every
// dependency is nonetheless kept Native-eligible so that adding the axis later
// stays a build change rather than a redesign. See PRD B-4.

// ---------------------------------------------------------------------------
// Module boundary enforcement                              (bead fnd-boundaries)
//
// Two invariants, both checked mechanically against the build graph, because
// documentation is not enforcement. See PRD PKG-4.
//
//   PKG-3  No pure module may acquire an effect system, directly or
//          transitively. Cats Effect and FS2 belong to eyes4s-fs2 and
//          eyes4s-io alone.
//
//   PKG-1  eyes4s-kernel may not depend on eyes4s-core. This is what keeps the
//          trajectory-and-measure layer free of ocular vocabulary, and it is
//          the entire cost of leaving the door open to extracting a general
//          `trace4s` later. See eyes4s.md, "Beyond gaze: the trajectory kernel".
// ---------------------------------------------------------------------------

lazy val checkModuleBoundaries =
  taskKey[Unit]("Fail if a pure module depends on an effect library.")

lazy val checkKernelPurity =
  taskKey[Unit]("Fail if eyes4s-kernel source contains ocular vocabulary.")

// The DEPENDENCY direction (kernel must not depend on core) needs no task:
// core already depends on kernel, so a kernel -> core edge is a cycle and sbt
// rejects the build at load. What is NOT structurally prevented -- and is the
// failure mode that actually matters -- is someone declaring `Fixation` or
// `Saccade` inside the kernel. That is a CONTENT violation, and it is what
// PRD A-3 describes. This word list is that documented list, made executable.
val ocularVocabulary = Set(
  "gaze",
  "fixation",
  "saccade",
  "blink",
  "pursuit",
  "scanpath",
  "pupil",
  "ocular",
  "fovea",
  "foveal",
  "microsaccade",
  "vergence",
  "eyetrack",
  "eyelink",
  "tobii",
  "viewing",
  "cyclopean",
  "nystagmus"
)

def forbiddenInPureModules(org: String, name: String): Boolean =
  (org == "org.typelevel" && name.startsWith("cats-effect")) ||
    org == "co.fs2"

lazy val pureModuleSettings = pureModuleSettingsForbidding((_, _) => false)

/** The pure-module boundary with `also` forbidden besides the effect systems. */
def pureModuleSettingsForbidding(also: (String, String) => Boolean) = Seq(
  checkModuleBoundaries := {
    val log        = streams.value.log
    val moduleName = name.value
    val offenders  = update.value.allModules
      .filter(m =>
        forbiddenInPureModules(m.organization, m.name) || also(m.organization, m.name)
      )
      .map(m => s"${m.organization}:${m.name}:${m.revision}")
      .distinct
      .sorted
    if (offenders.nonEmpty)
      sys.error(
        s"""|Module boundary violation in $moduleName.
            |
            |Pure modules must not depend on an effect system (and eyes4s-results on no
            |JSON library), but the resolved
            |dependency graph contains:
            |${offenders.map("  - " + _).mkString("\n")}
            |
            |Move the offending code to eyes4s-fs2 or eyes4s-io.""".stripMargin
      )
    else
      log.info(s"$moduleName: module boundaries OK (no effect deps)")
  }
)

// Comments are stripped before scanning, so scaladoc may still explain the
// boundary in the words it is drawing. Only declarations are checked.
ThisBuild / checkKernelPurity := {
  val log     = streams.value.log
  val srcRoot = (ThisBuild / baseDirectory).value / "kernel" / "src"

  // Blank out comments while PRESERVING newlines, so reported line numbers
  // still refer to the real file rather than to the stripped body.
  def blankOut(m: scala.util.matching.Regex.Match): String =
    m.matched.map(c => if (c == '\n') '\n' else ' ')

  def stripComments(s: String): String = {
    val noBlock = "(?s)/\\*.*?\\*/".r.replaceAllIn(s, blankOut _)
    "//[^\n]*".r.replaceAllIn(noBlock, blankOut _)
  }

  val pattern = ocularVocabulary.mkString("(?i)\\b(", "|", ")\\w*\\b").r

  val sources =
    if (srcRoot.exists) (srcRoot ** "*.scala").get else Nil

  val offenders = sources
    .flatMap { f =>
      val body = stripComments(IO.read(f))
      pattern.findAllMatchIn(body).map { m =>
        val line = body.take(m.start).count(_ == '\n') + 1
        s"  - ${f.getName}:$line  '${m.matched}'"
      }
    }
    .distinct
    .sorted

  if (offenders.nonEmpty)
    sys.error(
      s"""|Kernel purity violation.
          |
          |eyes4s-kernel is the trajectory-and-measure layer: it describes timed
          |paths through a typed geometry and the measures they induce. It must
          |contain no ocular vocabulary, so that a general `trace4s` -- mouse
          |tracking, animal tracking, VR navigation -- stays extractable.
          |
          |Found in kernel sources:
          |${offenders.mkString("\n")}
          |
          |Either move this to eyes4s-core, or generalise the concept until it
          |belongs in the kernel. See eyes4s.md, "Beyond gaze: the trajectory
          |kernel", and PRD A-3.""".stripMargin
    )
  else
    log.info(s"kernel purity OK (${sources.size} source(s) scanned, no ocular vocabulary)")
}

lazy val commonSettings = Seq(
  libraryDependencies ++= Seq(
    "org.scalameta" %%% "munit"            % munitV           % Test,
    "org.scalameta" %%% "munit-scalacheck" % munitScalacheckV % Test
  )
)

// ---------------------------------------------------------------------------
// Modules
// ---------------------------------------------------------------------------

lazy val root = tlCrossRootProject
  .aggregate(
    kernel,
    core,
    detect,
    surface,
    aoi,
    compare,
    design,
    plan,
    results,
    codec,
    laws,
    fs2Module,
    io
  )

/** Geometry, time, trajectories, measures, grids, surfaces, regions, machines.
  *
  * No ocular vocabulary. Enforced by `checkKernelPurity`.
  */
lazy val kernel = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("kernel"))
  .settings(commonSettings, pureModuleSettings)
  .settings(
    name                                    := "eyes4s-kernel",
    libraryDependencies += "org.typelevel" %%% "cats-core" % catsV
  )

/** The eye-specific layer: Gaze, Sample, Recording, BinocularRecording, Event,
  * Scanpath, Viewing.
  */
lazy val core = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("core"))
  .dependsOn(kernel)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-core")

/** Detector instances, filters, and the Machine runner. */
lazy val detect = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("detect"))
  .dependsOn(core)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-detect")

/** Smoothers, bandwidth selection, pyramids, entropy. */
lazy val surface = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("surface"))
  .dependsOn(core)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-surface")

/** AOI sets, dwell/entry/run statistics, transition matrices. */
lazy val aoi = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("aoi"))
  .dependsOn(core)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-aoi")

/** Compare hierarchy, alignment kernel, MultiMatch, distribution measures, OT. */
lazy val compare = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("compare"))
  .dependsOn(core, surface, aoi)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-compare")

/** Trials, pairings, baselines, contrasts, deterministic RNG. */
lazy val design = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("design"))
  .dependsOn(core, compare)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-design")

/** Analyses as descriptions: plan ADTs, interpreters, and the typed registry. */
lazy val plan = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("plan"))
  .dependsOn(design, detect)
  .settings(commonSettings, pureModuleSettings)
  .settings(name := "eyes4s-plan")

/** Reports and result tables: pure reductions over stored results with typed
  * trial covariates, and the one result-table layer every export renders.
  * No JSON library and no effect system, so a Scala.js client can use it.
  */
lazy val results = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("results"))
  .dependsOn(plan)
  // No JSON library either, so a Scala.js client reads tables without one.
  .settings(commonSettings, pureModuleSettingsForbidding((org, _) => org == "io.circe"))
  .settings(
    name := "eyes4s-results",
    // The plan catalog's samples and alignment check, so the results suites
    // check both code tables together.
    Test / unmanagedSources ++= Seq(
      file("plan/src/test/scala/eyes4s/plan/DiagnosticSamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticExamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticAlignment.scala").getAbsoluteFile
    )
  )

/** JSON codecs with a versioned schema, so a project file round-trips. */
lazy val codec = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("codec"))
  .dependsOn(plan, results)
  .settings(commonSettings, pureModuleSettings)
  .settings(
    name := "eyes4s-codec",
    Test / unmanagedSources ++= Seq(
      file("laws/src/test/scala/eyes4s/examples/MatchedControlFixtures.scala").getAbsoluteFile,
      // The plan catalog's samples and alignment check, so the codec suites
      // check both code tables together.
      file("plan/src/test/scala/eyes4s/plan/DiagnosticSamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticExamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticAlignment.scala").getAbsoluteFile,
      file(
        "results/src/test/scala/eyes4s/results/ResultsDiagnosticSamples.scala"
      ).getAbsoluteFile
    ),
    libraryDependencies ++= Seq(
      "io.circe" %%% "circe-core"   % circeV,
      "io.circe" %%% "circe-parser" % circeV
    )
  )

/** Discipline rule sets and ScalaCheck generators.
  *
  * munit, scalacheck and discipline are MAIN-scope dependencies here, not Test:
  * the suites are library code that downstream authors run against their own
  * instances. See PRD PKG-6.
  */
lazy val laws = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("laws"))
  .dependsOn(kernel, core, detect, surface, aoi, compare, design, plan, results, codec)
  .settings(pureModuleSettings)
  .settings(
    name := "eyes4s-laws",
    Test / unmanagedSources ++= Seq(
      file("codec/src/test/scala/eyes4s/codec/PointSamplingFixture.scala").getAbsoluteFile,
      file("codec/src/test/scala/eyes4s/codec/RepetitionPlanFixture.scala").getAbsoluteFile
    ),
    libraryDependencies ++= Seq(
      "org.scalameta"  %%% "munit"            % munitV,
      "org.scalameta"  %%% "munit-scalacheck" % munitScalacheckV,
      "org.typelevel"  %%% "discipline-munit" % disciplineMunitV,
      "org.typelevel"  %%% "cats-laws"        % catsLawsV,
      "org.scalacheck" %%% "scalacheck"       % scalacheckV
    )
  )
  .jvmSettings(
    // UI-S6: the schema registry suite checks every pinned v1 codec fixture.
    Test / unmanagedResourceDirectories += file("codec/src/test/resources").getAbsoluteFile
  )

/** Streaming execution: Machine.toPipe, progress events, cancellation. */
lazy val fs2Module = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("fs2"))
  .dependsOn(core, detect, plan)
  .settings(commonSettings)
  .settings(
    name := "eyes4s-fs2",
    libraryDependencies ++= Seq(
      "org.typelevel" %%% "cats-effect"         % catsEffectV,
      "co.fs2"        %%% "fs2-core"            % fs2V,
      "org.typelevel" %%% "cats-effect-testkit" % catsEffectV      % Test,
      "org.typelevel" %%% "munit-cats-effect"   % munitCatsEffectV % Test
    )
  )
  .jvmSettings(
    // The pinned runtime of ExecutionResponsivenessMain (docs/EXECUTION_RESPONSIVENESS.md):
    // a fixed heap, the default collector named explicitly, and four processors so the
    // global IORuntime has the compute pool of a four-vCPU CI runner on any host.
    Test / run / fork := true,
    Test / run / javaOptions ++= Seq(
      "-Xms2g",
      "-Xmx2g",
      "-XX:+UseG1GC",
      "-XX:ActiveProcessorCount=4"
    )
  )

/** Ingest and export: EyeLink ASC, CSV, Mirror-derived metadata decoders. */
lazy val io = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .jvmSettings(ApiAudit.settings)
  .in(file("io"))
  .dependsOn(fs2Module, codec, laws % Test)
  .settings(commonSettings)
  .settings(
    name := "eyes4s-io",
    Test / unmanagedSources ++= Seq(
      file("laws/src/test/scala/eyes4s/examples/MatchedControlFixtures.scala").getAbsoluteFile,
      file("docs/examples/StudyGuide.scala").getAbsoluteFile,
      file("docs/examples/TemporalStudyGuide.scala").getAbsoluteFile,
      file("codec/src/test/scala/eyes4s/codec/TemporalFixtures.scala").getAbsoluteFile,
      file("codec/src/test/scala/eyes4s/codec/StudyInputFixtures.scala").getAbsoluteFile,
      // Every catalog's samples and alignment check, so io checks all code
      // tables together and enumerates every public error enum.
      file("plan/src/test/scala/eyes4s/plan/DiagnosticSamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticExamples.scala").getAbsoluteFile,
      file("plan/src/test/scala/eyes4s/plan/DiagnosticAlignment.scala").getAbsoluteFile,
      file("codec/src/test/scala/eyes4s/codec/CodecDiagnosticSamples.scala").getAbsoluteFile,
      file(
        "results/src/test/scala/eyes4s/results/ResultsDiagnosticSamples.scala"
      ).getAbsoluteFile
    ),
    libraryDependencies += "co.fs2" %%% "fs2-io" % fs2V
  )
  .jvmSettings(
    Test / sourceGenerators += Def.task {
      val out  = (Test / sourceManaged).value / "DocumentationExamplesSuite.scala"
      val exit = scala.sys.process
        .Process(
          Seq("python3", "tools/documentation-examples.py", out.getAbsolutePath),
          file(".")
        )
        .!
      require(exit == 0, "Documentation example generation failed")
      Seq(out)
    }.taskValue,
    // Optional JVM-only Arrow transport; portable tables have no Arrow dependency.
    libraryDependencies ++= Seq(
      "org.apache.arrow" % "arrow-vector"        % "19.0.0"         % Optional,
      "org.apache.arrow" % "arrow-memory-unsafe" % "19.0.0"         % Optional,
      "org.typelevel"   %% "munit-cats-effect"   % munitCatsEffectV % Test
    ),
    Test / fork := true,
    Test / javaOptions ++= Seq(
      "-Xmx2g",
      "-Dfile.encoding=UTF-8",
      "-Dstdout.encoding=UTF-8",
      "--add-opens=java.base/java.nio=ALL-UNNAMED"
    ),
    Test / unmanagedSourceDirectories += file("tools/study-cli").getAbsoluteFile,
    Test / parallelExecution := false,
    Test / run / fork        := true,
    Test / run / javaOptions ++= Seq(
      "-Xms64m",
      "-Xmx256m",
      "--add-opens=java.base/java.nio=ALL-UNNAMED"
    ),
    // UI-S6: FreshProcessReconstructionJvmSuite writes and reads saved studies in
    // separate, freshly started JVMs over this test classpath, from the pinned
    // v1 codec fixtures. The classpath is written as a test resource because an
    // unforked test cannot read it from java.class.path.
    Test / unmanagedResourceDirectories += file("codec/src/test/resources").getAbsoluteFile,
    Test / resourceGenerators += Def.task {
      val out = (Test / resourceManaged).value / "eyes4s" / "fresh-process" / "classpath.txt"
      val entries = (Test / classDirectory).value +: (Test / dependencyClasspath).value.files
      IO.write(out, entries.map(_.getAbsolutePath).mkString(java.io.File.pathSeparator))
      Seq(out)
    }.taskValue
  )

// ---------------------------------------------------------------------------
// Eyes Studio                                   (DESIGN_SPEC section 13, S0.2)
//
// The application, not the library. None of these projects joins the root
// aggregate, compileAll or testAll: the library CI matrix must not grow, and
// studio-desktop needs a newer JDK than that matrix runs. They build and test
// through the `studioAll` alias only, and are never published.
//
//   studio-core     document, commands, services, StudyBackend. Effect-permitted.
//   studio-app      UI-neutral Elm-style presentation layer. Pure.
//   studio-viz      Intaglio scene builders. Pure.
//   studio-desktop  JavaFX shell. JVM-only, effect-permitted.
//
// The first three cross-build for Scala.js and may name no JavaFX artifact or
// JVM platform package; see project/StudioLint.scala and `checkStudioBoundaries`.
// ---------------------------------------------------------------------------

// studio-desktop: minimum JDK 22 (JavaFX 24); JDK 25 LTS recommended and used
// in CI. The library keeps release 11.
val javaFxV           = "24.0.1"
val studioDesktopJdkV = 22

// Source pins (S0.3). scaladock and Intaglio are source-only pre-release. Each
// is pinned by a full Git SHA in studio/pins.properties and resolved as
// 0.0.0-<sha>, which studio/publish-pins.sh builds from exactly that commit and
// publishes locally. No external build is loaded by default, so the library
// build never clones anything. `-Dstudio.<name>.local=<checkout>` substitutes
// a local checkout as a source dependency; there is no implicit sibling.
// studio/README.md documents both paths.
lazy val studioPins: java.util.Properties = {
  val props = new java.util.Properties
  IO.load(props, file("studio/pins.properties").getAbsoluteFile)
  props
}

def studioPinVersion(name: String): String = {
  val revision = Option(studioPins.getProperty(s"$name.revision")).getOrElse("")
  if (!revision.matches("[0-9a-f]{40}"))
    sys.error(s"studio/pins.properties: $name.revision is not a full Git SHA: '$revision'")
  s"0.0.0-$revision"
}

def studioPinOrganization(name: String): String =
  Option(studioPins.getProperty(s"$name.organization"))
    .getOrElse(sys.error(s"studio/pins.properties has no $name.organization"))

def studioLocalCheckout(name: String): Option[URI] =
  sys.props.get(s"studio.$name.local").map { path =>
    val dir = file(path).getAbsoluteFile.getCanonicalFile
    if (!(dir / "build.sbt").isFile)
      sys.error(s"-Dstudio.$name.local=$path: $dir is not an sbt build (no build.sbt)")
    dir.toURI
  }

lazy val intaglioLocal  = studioLocalCheckout("intaglio")
lazy val scaladockLocal = studioLocalCheckout("scaladock")

// JVM-only pinned artifacts, and the local projects that replace pins.
def intaglioPinned(module: String) =
  studioPinOrganization("intaglio") %% s"intaglio-$module" % studioPinVersion("intaglio")
def scaladockPinned(module: String) =
  studioPinOrganization("scaladock") %% s"scaladock-$module" % studioPinVersion("scaladock")
def studioLocalRefs(
    local: Option[URI],
    projects: String*
): Seq[ClasspathDep[ProjectReference]] =
  local.toSeq.flatMap(uri => projects.map(p => ClasspathDependency(ProjectRef(uri, p), None)))

lazy val checkStudioBoundaries =
  taskKey[Unit]("Fail if a library module depends on studio, or portable studio names JavaFX.")

// The resolved-graph half of the portable-studio rule: a portable studio project
// may resolve no JavaFX artifact, directly or transitively.
lazy val portableStudioSettings = Seq(
  checkModuleBoundaries := {
    val log        = streams.value.log
    val moduleName = name.value
    val offenders  = update.value.allModules
      .filter(m => StudioLint.forbiddenInPortableStudio(m.organization, m.name))
      .map(m => s"${m.organization}:${m.name}:${m.revision}")
      .distinct
      .sorted
    if (offenders.nonEmpty)
      sys.error(
        s"""|Studio boundary violation in $moduleName.
            |
            |Portable studio projects cross-build for Scala.js and must not resolve
            |a JavaFX artifact, but the resolved dependency graph contains:
            |${offenders.map("  - " + _).mkString("\n")}
            |
            |Move the JavaFX-facing code to studio-desktop (DESIGN_SPEC section 13).""".stripMargin
      )
    else
      log.info(s"$moduleName: studio boundaries OK (no JavaFX artifacts)")
  }
)

// Rules 1 and 3 of StudioLint, preceded by its self-test on planted violations.
ThisBuild / checkStudioBoundaries := {
  val log       = streams.value.log
  val buildRoot = (ThisBuild / baseDirectory).value

  val selfTest = StudioLint.selfTest
  if (selfTest.nonEmpty)
    sys.error(
      s"""|StudioLint self-test failed: a studio boundary rule no longer detects
          |a planted violation.
          |${selfTest.map("  - " + _).mkString("\n")}""".stripMargin
    )

  val graph = buildDependencies.value.classpath.map { case (project, deps) =>
    project.project -> deps.map(_.project.project)
  }
  val edges = StudioLint.libraryToStudioEdges(graph, _.startsWith("studio"))
  if (edges.nonEmpty)
    sys.error(
      s"""|Studio boundary violation: a library module depends on a studio project.
          |
          |${edges.map(p => "  - " + p.mkString(" -> ")).mkString("\n")}
          |
          |eyes4s modules must stay usable without the application. Move the
          |shared code into the library, or the dependency into studio.""".stripMargin
    )

  val imports = StudioLint.scanTree(buildRoot)
  if (imports.nonEmpty)
    sys.error(
      s"""|Studio boundary violation: portable studio sources name a JVM-only package.
          |
          |${imports.map("  - " + _.render).mkString("\n")}
          |
          |studio-core, studio-app and studio-viz cross-build for Scala.js and may not
          |name ${StudioLint.forbiddenPackages.mkString(", ")}. Put the code in
          |studio-desktop behind a platform-service interface (DESIGN_SPEC section 13).""".stripMargin
    )

  val effects =
    StudioLint.scanTree(buildRoot, StudioLint.pureSourceRoots, StudioLint.effectPackages)
  if (effects.nonEmpty)
    sys.error(
      s"""|Studio boundary violation: pure presentation sources name an effect library.
          |
          |${effects.map("  - " + _.render).mkString("\n")}
          |
          |studio-app and studio-viz describe effects as data and may not name
          |${StudioLint.effectPackages.mkString(", ")}. Run effects in studio-core or
          |studio-desktop (DESIGN_SPEC section 13).""".stripMargin
    )

  val members = StudioLint.scanMemberTree(buildRoot)
  if (members.nonEmpty)
    sys.error(
      s"""|Studio boundary violation: studio sources call an unbound report constructor.
          |
          |${members.map("  - " + _.render).mkString("\n")}
          |
          |Obtain bound reports through eyes4s.codec.ReportSources.study; the
          |constructors ${StudioLint.forbiddenMembers.mkString(
           ", "
         )} take no source binding.""".stripMargin
    )

  log.info(
    s"studio boundaries OK (lint self-test passed; ${graph.size} project(s) have no " +
      "library-to-studio edge; no JVM-only package in portable studio sources; " +
      "no effect library in studio-app or studio-viz sources; no unbound report constructor)"
  )
}

/** Document, commands, revisions, services and the StudyBackend protocol. */
lazy val studioCore = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("studio/core"))
  .enablePlugins(NoPublishPlugin)
  .dependsOn(plan, codec, fs2Module)
  .settings(commonSettings, portableStudioSettings)
  .settings(
    name := "eyes4s-studio-core",
    // S3.0: the backend protocol's codecs (circe, pinned with eyes4s-codec) and
    // its effect tests.
    libraryDependencies ++= Seq(
      "io.circe"      %%% "circe-core"        % circeV,
      "io.circe"      %%% "circe-parser"      % circeV,
      "io.circe"      %%% "circe-jawn"        % circeV,
      "org.typelevel" %%% "munit-cats-effect" % munitCatsEffectV % Test
    ),
    // S3.0: studio-core may not read files (it links for Scala.js), so the mock
    // study and the acceptance fixture's inventory are generated sources.
    Compile / sourceGenerators += Def.task {
      StudioFixture.generate(
        (ThisBuild / baseDirectory).value,
        (Compile / sourceManaged).value / "eyes4s" / "studio",
        streams.value.cacheDirectory / "studio-fixture"
      )
    }.taskValue,
    // S9.2b: the eyes4s release line of the studio build, for a figure's
    // stamp. The base version only (no commit or timestamp), so the source is
    // written once, not on every load. Generated, since studio-core reads no
    // resources (it links for Scala.js).
    Compile / sourceGenerators += Def.task {
      val file = (Compile / sourceManaged).value / "eyes4s" / "studio" / "StudioBuild.scala"
      val text =
        s"""package eyes4s.studio.core.engine
           |
           |/** The studio build (generated from the sbt build). */
           |object StudioBuild:
           |  /** The eyes4s release line studio is built from. */
           |  val eyes4sBaseVersion: String = "${tlBaseVersion.value}"
           |""".stripMargin
      if (!file.exists || IO.read(file) != text) IO.write(file, text)
      Seq(file)
    }.taskValue,
    // The generator's planted off-screen scanpaths, which a JVM test holds
    // against eyes4s-io's own admission (fixture off-screen fix).
    Test / sourceGenerators += Def.task {
      StudioFixture.plantedScanpaths(
        (Test / sourceManaged).value / "eyes4s" / "studio" / "PlantedScanpaths.scala"
      )
    }.taskValue
  )
  .jvmConfigure(_.dependsOn(io.jvm % Test))
  // S5.4: the golden tables' text, for the JVM suite that admits them with
  // eyes4s-io under the story's recorded mappings.
  .jvmSettings(
    Test / sourceGenerators += Def.task {
      StudioFixture.goldenCsv(
        (ThisBuild / baseDirectory).value,
        (Test / sourceManaged).value / "eyes4s" / "studio" / "GoldenCsv.scala"
      )
    }.taskValue
  )

/** UI-neutral presentation: app model, intents, pure update, view-models. */
lazy val studioApp = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("studio/app"))
  .enablePlugins(NoPublishPlugin)
  // S1.0: the app's law suites reuse studio-core's document and command generators.
  .dependsOn(studioCore % "compile->compile;test->test")
  .settings(commonSettings, portableStudioSettings)
  .settings(name := "eyes4s-studio-app")

/** Intaglio scene builders over view-models, on Intaglio core, interaction and svg. */
lazy val studioViz = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("studio/viz"))
  .enablePlugins(NoPublishPlugin)
  .dependsOn(studioApp)
  .jvmConfigure(
    _.dependsOn(studioLocalRefs(intaglioLocal, "coreJVM", "interactionJVM", "svgJVM"): _*)
  )
  .jsConfigure(
    _.dependsOn(studioLocalRefs(intaglioLocal, "coreJS", "interactionJS", "svgJS"): _*)
  )
  .settings(commonSettings, portableStudioSettings)
  .settings(
    name := "eyes4s-studio-viz",
    libraryDependencies ++= {
      if (intaglioLocal.isDefined) Nil
      else
        Seq("core", "interaction", "svg").map { m =>
          studioPinOrganization("intaglio") %%% s"intaglio-$m" % studioPinVersion("intaglio")
        }
    }
  )

// OpenJFX publishes one native jar per platform, selected by classifier. The
// host is detected; `-Djavafx.platform=<classifier>` overrides it. Packaging
// runs once per OS on a native runner (S0.4), so no build mixes classifiers.
lazy val javaFxClassifier: String = {
  val os       = sys.props.getOrElse("os.name", "").toLowerCase
  val arch     = sys.props.getOrElse("os.arch", "").toLowerCase
  val aarch64  = arch == "aarch64" || arch == "arm64"
  val detected =
    if (os.contains("mac")) { if (aarch64) "mac-aarch64" else "mac" }
    else if (os.contains("win")) "win"
    else if (os.contains("linux")) { if (aarch64) "linux-aarch64" else "linux" }
    else s"unsupported-os-$os" // resolution then fails and names the host
  sys.props.get("javafx.platform").getOrElse(detected)
}

/** The JavaFX shell: renders view-models and dispatches intents. JVM only. */
lazy val studioDesktop = project
  .in(file("studio/desktop"))
  .enablePlugins(NoPublishPlugin)
  .dependsOn(studioViz.jvm)
  // S9.5: export bundles write result tables through eyes4s-io's CSV transport.
  .dependsOn(io.jvm)
  // S2.3: the file-system ProjectStore runs studio-core's conformance suite.
  .dependsOn(studioCore.jvm % "test->test")
  // S1.4: the shell FX suites boot at the S1.0 story models (StoryModels).
  .dependsOn(studioApp.jvm % "test->test")
  .dependsOn(studioLocalRefs(intaglioLocal, "javafxJVM", "pdfJVM", "java2dJVM"): _*)
  .dependsOn(studioLocalRefs(scaladockLocal, "core", "fx"): _*)
  .settings(commonSettings)
  .settings(
    name         := "eyes4s-studio-desktop",
    tlJdkRelease := Some(studioDesktopJdkV),
    libraryDependencies ++= Seq("javafx-base", "javafx-graphics", "javafx-controls").map(
      "org.openjfx" % _ % javaFxV classifier javaFxClassifier
    ),
    libraryDependencies ++=
      (if (intaglioLocal.isDefined) Nil
       else Seq("javafx", "pdf", "java2d").map(intaglioPinned)) ++
        (if (scaladockLocal.isDefined) Nil
         else Seq(scaladockPinned("core"), scaladockPinned("fx"))),
    // One JavaFX for the shell and both providers. Intaglio and scaladock
    // declare it `Provided` (21.0.5 and 24.0.1), which does not reach us; since
    // scaladock 3ed443e (still at 628c46f) ScalaFX is demo-only. No override: a clash must reach the
    // guard below, which requires exactly base, graphics and controls at javaFxV.
    checkModuleBoundaries := {
      val log       = streams.value.log
      val allowed   = Set("javafx-base", "javafx-graphics", "javafx-controls")
      val openjfx   = update.value.allModules.filter(_.organization == "org.openjfx")
      val offenders = openjfx
        .filter(m => m.revision != javaFxV || !allowed(m.name))
        .map(m => s"${m.organization}:${m.name}:${m.revision}")
        .distinct
        .sorted
      val missing = allowed -- openjfx.map(_.name)
      if (offenders.nonEmpty || missing.nonEmpty)
        sys.error(
          s"""|studio-desktop must resolve exactly ${allowed.toSeq.sorted
               .mkString(", ")} at OpenJFX $javaFxV.
              |Unexpected: ${offenders.mkString(", ")}
              |Missing: ${missing.toSeq.sorted.mkString(", ")}""".stripMargin
        )
      else log.info(s"eyes4s-studio-desktop: OpenJFX $javaFxV base/graphics/controls only")
    },
    // FX tests (StudioFxSuite, S0.4) start the toolkit once per forked JVM.
    Test / fork := true,
    Test / javaOptions ++= studioFxTestOptions((ThisBuild / baseDirectory).value)
  )
  .settings(studioTokenSettings)

// Snapshots go to <build>/target/studio-snapshots/<suite>/<test>/<theme>-<scale>x.png.
// java.awt.headless keeps AWT (used only for PNG encoding) off the display. On CI,
// as in scaladock, JavaFX renders through the software pipeline; Linux CI wraps
// sbt in xvfb-run. Greyscale text antialiasing keeps software snapshots stable.
def studioFxTestOptions(buildRoot: File): Seq[String] =
  Seq(
    s"-Deyes4s.studio.snapshots=${(buildRoot / "target" / "studio-snapshots").getAbsolutePath}",
    "-Djava.awt.headless=true"
  ) ++ (if (sys.env.contains("CI")) Seq("-Dprism.order=sw", "-Dprism.lcdtext=false") else Nil)

lazy val studioCrossModules = Seq("studioCore", "studioApp", "studioViz")
lazy val studioProjects     =
  studioCrossModules.flatMap(m => allPlatforms.map(p => s"$m$p")) :+ "studioDesktop"

// The resolved-graph rule on each studio project. Each resolves the scaladock and
// Intaglio pins, so these run in studio.yml after the pins are published, and in the
// local checkBoundaries. The build-level studio rules (checkStudioBoundaries,
// checkStudioColours) read the project graph and sources only; they stay in
// checkLibraryBoundaries.
lazy val studioBoundaryChecks =
  studioCrossModules.flatMap(m => allPlatforms.map(p => s"$m$p/checkModuleBoundaries")) :+
    "studioDesktop/checkModuleBoundaries"

addCommandAlias("studioBoundaries", studioBoundaryChecks.mkString(";", ";", ""))

addCommandAlias(
  "studioAll",
  (studioProjects.map(p => s"$p/test") :+ "studioAppJS/fastLinkJS").mkString(";", ";", "")
)

// The root headerCheckAll and scalafmtCheckAll cover the aggregate only.
// checkStudioTypeScale (S1.2) is defined with the token settings below.
addCommandAlias(
  "studioStyleCheck",
  ("checkStudioTypeScale" +: studioProjects
    .flatMap(p => Seq(s"$p/headerCheckAll", s"$p/scalafmtCheckAll")))
    .mkString(";", ";", "")
)

// Studio CI (S0.4): its own workflow, studio.yml, on JDK 25, never in the
// library matrix or checks.yml. Linux runs everything under a virtual display and owns
// snapshots (and, later, goldens); macOS runs the functional FX tests only.
// OpenJFX natives are named per runner with -Djavafx.platform.
lazy val studioJdk = JavaSpec.temurin("25")

// Every studio job resolves scaladock and Intaglio as pinned artifacts (S0.3),
// so each one publishes the pins from their remotes before sbt runs.
def studioJobSetup: List[WorkflowStep] =
  List(WorkflowStep.CheckoutFull, WorkflowStep.SetupSbt) ::: WorkflowStep.SetupJava(
    List(studioJdk)
  ) ::: List(
    WorkflowStep.Run(
      List("bash studio/publish-pins.sh"),
      name = Some("Publish the scaladock and Intaglio pins")
    )
  )

// studio-clean-clone (S0.3): the pins resolve on a fresh runner, and the
// explicit local-checkout override builds against the same pinned commits.
lazy val studioCleanCloneJob = {
  def checkout(name: String) =
    s"target/studio-pins/$name-${studioPinVersion(name).stripPrefix("0.0.0-")}"
  WorkflowJob(
    "studio-clean-clone",
    "Studio pins from a clean clone",
    studioJobSetup ::: List(
      WorkflowStep.Run(
        List(
          "sbt -J-Xmx6g -Djavafx.platform=linux" +
            s" -Dstudio.intaglio.local=${checkout("intaglio")}" +
            s" -Dstudio.scaladock.local=${checkout("scaladock")}" +
            " studioVizJVM/test studioVizJS/test studioDesktop/Test/compile" +
            " studioDesktop/checkModuleBoundaries"
        ),
        name = Some("Build studio through the local-checkout override")
      )
    ),
    sbtStepPreamble = Nil,
    oses = List("ubuntu-22.04"),
    scalas = Nil,
    javas = List(studioJdk),
    timeoutMinutes = Some(60)
  )
}

lazy val studioLinuxJob = WorkflowJob(
  "studio-linux",
  "Studio (Linux, headless JavaFX)",
  studioJobSetup ::: List(
    WorkflowStep.Use(
      UseRef.Public("actions", "setup-python", "v6"),
      name = Some("Setup Python"),
      params = Map("python-version" -> "3.14")
    ),
    WorkflowStep.Run(
      List(
        "tmp=\"$(mktemp -d)\"",
        "(cd \"$tmp\" && python3 \"$GITHUB_WORKSPACE/docs/studio/fixture/make_fixture.py\" > /dev/null)",
        "diff -u docs/studio/fixture/FIXTURE.md \"$tmp/FIXTURE.md\"",
        "diff -u docs/studio/fixture/fixture.json \"$tmp/fixture.json\""
      ),
      name = Some("Check the studio design fixture regenerates")
    ),
    WorkflowStep.Run(
      List("python3 tools/studio-fixture/generate.py --check"),
      name = Some("Check the studio acceptance fixture is current")
    ),
    WorkflowStep.Run(
      List("python3 tools/studio-fixture/verify_counts.py"),
      name = Some("Verify studio fixture counts")
    ),
    WorkflowStep.Run(
      List(
        "xvfb-run -a -s '-screen 0 1920x1200x24' sbt -J-Xmx8g -Djavafx.platform=linux studioAll studioStyleCheck"
      ),
      name = Some("Build and test studio (xvfb, software pipeline)")
    ),
    WorkflowStep.Run(
      List("sbt -J-Xmx4g -Djavafx.platform=linux studioBoundaries"),
      name = Some("Check studio resolved-graph boundaries")
    ),
    WorkflowStep.Use(
      UseRef.Public("actions", "upload-artifact", "v4"),
      name = Some("Upload studio snapshots"),
      cond = Some("always()"),
      params = Map(
        "name"              -> "studio-snapshots-linux-${{ github.sha }}",
        "path"              -> "target/studio-snapshots/",
        "if-no-files-found" -> "warn"
      )
    ),
    WorkflowStep.Run(
      List(
        "if [ -z \"$(find target/studio-snapshots -name '*.png' -print -quit 2>/dev/null)\" ]; then",
        "  echo '::error::no PNG under target/studio-snapshots: the FX snapshot tests wrote nothing'",
        "  exit 1",
        "fi"
      ),
      name = Some("Require studio snapshots"),
      cond = Some("success()")
    )
  ),
  sbtStepPreamble = Nil,
  oses = List("ubuntu-22.04"),
  scalas = Nil,
  javas = List(studioJdk),
  timeoutMinutes = Some(60)
)

lazy val studioMacosJob = WorkflowJob(
  "studio-macos",
  "Studio (macOS, functional JavaFX)",
  studioJobSetup ::: List(
    WorkflowStep.Run(
      List("sbt -J-Xmx4g -Djavafx.platform=mac-aarch64 studioDesktop/test"),
      name = Some("Run functional JavaFX tests (no goldens)"),
      // The runner's display is 1024x768, which clamps a 1440x900 stage: tests
      // that need the full stage skip here and run in the Linux job.
      env = Map("EYES4S_STUDIO_SMALL_DISPLAY" -> "skip")
    )
  ),
  sbtStepPreamble = Nil,
  oses = List("macos-15"),
  scalas = Nil,
  javas = List(studioJdk),
  timeoutMinutes = Some(60)
)

// studio.yml: rendered with the same generator as checks.yml, and listed in
// trustWorkflowContents so githubWorkflowCheck keeps it current.
lazy val studioWorkflowPaths = List(
  "studio/**",
  "fixtures/studio-golden/**",
  "fixtures/studio-bundles/**",
  "tools/studio-fixture/**",
  "docs/studio/fixture/**",
  "build.sbt",
  "project/**",
  ".github/workflows/studio.yml"
) ++ Seq(
  "kernel",
  "core",
  "detect",
  "surface",
  "aoi",
  "compare",
  "design",
  "plan",
  "results",
  "codec",
  "fs2"
)
  .map(dir => s"$dir/**")

lazy val studioWorkflowContents = taskKey[String]("Render the Eyes Studio workflow.")

studioWorkflowContents := GenerativePlugin.compileWorkflow(
  "Studio",
  githubWorkflowTargetBranches.value.toList,
  Nil,
  Paths.Include(studioWorkflowPaths),
  githubWorkflowPREventTypes.value.toList,
  Some(Permissions.Specify.defaultRestrictive.withPackages(PermissionValue.None)),
  githubWorkflowEnv.value,
  githubWorkflowConcurrency.value,
  List(studioLinuxJob, studioMacosJob, studioCleanCloneJob),
  githubWorkflowSbtCommand.value
)

// Design tokens (S1.1). eyes4s.studio.app.tokens.Tokens is the one colour
// source; TokenFiles generates the checked-in JavaFX stylesheets and the web
// custom properties (docs/studio/tokens/) from it. TokenFilesSuite (studioAll)
// fails when one is stale; `studioTokens` rewrites them. checkStudioColours
// (checkBoundaries) rejects a literal colour anywhere else in studio sources.
lazy val checkStudioColours =
  taskKey[Unit]("Fail on a literal colour in studio sources outside the token source.")

ThisBuild / checkStudioColours := {
  val log       = streams.value.log
  val buildRoot = (ThisBuild / baseDirectory).value
  val selfTest  = NoLiteralColourLint.selfTest
  if (selfTest.nonEmpty)
    sys.error(
      s"""|NoLiteralColourLint self-test failed: a rule no longer detects a planted
          |literal colour, or flags a clean input.
          |${selfTest.map("  - " + _).mkString("\n")}""".stripMargin
    )
  val found = NoLiteralColourLint.scanTree(buildRoot)
  if (found.nonEmpty)
    sys.error(
      s"""|Literal colour outside the token source.
          |
          |${found.map("  - " + _.render).mkString("\n")}
          |
          |Use a token: a JavaFX looked-up colour (-es-ink) in CSS, or
          |eyes4s.studio.app.tokens.Tokens in Scala. Add a new colour to Tokens.scala
          |and run `sbt studioTokens` (DESIGN_SPEC section 4).""".stripMargin
    )
  log.info(
    "studio colours OK (lint self-test passed; no literal colour outside the token source)"
  )
}

// Type scale (S1.2): only the five sizes of eyes4s.studio.app.tokens.TypeSize
// in studio CSS, FXML and inline styles. Runs in studioStyleCheck.
lazy val checkStudioTypeScale =
  taskKey[Unit]("Fail on a font size in studio sources outside the five-size type scale.")

ThisBuild / checkStudioTypeScale := {
  val log      = streams.value.log
  val selfTest = TypeScaleLint.selfTest
  if (selfTest.nonEmpty)
    sys.error(
      s"""|TypeScaleLint self-test failed: a rule no longer detects a planted
          |font size, or flags a clean input.
          |${selfTest.map("  - " + _).mkString("\n")}""".stripMargin
    )
  val found = TypeScaleLint.scanTree((ThisBuild / baseDirectory).value)
  if (found.nonEmpty)
    sys.error(
      s"""|Font size outside the type scale, or a font weight.
          |
          |${found.map("  - " + _.render).mkString("\n")}
          |
          |Use a type class (t11, t12, t13, t16, t28 in studio-type.css) or
          |eyes4s.studio.app.tokens.TypeSize (DESIGN_SPEC section 7).""".stripMargin
    )
  log.info(
    "studio type scale OK (lint self-test passed; only the five sizes in studio sources)"
  )
}

lazy val studioTokenSettings = Seq(
  // TokenFilesSuite compares the checked-in files under the build root.
  Test / resourceGenerators += Def.task {
    val out =
      (Test / resourceManaged).value / "eyes4s" / "studio" / "desktop" / "build-root.txt"
    IO.write(out, (ThisBuild / baseDirectory).value.getAbsolutePath)
    Seq(out)
  }.taskValue
)

addCommandAlias(
  "studioTokens",
  "studioDesktop/runMain eyes4s.studio.desktop.tokens.TokenFiles --write"
)
addCommandAlias(
  "studioTokensCheck",
  "studioDesktop/runMain eyes4s.studio.desktop.tokens.TokenFiles --check"
)

// ---------------------------------------------------------------------------
// Aliases
// ---------------------------------------------------------------------------

// Public reader documentation only; docs/ also contains internal plans and audits.
// Local/CI generation does not enable site deployment.
lazy val docs = project
  .in(file("site"))
  .enablePlugins(TypelevelSitePlugin)
  .dependsOn(io.jvm)
  .settings(
    name           := "eyes4s-guide",
    publish / skip := true,
    mdocIn         := file("site-docs"),
    Compile / unmanagedResourceDirectories += file("site-docs/data").getAbsoluteFile,
    tlSitePublishBranch := None
  )

lazy val allModules = Seq(
  "kernel",
  "core",
  "detect",
  "surface",
  "aoi",
  "compare",
  "design",
  "plan",
  "results",
  "codec",
  "laws",
  "fs2Module",
  "io"
)
lazy val allPlatforms = Seq("JVM", "JS")

addCommandAlias(
  "compileAll",
  allModules.flatMap(m => allPlatforms.map(p => s"$m$p/compile")).mkString(";", ";", "")
)

addCommandAlias(
  "testAll",
  allModules.flatMap(m => allPlatforms.map(p => s"$m$p/test")).mkString(";", ";", "")
)

// checkModuleBoundaries is per-module (it inspects each module's own resolved
// graph); checkKernelPurity, checkStudioBoundaries and checkStudioColours are
// build-level and resolve nothing. `checkLibraryBoundaries` needs no studio pin and
// runs in checks.yml; `studioBoundaries` runs in studio.yml; `checkBoundaries` runs
// all of them.
lazy val libraryBoundaryChecks =
  Seq("checkKernelPurity") ++
    allModules
      .filterNot(m => m == "fs2Module" || m == "io")
      .flatMap(m => allPlatforms.map(p => s"$m$p/checkModuleBoundaries")) ++
    Seq("checkStudioBoundaries", "checkStudioColours")

addCommandAlias("checkLibraryBoundaries", libraryBoundaryChecks.mkString(";", ";", ""))

addCommandAlias(
  "checkBoundaries",
  (libraryBoundaryChecks ++ studioBoundaryChecks).mkString(";", ";", "")
)

lazy val apiAuditInputs =
  taskKey[Unit]("Export resolved compiler classpaths for the public API audit")
apiAuditInputs := {
  val output = file("target/api-audit")
  IO.createDirectory(output)
  val jvm = (LocalProject(
    "ioJVM"
  ) / Compile / fullClasspath).value.files ++ (laws.jvm / Compile / fullClasspath).value.files
  val js = (LocalProject(
    "ioJS"
  ) / Compile / fullClasspath).value.files ++ (laws.js / Compile / fullClasspath).value.files
  IO.writeLines(output / "classpath-jvm.txt", jvm.distinct.map(_.getAbsolutePath))
  IO.writeLines(output / "classpath-js.txt", js.distinct.map(_.getAbsolutePath))
}
