/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.detect

import eyes4s.core.*
import eyes4s.kernel.*
import eyes4s.kernel.Unit2D.Deg

/** Golden fixture generated by the University of Potsdam Python translation
  * of the Engbert Microsaccade Toolbox at commit
  * `a3eba6e9f1464c953c81fbd87944ba7678c2cf64`.
  *
  * The machine-readable fixture and its pinned generator live under
  * `tools/engbert-kernels/`. This suite embeds the values so the same oracle is
  * checked on JVM and JavaScript without a test-time Python or network
  * dependency.
  */
class EngbertKlieglConformanceSuite extends munit.FunSuite:

  private val clock = ClockId("engbert-reference")
  private val xs    = Vector(0.0, 0.0, 0.0, 1.0, 3.0, 6.0, 8.0, 9.0, 9.0)
  private val input = xs.zipWithIndex.map { case (x, index) =>
    Sample(Instant.millis(index.toLong), Gaze.Tracked(Pt[Deg](x, 0.0), None))
  }
  private val reference = Vector(
    666.6666666666666, 1500.0, 2166.6666666666665, 2166.6666666666665, 1500.0
  )

  test("regular five-point velocities agree with the pinned reference oracle") {
    val obtained = Kinematics.velocities(input).toOption.get

    assertEquals(obtained.map(_._1), (2L to 6L).map(Instant.millis).toVector)
    assertEquals(obtained.length, reference.length)
    obtained.map(_._2).zip(reference).foreach { case (velocity, expectedX) =>
      assertEqualsDouble(velocity.dx, expectedX, 1e-12)
      assertEqualsDouble(velocity.dy, 0.0, 1e-12)
    }
  }

  test("the detected event retains the reference peak velocity") {
    val thresholds = EkThresholds.of(100.0, 1.0).toOption.get
    val minSamples = EkMinimumSamples.of(3).toOption.get
    val events     = Detectors
      .engbertKliegl(thresholds, minSamples, clock)
      .runAll(input)
      .map(_.toOption.get)
    val saccades = events.collect { case event: Event.Saccade[Deg] => event }

    assertEquals(saccades.length, 1)
    assertEqualsDouble(saccades.head.span.onset.toMillis, 2.0, 1e-12)
    assertEqualsDouble(saccades.head.span.offset.toMillis, 7.0, 1e-12)
    assertEqualsDouble(
      saccades.head.peakVelocity.map(_.value).get,
      2166.6666666666665,
      1e-12
    )
  }

  test("a full candidate agrees with the pinned toolbox when supplied its radius") {
    val positions = Vector(
      Pt[Deg](0.0, 0.02),
      Pt[Deg](0.01, -0.02),
      Pt[Deg](-0.01, 0.01),
      Pt[Deg](0.02, 0.0),
      Pt[Deg](-0.02, -0.01),
      Pt[Deg](0.0, 0.01),
      Pt[Deg](0.01, -0.02),
      Pt[Deg](0.5, 0.1),
      Pt[Deg](1.5, 0.3),
      Pt[Deg](3.0, 0.6),
      Pt[Deg](4.0, 0.8),
      Pt[Deg](4.02, 0.79),
      Pt[Deg](3.99, 0.81),
      Pt[Deg](4.01, 0.8),
      Pt[Deg](4.0, 0.79)
    )
    val samples = positions.zipWithIndex.map { case (position, index) =>
      Sample(Instant.millis(index.toLong), Gaze.Tracked(position, None))
    }
    val toolboxRadius = EkThresholds
      .of(49.99999999999947, 58.33333333333337)
      .toOption
      .get
    val detector = Detectors.engbertKliegl(
      toolboxRadius,
      EkMinimumSamples.of(3).toOption.get,
      clock
    )
    val saccades = detector.runAll(samples).map(_.toOption.get).collect {
      case event: Event.Saccade[Deg] => event
    }

    assertEquals(saccades.length, 1)
    val event = saccades.head
    assertEqualsDouble(event.span.onset.toMillis, 5.0, 1e-12)
    assertEqualsDouble(event.span.offset.toMillis, 12.0, 1e-12)
    assertEquals(event.from, positions(5))
    assertEquals(event.to, positions(11))
    assertEqualsDouble(
      event.peakVelocity.map(_.value).get,
      1103.8128363892938,
      1e-9
    )
  }

  test("toolbox boundary and threshold differences are explicit card deviations") {
    val card = AlgorithmCards.engbertKliegl

    assert(
      card.assumptions.contains(DetectorAssumption.InvalidObservationsBreakCandidates)
    )
    assert(card.deviations.contains(DetectorDeviation.PublicationMedianSquareThreshold))
    assert(card.deviations.contains(DetectorDeviation.ToolboxBoundaryVelocitiesOmitted))
    assert(card.deviations.contains(DetectorDeviation.InclusiveCandidatePeakVelocity))
    assertEqualsDouble(EkThresholds.medianSquareSpread(Vector(0.0, 1.0, 2.0)), 0.0, 0.0)
    assertEqualsDouble(EkThresholds.medianSquareSpread(Vector(0.0, 2.0)), 1.0, 0.0)
  }

end EngbertKlieglConformanceSuite
