/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.design

// Generated by tools/r-parity/generate_sampling.py.
// format: off
object FiniteControlReference:
  final case class Source(key: String,matched: String,stratum: String,values: Vector[Double])
  final case class Result(cap: Int,key: String,count: Option[Int],mean: Option[Double],selected: Vector[Int])
  val sources: Vector[Source] = Vector(Source("a1","a","q1",Vector(1.0,0.0)),Source("a2","a","q1",Vector(1.0,0.0)),Source("b1","b","q1",Vector(0.0,1.0)),Source("c1","c","q2",Vector(1.0,1.0)),Source("d1","d","q2",Vector(1.0,0.0)),Source("c2","c","q2",Vector(1.0,1.0)))
  val results: Vector[Result] = Vector(
    Result(0,"a1",None,None,Vector()),
    Result(0,"a2",None,None,Vector()),
    Result(0,"b1",None,None,Vector()),
    Result(0,"c1",None,None,Vector()),
    Result(0,"d1",None,None,Vector()),
    Result(0,"c2",None,None,Vector()),
    Result(1,"a1",Some(1),Some(0.0),Vector(2)),
    Result(1,"a2",Some(1),Some(0.0),Vector(2)),
    Result(1,"b1",Some(1),Some(0.0),Vector(1)),
    Result(1,"c1",Some(1),Some(0.707106781186547),Vector(4)),
    Result(1,"d1",Some(1),Some(0.707106781186547),Vector(3)),
    Result(1,"c2",Some(1),Some(0.707106781186547),Vector(4)),
    Result(20,"a1",Some(1),Some(0.0),Vector(2)),
    Result(20,"a2",Some(1),Some(0.0),Vector(2)),
    Result(20,"b1",Some(1),Some(0.0),Vector(1)),
    Result(20,"c1",Some(1),Some(0.707106781186547),Vector(4)),
    Result(20,"d1",Some(1),Some(0.707106781186547),Vector(3)),
    Result(20,"c2",Some(1),Some(0.707106781186547),Vector(4))
  )
// format: on
