/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.design

// Generated by tools/r-parity/generate_repetition.py. Do not hand-edit.
// format: off
object RepetitionReference:
  final case class Row(id: String, weights: Vector[Double], target: Double, control: Double, referenceSame: Double, referenceOther: Double, targets: Vector[String], controls: Vector[String])
  val rows = Vector(
    Row("s1/a/encode", Vector(1.0, 2.0, 2.0, 4.0), 1.0, 0.72, 0.76, 0.8, Vector("s1/a/recall"), Vector("s1/b/recall", "s1/c/recall")),
    Row("s1/b/encode", Vector(4.0, 2.0, 2.0, 1.0), 0.8, 0.82, 0.784, 0.82, Vector("s1/b/recall"), Vector("s1/a/recall", "s1/c/recall")),
    Row("s1/c/encode", Vector(2.0, 4.0, 1.0, 2.0), 0.8, 0.9, 0.784, 0.82, Vector("s1/c/recall"), Vector("s1/a/recall", "s1/b/recall")),
    Row("s2/a/encode", Vector(2.0, 1.0, 4.0, 2.0), 0.84, 0.86, 0.76, 0.8, Vector("s2/a/recall"), Vector("s2/b/recall", "s2/c/recall")),
    Row("s2/b/encode", Vector(1.0, 4.0, 2.0, 2.0), 1.0, 0.68, 0.776, 0.813333333333333, Vector("s2/b/recall"), Vector("s2/a/recall", "s2/c/recall")),
    Row("s2/c/encode", Vector(4.0, 1.0, 2.0, 2.0), 0.84, 0.82, 0.776, 0.813333333333333, Vector("s2/c/recall"), Vector("s2/a/recall", "s2/b/recall")),
    Row("s1/a/recall", Vector(1.0, 2.0, 2.0, 4.0), 1.0, 0.72, 0.76, 0.8, Vector("s1/a/encode"), Vector("s1/b/encode", "s1/c/encode")),
    Row("s1/b/recall", Vector(2.0, 4.0, 1.0, 2.0), 0.8, 0.9, 0.784, 0.82, Vector("s1/b/encode"), Vector("s1/a/encode", "s1/c/encode")),
    Row("s1/c/recall", Vector(4.0, 2.0, 2.0, 1.0), 0.8, 0.82, 0.784, 0.82, Vector("s1/c/encode"), Vector("s1/a/encode", "s1/b/encode")),
    Row("s2/a/recall", Vector(4.0, 1.0, 2.0, 2.0), 0.84, 0.82, 0.776, 0.813333333333333, Vector("s2/a/encode"), Vector("s2/b/encode", "s2/c/encode")),
    Row("s2/b/recall", Vector(1.0, 4.0, 2.0, 2.0), 1.0, 0.68, 0.776, 0.813333333333333, Vector("s2/b/encode"), Vector("s2/a/encode", "s2/c/encode")),
    Row("s2/c/recall", Vector(2.0, 1.0, 4.0, 2.0), 0.84, 0.86, 0.76, 0.8, Vector("s2/c/encode"), Vector("s2/a/encode", "s2/b/encode")),
  )
// format: on
