/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.design

// Generated by tools/r-parity/generate_repetition_methods.py.
// format: off
object RepetitionMethodsReference:
  final case class Row(key: String,participant: String,stimulus: String,occasion: String,values: Vector[Double],scale1: Vector[Double])
  val rows: Vector[Row] = Vector(
    Row("p1/a/0","p1","a","0",Vector(0.1,0.2,0.3,0.4),Vector(0.25,0.25,0.25,0.25)),
    Row("p1/b/0","p1","b","0",Vector(0.4,0.3,0.2,0.1),Vector(0.1,0.4,0.1,0.4)),
    Row("p1/a/1","p1","a","1",Vector(0.1,0.4,0.1,0.4),Vector(0.2,0.2,0.5,0.1)),
    Row("p1/b/1","p1","b","1",Vector(0.2,0.2,0.5,0.1),Vector(0.3,0.1,0.2,0.4)),
    Row("p1/a/2","p1","a","2",Vector(0.3,0.1,0.2,0.4),Vector(0.25,0.15,0.4,0.2)),
    Row("p1/b/2","p1","b","2",Vector(0.25,0.15,0.4,0.2),Vector(0.1,0.1,0.2,0.6)),
    Row("p2/a/0","p2","a","0",Vector(0.1,0.2,0.3,0.4),Vector(0.1,0.4,0.1,0.4))
  )
  final case class Mean(key: String,same: Option[Double],other: Option[Double],nestedSame: Option[Double],nestedOther: Option[Double],pooledSame: Option[Double])
  val methods: Vector[(String,Vector[Mean])] = Vector(
    ("pearson",Vector(Mean("p1/a/0",Some(0.0),Some(0.2416841141083493),Some(0.0),Some(0.2416841141083493),Some(0.0)),Mean("p1/b/0",Some(-1.0),Some(-0.2416841141083493),Some(-0.5),Some(-0.24376444984558387),Some(-0.3333333333333333)),Mean("p1/a/1",Some(-0.6666666666666666),Some(-0.07091402604746307),Some(-0.5569401310833122),Some(-0.07540451034231643),Some(-0.5569401310833122)),Mean("p1/b/1",Some(-0.6666666666666666),Some(0.08873144217495803),Some(-0.5569401310833122),Some(0.1202913813240087),Some(-0.5569401310833122)),Mean("p1/a/2",Some(0.0),Some(-0.009442719099991581),Some(-0.06482037235521643),Some(-0.03599102405997563),Some(-0.06482037235521643)),Mean("p1/b/2",Some(0.0),Some(0.04172198831418284),Some(-0.06482037235521643),Some(0.16533058632877604),Some(-0.06482037235521643)),Mean("p2/a/0",Some(0.0),Some(0.2416841141083493),Some(0.5),Some(-0.0020803357372345885),Some(0.3333333333333333)))),
    ("spearman",Vector(Mean("p1/a/0",Some(0.0),Some(0.13274645737078),Some(0.0),Some(0.13274645737078),Some(0.0)),Mean("p1/b/0",Some(-1.0),Some(-0.13274645737078),Some(-0.5),Some(-0.23710219265925844),Some(-0.3333333333333333)),Mean("p1/a/1",Some(-0.7071067811865476),Some(-0.08944271909999159),Some(-0.6697811566101117),Some(-0.11150913636727526),Some(-0.6697811566101117)),Mean("p1/b/1",Some(-0.7071067811865476),Some(-0.06324555320336758),Some(-0.6697811566101117),Some(0.02),Some(-0.6697811566101117)),Mean("p1/a/2",Some(0.2),Some(-0.04649110640673517),Some(0.205409255338946),Some(-0.07888543819998317),Some(0.205409255338946)),Mean("p1/b/2",Some(0.2),Some(-0.052394331793248),Some(0.205409255338946),Some(0.05085550605251343),Some(0.205409255338946)),Mean("p2/a/0",Some(0.0),Some(0.13274645737078),Some(0.5),Some(-0.10435573528847844),Some(0.3333333333333333)))),
    ("fisherz",Vector(Mean("p1/a/0",Some(0.0),Some(0.2562394253728775),Some(0.0),Some(0.2562394253728775),Some(0.0)),Mean("p1/b/0",Some(-18.36840028483855),Some(-0.2562394253728775),Some(-9.184200142419275),Some(-0.30045859437759825),Some(-6.122800094946183)),Mean("p1/a/1",Some(-0.8047189562170501),Some(-0.12447500330010838),Some(-0.6429653906383268),Some(-0.07531610720972358),Some(-0.6429653906383268)),Mean("p1/b/1",Some(-0.8047189562170501),Some(0.18898366529611837),Some(-0.6429653906383268),Some(0.19393758202983583),Some(-0.6429653906383268)),Mean("p1/a/2",Some(0.0),Some(-0.011512578973200327),Some(-0.0651872181486213),Some(-0.04149574962524953),Some(-0.0651872181486213)),Mean("p1/b/2",Some(0.0),Some(0.08852805124367097),Some(-0.0651872181486213),Some(0.21876940650078733),Some(-0.0651872181486213)),Mean("p2/a/0",Some(0.0),Some(0.2562394253728775),Some(9.184200142419275),Some(-0.04421916900472071),Some(6.122800094946183)))),
    ("cosine",Vector(Mean("p1/a/0",Some(0.8333333333333334),Some(0.8578939926620068),Some(0.8454131295229388),Some(0.8637552983660003),Some(0.8454131295229388)),Mean("p1/b/0",Some(0.6666666666666667),Some(0.7690440178965776),Some(0.7977065647614694),Some(0.7370852296814401),Some(0.7977065647614694)),Mean("p1/a/1",Some(0.5588235294117647),Some(0.7767219958893673),Some(0.6238351248027145),Some(0.7351744937312726),Some(0.6238351248027145)),Mean("p1/b/1",Some(0.5588235294117647),Some(0.8001853322135656),Some(0.6238351248027145),Some(0.8235838149737358),Some(0.6238351248027145)),Mean("p1/a/2",Some(0.8549819600709617),Some(0.8076587501433536),Some(0.7743349678451288),Some(0.811071013239091),Some(0.7743349678451288)),Mean("p1/b/2",Some(0.8549819600709617),Some(0.8408678498154949),Some(0.7743349678451288),Some(0.8047303979100701),Some(0.7743349678451288)),Mean("p2/a/0",Some(0.8333333333333334),Some(0.8578939926620068),Some(0.8810398980948028),Some(0.7815102170641548),Some(0.8810398980948028)))),
    ("l1",Vector(Mean("p1/a/0",Some(0.8),Some(0.7625),Some(0.75),Some(0.7625),Some(0.75)),Mean("p1/b/0",Some(0.6),Some(0.6749999999999999),Some(0.725),Some(0.64375),Some(0.725)),Mean("p1/a/1",Some(0.5),Some(0.6900000000000001),Some(0.55),Some(0.655),Some(0.55)),Mean("p1/b/1",Some(0.5),Some(0.71),Some(0.55),Some(0.73),Some(0.55)),Mean("p1/a/2",Some(0.75),Some(0.72),Some(0.675),Some(0.7150000000000001),Some(0.675)),Mean("p1/b/2",Some(0.75),Some(0.72),Some(0.675),Some(0.695),Some(0.675)),Mean("p2/a/0",Some(0.8),Some(0.7625),Some(0.825),Some(0.6875),Some(0.825)))),
    ("jaccard",Vector(Mean("p1/a/0",Some(0.75),Some(0.7524281274281275),Some(0.7426470588235294),Some(0.7563463797983921),Some(0.7426470588235294)),Mean("p1/b/0",Some(0.5),Some(0.626761255437726),Some(0.6838235294117647),Some(0.5891012364751861),Some(0.6838235294117647)),Mean("p1/a/1",Some(0.3877551020408163),Some(0.6416971916971917),Some(0.4557823129251701),Some(0.5999510060434431),Some(0.4557823129251701)),Mean("p1/b/1",Some(0.3877551020408163),Some(0.673992673992674),Some(0.4557823129251701),Some(0.7031616642064404),Some(0.4557823129251701)),Mean("p1/a/2",Some(0.746268656716418),Some(0.6845640845640846),Some(0.6311988444872412),Some(0.6945549461260381),Some(0.6311988444872412)),Mean("p1/b/2",Some(0.746268656716418),Some(0.7354429883841649),Some(0.6311988444872412),Some(0.6807373672079554),Some(0.6311988444872412)),Mean("p2/a/0",Some(0.75),Some(0.7524281274281275),Some(0.8088235294117647),Some(0.6519346724703867),Some(0.8088235294117647)))),
    ("dcov",Vector(Mean("p1/a/0",Some(1.0),Some(0.6353845503498896),Some(1.0),Some(0.6353845503498896),Some(1.0)),Mean("p1/b/0",Some(1.0),Some(0.6353845503498896),Some(1.0),Some(0.6326129050416568),Some(1.0)),Mean("p1/a/1",Some(0.6389431042462724),Some(0.5846116264638864),Some(0.6559647963561513),Some(0.6354672560610987),Some(0.6559647963561513)),Mean("p1/b/1",Some(0.6389431042462724),Some(0.726488947569233),Some(0.6559647963561513),Some(0.6838922139584293),Some(0.6559647963561513)),Mean("p1/a/2",Some(0.6798898171917449),Some(0.6802050066859971),Some(0.6085873915517579),Some(0.738820618216457),Some(0.6085873915517579)),Mean("p1/b/2",Some(0.6798898171917449),Some(0.7162662366101091),Some(0.6085873915517579),Some(0.6750922422607886),Some(0.6085873915517579)),Mean("p2/a/0",Some(1.0),Some(0.6353845503498896),Some(1.0),Some(0.6326129050416568),Some(1.0))))
  )
// format: on
