/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.design

// Generated by tools/r-parity/generate_template_cv.py.
// format: off
object TemplateCvReference:
  final case class Row(key: String, group: String, matched: String, values: Vector[Double], fold: Int, expected: Double)
  val rows: Vector[Row] = Vector(
    Row("s1","p1","a",Vector(1.0,0.0),1,0.894427190999916),
    Row("s2","p2","b",Vector(0.0,1.0),2,0.894427190999916),
    Row("s3","p3","c",Vector(1.0,1.0),1,1),
    Row("s4","p4","d",Vector(2.0,1.0),2,0.894427190999916),
    Row("s5","p2","c",Vector(1.0,2.0),2,0.948683298050514)
  )
  val references: Vector[(String,Vector[Double])] = Vector(("a",Vector(2.0,1.0)),("b",Vector(1.0,2.0)),("c",Vector(1.0,1.0)),("d",Vector(1.0,0.0)))
  val folds: Vector[(Int,Int,Int,Int)] = Vector((1,2,2,1),(2,1,3,1))
// format: on
