#!/usr/bin/env python3
"""Validate the finite eyesim baseline inventory and its pinned evidence.

The inventory is baseline.json merged with the per-ticket fragments in manifest.d/. The checker
validates its structure and fixture digests; that every generator reads the eyesim pin from
baseline.json and runs R only through parity.py, and that fixtures and generated files record
that pin; that recorded R runtimes match r-lock.json; that the shared falsification input stays
frozen and each per-ticket input belongs to its ticket; and, on request, the pinned Git object,
the live Mote gap tasks and the fixture regeneration. Out-of-baseline records are validated and
reported separately: they are neither gaps nor progress towards closing the baseline.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import re
import shlex
import subprocess
import sys

sys.dont_write_bytecode = True
import parity  # noqa: E402

ROOT = parity.ROOT
DEFAULT_MANIFEST = parity.MANIFEST
EXPECTED_ROWS = [
    "fixation-data",
    "spatial-transforms",
    "scanpaths",
    "density",
    "fixation-sampling",
    "entropy-map-arithmetic",
    "map-fixation-comparison",
    "matched-controls",
    "repetition",
    "multiscale",
    "temporal",
    "template-models",
    "reuse-export",
]
EXPECTED_STATUSES = [
    "verified-equivalent",
    "verified-intentional-divergence",
    "implementation-gap",
]
WORKFLOW_ISSUE = "bd-01M214CX2CTADNR6Q9D032Y1FB"
# The shared falsification input is frozen: the transform, entropy, admission and template
# generators hash the whole file, so any edit would force all of them to regenerate. New
# inputs go in fixtures/cases/<ticket>.json, registered by manifest.d/<ticket>.json.
FROZEN_INPUTS = {
    "tools/r-parity/fixtures/baseline-cases.json": "0b2e5036ee1c8aee63e27b3a99d08f8e4bffa3402e9ff67e4cba5bd68aef0300",
}
CASES_DIR = "tools/r-parity/fixtures/cases"
FRAGMENT_KEYS = {"schema", "ticket", "fixtures", "regeneration", "cases"}
GENERATED_MARKER = "Generated by tools/r-parity/"
SHA = re.compile(r"(?<![0-9a-f])[0-9a-f]{40}(?![0-9a-f])")
SCALA_REVISION = re.compile(r'eyesimRevision\s*=\s*"([^"]*)"')
# A generator runs R and installs eyesim only through parity.r_session.
DIRECT_R = re.compile(
    r"[\"']\s*(Rscript|R CMD|git archive)\b|[\"'](Rscript|INSTALL|archive)[\"']"
)
HARNESS = {"parity.py", "check_baseline.py", "provision.py"}
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
CASE_FIELDS = ["id", "row", "estimand", "independent_case"]
CASE_LISTS = [
    "eyesim_entry_points",
    "methods",
    "conventions",
    "backend_dependencies",
    "eyes4s_public_api",
    "fixture_inputs",
]


@dataclass
class Inventory:
    """baseline.json merged with manifest.d/*.json, remembering where each fixture is declared."""

    path: Path
    manifest: dict
    origins: dict[str, Path] = field(default_factory=dict)
    fragments: dict[str, Path] = field(default_factory=dict)


def run(args: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(args, cwd=cwd or ROOT, check=True, text=True, capture_output=True)
    return result.stdout


def require(condition: bool, message: str, failures: list[str]) -> None:
    if not condition:
        failures.append(message)


def nonempty_strings(value: object) -> bool:
    return (
        isinstance(value, list)
        and bool(value)
        and all(isinstance(item, str) and bool(item.strip()) for item in value)
    )


def strings(value: object) -> list[str]:
    """The string items of a list, or nothing: iteration never crashes on a malformed field."""
    return (
        [item for item in value if isinstance(item, str)]
        if isinstance(value, list)
        else []
    )


def covers(required: str, actual: str) -> bool:
    return (
        required == actual
        or actual.startswith(required + ".")
        or required.startswith(actual + ".")
    )


def rel(path: Path) -> str:
    resolved = path.resolve()
    return (
        resolved.relative_to(ROOT).as_posix()
        if resolved.is_relative_to(ROOT)
        else str(resolved)
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_json(path: Path) -> object | None:
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def command_tokens(command: str, owner: str, failures: list[str]) -> list[str]:
    try:
        return shlex.split(command.replace("{eyesim}", "/tmp/eyesim"))
    except ValueError as error:
        failures.append(f"{owner} command cannot be parsed: {error}")
        return []


def load_inventory(path: Path, failures: list[str]) -> Inventory:
    manifest = json.loads(path.read_text())
    inventory = Inventory(path, manifest)
    if isinstance(manifest.get("fixtures"), dict):
        inventory.origins = {fixture: path for fixture in manifest["fixtures"]}
    fragments = path.parent / "manifest.d"
    for fragment_path in sorted(fragments.glob("*.json")) if fragments.is_dir() else []:
        name = rel(fragment_path)
        fragment = read_json(fragment_path)
        if not isinstance(fragment, dict):
            failures.append(f"{name} must be a JSON object")
            continue
        ticket = fragment_path.stem
        require(fragment.get("schema") == 1, f"{name} schema must be 1", failures)
        require(
            fragment.get("ticket") == ticket,
            f"{name} must declare ticket {ticket}, its file name",
            failures,
        )
        unknown = sorted(set(fragment) - FRAGMENT_KEYS)
        require(not unknown, f"{name} has unknown keys {unknown}", failures)
        inventory.fragments[ticket] = fragment_path
        for key in ("fixtures", "regeneration"):
            entries = fragment.get(key, {})
            if not isinstance(entries, dict) or not isinstance(manifest.get(key), dict):
                require(
                    isinstance(entries, dict),
                    f"{name} {key} must be an object",
                    failures,
                )
                continue
            for entry_id, entry in entries.items():
                if entry_id in manifest[key]:
                    failures.append(f"{name} redeclares {key} id {entry_id}")
                    continue
                manifest[key][entry_id] = entry
                if key == "fixtures":
                    inventory.origins[entry_id] = fragment_path
        cases = fragment.get("cases", [])
        if isinstance(cases, list) and isinstance(manifest.get("cases"), list):
            manifest["cases"].extend(cases)
        else:
            require(isinstance(cases, list), f"{name} cases must be a list", failures)
    return inventory


def regenerated_fixtures(manifest: dict) -> set[str]:
    regenerators = manifest.get("regeneration")
    if not isinstance(regenerators, dict):
        return set()
    return {
        output
        for regen in regenerators.values()
        if isinstance(regen, dict)
        for output in strings(regen.get("outputs"))
    }


def verify_record(
    record: dict,
    record_id: str,
    kind: str,
    row_by_id: dict,
    fixtures: dict,
    failures: list[str],
) -> None:
    """The fields shared by counted cases and out-of-baseline records."""
    for name in CASE_FIELDS:
        require(bool(record.get(name)), f"{kind} {record_id} needs {name}", failures)
    for name in CASE_LISTS:
        require(
            nonempty_strings(record.get(name)),
            f"{kind} {record_id} needs {name}",
            failures,
        )
    row_id = record.get("row")
    require(
        isinstance(row_id, str) and row_id in row_by_id,
        f"{kind} {record_id} names unknown row {row_id}",
        failures,
    )
    for fixture_id in strings(record.get("fixture_inputs")):
        require(
            fixture_id in fixtures,
            f"{kind} {record_id} names unknown fixture {fixture_id}",
            failures,
        )
    evidence = record.get("evidence")
    require(
        isinstance(evidence, list),
        f"{kind} {record_id} evidence must be a list",
        failures,
    )
    if isinstance(evidence, list):
        for path_text in evidence:
            require(
                isinstance(path_text, str) and (ROOT / path_text).is_file(),
                f"{kind} {record_id} evidence path is missing: {path_text}",
                failures,
            )


def record_id(record: dict, fallback: str, failures: list[str]) -> str:
    value = record.get("id")
    if isinstance(value, str) and value:
        return value
    failures.append(f"{fallback} needs a string id")
    return fallback


def verify_manifest(
    inventory: Inventory, failures: list[str], regenerating: bool = False
) -> None:
    """Every structural, digest, pin and lock check that needs neither eyesim nor Mote.

    While fixtures are being regenerated (`regenerating`), digests of regenerated outputs and
    the pin and runtime records they carry are expected to be stale and are checked afterwards.
    """
    manifest = inventory.manifest
    require(manifest.get("schema") == 1, "manifest schema must be 1", failures)
    require(
        manifest.get("status_values") == EXPECTED_STATUSES,
        "status_values must be the three frozen classifications in order",
        failures,
    )

    eyesim = manifest.get("eyesim", {})
    revision = eyesim.get("revision", "")
    require(
        isinstance(revision, str)
        and re.fullmatch(r"[0-9a-f]{40}", revision) is not None,
        "eyesim.revision must be a full lowercase Git SHA",
        failures,
    )
    require(bool(eyesim.get("version")), "eyesim.version is required", failures)
    require(bool(eyesim.get("license")), "eyesim.license is required", failures)
    require(
        nonempty_strings(eyesim.get("inventory_sources")),
        "eyesim.inventory_sources must name source files",
        failures,
    )

    rows = manifest.get("rows")
    require(isinstance(rows, list), "rows must be a list", failures)
    if not isinstance(rows, list):
        return
    row_ids = [row.get("id") for row in rows if isinstance(row, dict)]
    require(
        row_ids == EXPECTED_ROWS,
        "rows must contain the frozen 13-row baseline",
        failures,
    )
    row_by_id = {row.get("id"): row for row in rows if isinstance(row, dict)}
    for row_id in EXPECTED_ROWS:
        row = row_by_id.get(row_id, {})
        require(bool(row.get("label")), f"row {row_id} needs a label", failures)
        require(
            nonempty_strings(row.get("required_entry_points")),
            f"row {row_id} needs required_entry_points",
            failures,
        )

    fixtures = manifest.get("fixtures")
    require(
        isinstance(fixtures, dict) and bool(fixtures),
        "fixtures must be non-empty",
        failures,
    )
    if not isinstance(fixtures, dict):
        fixtures = {}
    regenerated = regenerated_fixtures(manifest)
    for fixture_id, fixture in fixtures.items():
        if not isinstance(fixture, dict):
            failures.append(f"fixture {fixture_id} must be an object")
            continue
        path = ROOT / str(fixture.get("path", ""))
        require(
            path.is_file(),
            f"fixture {fixture_id} path does not exist: {path}",
            failures,
        )
        digest = fixture.get("sha256", "")
        require(
            isinstance(digest, str)
            and re.fullmatch(r"[0-9a-f]{64}", digest) is not None,
            f"fixture {fixture_id} needs a full SHA-256 digest",
            failures,
        )
        if path.is_file() and isinstance(digest, str):
            if not (regenerating and fixture_id in regenerated):
                actual = sha256(path)
                require(
                    actual == digest,
                    f"fixture {fixture_id} digest drift: {actual}",
                    failures,
                )
            if path.suffix == ".json":
                require(
                    read_json(path) is not None,
                    f"fixture {fixture_id} is not valid JSON",
                    failures,
                )
        require(
            bool(fixture.get("license")),
            f"fixture {fixture_id} needs a license",
            failures,
        )
        require(
            bool(fixture.get("role")), f"fixture {fixture_id} needs a role", failures
        )
    for frozen, digest in FROZEN_INPUTS.items():
        path = ROOT / frozen
        require(
            path.is_file() and sha256(path) == digest,
            f"{frozen} is frozen; put new inputs in {CASES_DIR}/<ticket>.json",
            failures,
        )

    regenerators = manifest.get("regeneration")
    require(
        isinstance(regenerators, dict) and bool(regenerators),
        "regeneration must be non-empty",
        failures,
    )
    if not isinstance(regenerators, dict):
        regenerators = {}
    claimed: dict[str, str] = {}
    for regen_id, regen in regenerators.items():
        if not isinstance(regen, dict):
            failures.append(f"regenerator {regen_id} must be an object")
            continue
        command = regen.get("command", "")
        require(
            isinstance(command, str) and bool(command),
            f"regenerator {regen_id} needs a command",
            failures,
        )
        require(
            isinstance(regen.get("requires_eyesim"), bool),
            f"regenerator {regen_id} needs requires_eyesim",
            failures,
        )
        outputs = regen.get("outputs")
        require(
            nonempty_strings(outputs), f"regenerator {regen_id} needs outputs", failures
        )
        for output in strings(outputs):
            require(
                output in fixtures,
                f"regenerator {regen_id} names unknown fixture {output}",
                failures,
            )
            require(
                output not in claimed,
                f"fixture {output} is regenerated by both {claimed.get(output)} and {regen_id}",
                failures,
            )
            claimed.setdefault(output, regen_id)
        if isinstance(command, str) and command:
            tokens = command_tokens(command, f"regenerator {regen_id}", failures)
            require(
                not tokens or "--check" in tokens,
                f"regenerator {regen_id} command must be a --check command",
                failures,
            )
            for token in tokens:
                if token.startswith("tools/"):
                    require(
                        (ROOT / token).is_file(),
                        f"regenerator {regen_id} script is missing: {token}",
                        failures,
                    )
        if regen.get("requires_eyesim") is True:
            carriers = []
            for output in strings(outputs):
                fixture = fixtures.get(output)
                if isinstance(fixture, dict) and str(fixture.get("path", "")).endswith(
                    ".json"
                ):
                    document = read_json(ROOT / str(fixture["path"]))
                    if isinstance(document, dict) and "eyesim_revision" in document:
                        carriers.append(output)
            require(
                bool(carriers),
                f"regenerator {regen_id} calls eyesim but no JSON output records eyesim_revision",
                failures,
            )

    cases = manifest.get("cases")
    require(
        isinstance(cases, list) and bool(cases), "cases must be non-empty", failures
    )
    if not isinstance(cases, list):
        return
    record_ids: set[str] = set()
    cases_by_row: dict[str, list[dict]] = {row: [] for row in EXPECTED_ROWS}
    for index, case in enumerate(cases):
        if not isinstance(case, dict):
            failures.append(f"case[{index}] must be an object")
            continue
        case_id = record_id(case, f"case[{index}]", failures)
        require(case_id not in record_ids, f"duplicate case id {case_id}", failures)
        record_ids.add(case_id)
        verify_record(case, case_id, "case", row_by_id, fixtures, failures)
        if case.get("row") in cases_by_row:
            cases_by_row[case["row"]].append(case)
        status = case.get("status")
        require(
            status in EXPECTED_STATUSES,
            f"case {case_id} has invalid status {status}",
            failures,
        )
        evidence = case.get("evidence")
        if status == "implementation-gap":
            require(
                isinstance(case.get("gap_issue"), str) and bool(case.get("gap_issue")),
                f"gap case {case_id} needs one exact gap_issue",
                failures,
            )
            require(
                bool(case.get("planned_evidence")),
                f"gap case {case_id} needs planned_evidence",
                failures,
            )
        else:
            require(
                case.get("gap_issue") is None,
                f"verified case {case_id} cannot name gap_issue",
                failures,
            )
            require(bool(evidence), f"verified case {case_id} needs evidence", failures)
        if status == "verified-intentional-divergence":
            require(
                bool(case.get("divergence")),
                f"divergence case {case_id} needs a reason",
                failures,
            )
        for regen_id in strings(case.get("regeneration_ids")):
            require(
                regen_id in regenerators,
                f"case {case_id} names unknown regenerator {regen_id}",
                failures,
            )

    excluded = manifest.get("out_of_baseline", [])
    require(isinstance(excluded, list), "out_of_baseline must be a list", failures)
    if not isinstance(excluded, list):
        excluded = []
    excluded_by_row: dict[str, list[dict]] = {row: [] for row in EXPECTED_ROWS}
    kind = "out-of-baseline case"
    for index, record in enumerate(excluded):
        if not isinstance(record, dict):
            failures.append(f"out_of_baseline[{index}] must be an object")
            continue
        excluded_id = record_id(record, f"out_of_baseline[{index}]", failures)
        require(
            excluded_id not in record_ids, f"duplicate case id {excluded_id}", failures
        )
        record_ids.add(excluded_id)
        verify_record(record, excluded_id, kind, row_by_id, fixtures, failures)
        if record.get("row") in excluded_by_row:
            excluded_by_row[record["row"]].append(record)
        for name in ("status", "gap_issue"):
            require(
                name not in record,
                f"{kind} {excluded_id} cannot carry {name}; it is not counted",
                failures,
            )
        require(
            bool(record.get("reason")), f"{kind} {excluded_id} needs a reason", failures
        )
        require(
            isinstance(record.get("owner_decision"), str)
            and DATE.fullmatch(record["owner_decision"]) is not None,
            f"{kind} {excluded_id} needs owner_decision as YYYY-MM-DD",
            failures,
        )

    for row_id, row_cases in cases_by_row.items():
        require(bool(row_cases), f"row {row_id} has no classified cases", failures)
        classified = [
            entry
            for record in row_cases + excluded_by_row[row_id]
            for entry in strings(record.get("eyesim_entry_points"))
        ]
        for required in strings(row_by_id.get(row_id, {}).get("required_entry_points")):
            require(
                any(covers(required, entry) for entry in classified),
                f"row {row_id} does not classify required entry point {required}",
                failures,
            )

    verify_case_inputs(inventory, failures)
    verify_pin(inventory, failures, regenerating)
    verify_lock(inventory, failures, regenerating)


def repository_files(*pathspecs: str) -> list[str]:
    """Tracked and untracked, not ignored, files matching `pathspecs`."""
    listed = run(
        [
            "git",
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            *pathspecs,
        ]
    )
    return sorted({name for name in listed.splitlines() if (ROOT / name).is_file()})


def verify_case_inputs(inventory: Inventory, failures: list[str]) -> None:
    """Each per-ticket input lives in fixtures/cases/, registered by that ticket's fragment."""
    fixtures = inventory.manifest.get("fixtures", {})
    registered = {
        str(fixture.get("path")): fixture_id
        for fixture_id, fixture in fixtures.items()
        if isinstance(fixture, dict)
    }
    for path_text, fixture_id in registered.items():
        if not path_text.startswith(CASES_DIR + "/"):
            continue
        parts = Path(path_text).relative_to(CASES_DIR).parts
        if not parts:
            failures.append(f"fixture {fixture_id} must name a file under {CASES_DIR}")
            continue
        owner = parts[0].removesuffix(".json") if len(parts) == 1 else parts[0]
        origin = inventory.origins.get(fixture_id)
        require(
            origin is not None
            and origin.parent.name == "manifest.d"
            and origin.stem == owner,
            f"fixture {fixture_id} ({path_text}) must be registered by manifest.d/{owner}.json",
            failures,
        )
        require(
            len(parts) > 1 or parts[0].endswith(".json"),
            f"fixture {fixture_id}: a single case input must be {CASES_DIR}/<ticket>.json",
            failures,
        )
    for name in repository_files(CASES_DIR):
        require(
            name in registered,
            f"{name} is not registered as a fixture by its ticket's fragment",
            failures,
        )


def generator_scripts(manifest: dict) -> set[Path]:
    """Every script in tools/r-parity and every script a regeneration command names."""
    scripts = {
        path.resolve()
        for pattern in ("*.py", "*.R")
        for path in parity.HERE.glob(pattern)
    }
    regenerators = manifest.get("regeneration")
    for regen in regenerators.values() if isinstance(regenerators, dict) else []:
        if isinstance(regen, dict) and isinstance(regen.get("command"), str):
            for token in command_tokens(regen["command"], "regenerator", []):
                if token.startswith("tools/") and (ROOT / token).is_file():
                    scripts.add((ROOT / token).resolve())
    return scripts


def verify_pin(inventory: Inventory, failures: list[str], regenerating: bool) -> None:
    """The pin is written once, in baseline.json; everything else reads or records that value."""
    manifest = inventory.manifest
    pin = manifest.get("eyesim", {}).get("revision", "")
    if not isinstance(pin, str) or re.fullmatch(r"[0-9a-f]{40}", pin) is None:
        return
    for script in sorted(generator_scripts(manifest)):
        text = script.read_text()
        for found in sorted(set(SHA.findall(text))):
            failures.append(
                f"{rel(script)} names revision {found}; generators read the pin from baseline.json"
            )
        if (
            script.suffix == ".py"
            and script.name not in HARNESS
            and DIRECT_R.search(text)
        ):
            failures.append(
                f"{rel(script)} runs a process itself; generators run R and install eyesim "
                "only through parity.r_session"
            )

    fixtures = manifest.get("fixtures", {})
    fixture_paths = {
        str(fixture.get("path"))
        for fixture in fixtures.values()
        if isinstance(fixture, dict)
    }
    generated = [
        name
        for name in repository_files("*.scala")
        if GENERATED_MARKER in (ROOT / name).read_text()
    ]
    if not regenerating:
        for path_text in sorted(fixture_paths):
            path = ROOT / path_text
            if path.suffix != ".json" or not path.is_file():
                continue
            document = read_json(path)
            if isinstance(document, dict) and "eyesim_revision" in document:
                require(
                    document["eyesim_revision"] == pin,
                    f"{path_text} records eyesim revision {document['eyesim_revision']}, not the pin",
                    failures,
                )
        for name in generated:
            for found in SCALA_REVISION.findall((ROOT / name).read_text()):
                require(
                    found == pin,
                    f"{name} records eyesim revision {found}, not the pin",
                    failures,
                )

    allowed = {rel(inventory.path), *fixture_paths, *generated}
    try:
        hits = run(
            [
                "git",
                "grep",
                "--untracked",
                "-l",
                "-F",
                pin,
                "--",
                ".",
                ":(exclude).mote",
                ":(exclude).claude",
            ]
        ).splitlines()
    except subprocess.CalledProcessError as error:
        hits = [] if error.returncode == 1 else [f"<git grep failed: {error}>"]
    for hit in hits:
        require(
            hit in allowed,
            f"{hit} names the eyesim pin; refer to baseline.json instead so a pin move is one line",
            failures,
        )


def runtime_records(value: object, where: str = ""):
    """Every {"R": ..., "packages": {...}} runtime record inside a fixture document."""
    if isinstance(value, dict):
        if isinstance(value.get("R"), str) and isinstance(value.get("packages"), dict):
            yield where or "<root>", value
        for key, item in value.items():
            yield from runtime_records(item, f"{where}.{key}" if where else key)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from runtime_records(item, f"{where}[{index}]")


def verify_lock(inventory: Inventory, failures: list[str], regenerating: bool) -> None:
    """r-lock.json is well formed, and every runtime a fixture recorded is the locked one."""
    lock = read_json(parity.R_LOCK)
    if not isinstance(lock, dict):
        failures.append(f"{rel(parity.R_LOCK)} is missing or not a JSON object")
        return
    require(lock.get("schema") == 1, "r-lock.json schema must be 1", failures)
    require(
        isinstance(lock.get("R"), str) and bool(lock.get("R")),
        "r-lock.json needs R",
        failures,
    )
    packages = lock.get("packages")
    require(
        isinstance(packages, list) and bool(packages),
        "r-lock.json needs packages",
        failures,
    )
    if not isinstance(packages, list):
        return
    locked: dict[str, str] = {}
    for package in packages:
        ok = isinstance(package, dict) and all(
            isinstance(package.get(key), str) and package.get(key)
            for key in ("name", "version", "source")
        )
        require(
            ok,
            f"r-lock.json package needs name, version and source: {package}",
            failures,
        )
        if ok:
            require(
                package["name"] not in locked,
                f"r-lock.json locks {package['name']} twice",
                failures,
            )
            locked[package["name"]] = package["version"]
    if regenerating:
        return
    eyesim_version = inventory.manifest.get("eyesim", {}).get("version", "")
    for fixture_id, fixture in inventory.manifest.get("fixtures", {}).items():
        path = (
            ROOT / str(fixture.get("path", "")) if isinstance(fixture, dict) else None
        )
        if path is None or path.suffix != ".json" or not path.is_file():
            continue
        for where, record in runtime_records(read_json(path)):
            require(
                record["R"] == lock.get("R"),
                f"fixture {fixture_id} {where} records R {record['R']}, locked {lock.get('R')}",
                failures,
            )
            for name, version in record["packages"].items():
                expected = eyesim_version if name == "eyesim" else locked.get(name)
                require(
                    isinstance(version, str)
                    and isinstance(expected, str)
                    and parity.same_version(version, expected),
                    f"fixture {fixture_id} {where} records {name} {version}, "
                    f"locked {expected or 'nowhere'}",
                    failures,
                )


def verify_eyesim(
    manifest: dict, checkout: Path, failures: list[str], regenerating: bool = False
) -> None:
    revision = manifest["eyesim"]["revision"]
    try:
        run(["git", "cat-file", "-e", f"{revision}^{{commit}}"], checkout)
    except (subprocess.CalledProcessError, FileNotFoundError):
        failures.append(
            f"eyesim checkout does not contain pinned revision {revision}: {checkout}"
        )
        return
    for source in manifest["eyesim"]["inventory_sources"]:
        try:
            run(["git", "show", f"{revision}:{source}"], checkout)
        except subprocess.CalledProcessError:
            failures.append(f"pinned eyesim source is missing: {source}")
    description = run(["git", "show", f"{revision}:DESCRIPTION"], checkout)
    version = parity.dcf_field(description, "Version")
    if not regenerating:
        require(
            version == manifest["eyesim"]["version"],
            "pinned eyesim DESCRIPTION version does not match the manifest",
            failures,
        )
    lock = read_json(parity.R_LOCK)
    require(
        isinstance(lock, dict)
        and lock.get("eyesim_roots") == parity.eyesim_requirements(checkout, revision),
        "r-lock.json eyesim_roots differ from the pinned DESCRIPTION's requirements; run "
        "python3 tools/r-parity/provision.py --update --eyesim <checkout>",
        failures,
    )


def verify_mote(inventory: Inventory, failures: list[str]) -> None:
    manifest = inventory.manifest
    gap_issues = sorted(
        {
            case["gap_issue"]
            for case in manifest["cases"]
            if case["status"] == "implementation-gap"
        }
    )
    for issue in gap_issues:
        try:
            output = run(["mote", "show", issue])
        except (subprocess.CalledProcessError, FileNotFoundError):
            failures.append(f"gap issue is missing from Mote: {issue}")
            continue
        status = re.search(r"^status:\s+(\S+)", output, re.MULTILINE)
        require(
            status is not None and status.group(1) in {"open", "doing"},
            f"gap issue {issue} must remain open or doing",
            failures,
        )
    try:
        workflow = run(["mote", "show", WORKFLOW_ISSUE])
        for issue in gap_issues:
            require(
                issue in workflow,
                f"workflow issue is not blocked by gap issue {issue}",
                failures,
            )
    except (subprocess.CalledProcessError, FileNotFoundError):
        failures.append(f"workflow issue is missing from Mote: {WORKFLOW_ISSUE}")
    for ticket in inventory.fragments:
        try:
            run(["mote", "show", ticket])
        except (subprocess.CalledProcessError, FileNotFoundError):
            failures.append(f"manifest.d/{ticket}.json names no Mote task {ticket}")


def output_paths(manifest: dict) -> dict[str, Path]:
    fixtures = manifest.get("fixtures")
    fixtures = fixtures if isinstance(fixtures, dict) else {}
    return {
        fixture_id: ROOT / str(fixtures[fixture_id].get("path", ""))
        for fixture_id in regenerated_fixtures(manifest)
        if isinstance(fixtures.get(fixture_id), dict)
    }


def recorded_pins(manifest: dict) -> set[str]:
    """The revisions the regenerated fixtures currently record."""
    pins = set()
    for path in output_paths(manifest).values():
        document = read_json(path) if path.suffix == ".json" else None
        if isinstance(document, dict) and isinstance(
            document.get("eyesim_revision"), str
        ):
            pins.add(document["eyesim_revision"])
    return pins


def regeneration_plan(
    manifest: dict, eyesim: Path | None, write: bool
) -> list[tuple[str, list[str]]]:
    plan = []
    for regen_id, regen in manifest["regeneration"].items():
        if regen["requires_eyesim"] and eyesim is None:
            raise SystemExit(f"--run-regeneration requires --eyesim for {regen_id}")
        command = regen["command"]
        if eyesim is not None:
            command = command.replace("{eyesim}", str(eyesim))
        argv = shlex.split(command)
        if write:
            argv = [token for token in argv if token != "--check"]
        plan.append((regen_id, argv))
    return plan


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if text.count(old) != 1:
        raise SystemExit(
            f"cannot refresh {rel(path)}: {old!r} occurs {text.count(old)} times"
        )
    path.write_text(text.replace(old, new))


def refresh(inventory: Inventory, eyesim: Path, before: dict[str, str | None]) -> None:
    """After regeneration: record new digests and the eyesim version.

    Only an output the write pass actually changed gets a new digest. One it left as it was must
    still match its recorded digest, so hand edits and misdeclared outputs are not absorbed.
    """
    manifest = inventory.manifest
    stale = []
    for fixture_id, path in sorted(output_paths(manifest).items()):
        fixture = manifest["fixtures"][fixture_id]
        actual = sha256(path) if path.is_file() else None
        if actual == fixture["sha256"]:
            continue
        if actual is None or actual == before.get(fixture_id):
            stale.append(
                f"fixture {fixture_id} differs from its digest but no generator rewrote it"
            )
            continue
        replace_once(
            inventory.origins[fixture_id],
            f'"sha256": "{fixture["sha256"]}"',
            f'"sha256": "{actual}"',
        )
        print(f"refreshed digest of {fixture_id}", flush=True)
    if stale:
        raise SystemExit(
            "Regeneration left unexplained drift:\n- " + "\n- ".join(stale)
        )
    revision = manifest["eyesim"]["revision"]
    version = parity.dcf_field(parity.eyesim_description(eyesim, revision), "Version")
    if version != manifest["eyesim"]["version"]:
        replace_once(
            inventory.path,
            f'"version": "{manifest["eyesim"]["version"]}"',
            f'"version": "{version}"',
        )
        print(f"refreshed eyesim.version to {version}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--eyesim", type=Path, help="Git checkout containing the pinned eyesim object"
    )
    parser.add_argument(
        "--mote", action="store_true", help="also require every gap task to be live"
    )
    parser.add_argument(
        "--run-regeneration",
        action="store_true",
        help=(
            "run every fixture check; when the pin has moved, first regenerate every fixture, "
            "then fail so the rewritten tree is reviewed and committed"
        ),
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="with --run-regeneration: regenerate every fixture even if the pin has not moved",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="with --run-regeneration: print the commands instead of running them",
    )
    parser.add_argument(
        "--list-cases", action="store_true", help="list case ids by status"
    )
    args = parser.parse_args()
    if (args.write or args.dry_run) and not args.run_regeneration:
        parser.error("--write and --dry-run apply to --run-regeneration")

    failures: list[str] = []
    inventory = load_inventory(args.manifest, failures)
    manifest = inventory.manifest
    pin = manifest.get("eyesim", {}).get("revision")
    moved = args.run_regeneration and recorded_pins(manifest) not in (set(), {pin})
    regenerating = args.run_regeneration and (args.write or moved)
    if regenerating and args.eyesim is None:
        parser.error("regenerating fixtures requires --eyesim")
    verify_manifest(inventory, failures, regenerating)
    if args.eyesim is not None:
        verify_eyesim(manifest, args.eyesim, failures, regenerating)
    if args.mote:
        verify_mote(inventory, failures)
    if failures:
        raise SystemExit("Baseline contract failed:\n- " + "\n- ".join(failures))
    if args.run_regeneration:
        if moved:
            print(
                f"The pin moved to {pin}; fixtures record {sorted(recorded_pins(manifest))}.",
                flush=True,
            )
        passes = [True, False] if regenerating else [False]
        for write in passes:
            verb = ("would " if args.dry_run else "") + (
                "regenerate" if write else "run"
            )
            before = {
                fixture_id: sha256(path) if path.is_file() else None
                for fixture_id, path in output_paths(manifest).items()
            }
            for regen_id, argv in regeneration_plan(manifest, args.eyesim, write):
                print(f"{verb} {regen_id}: {shlex.join(argv)}", flush=True)
                if not args.dry_run:
                    subprocess.run(argv, cwd=ROOT, check=True)
            if write and not args.dry_run:
                refresh(inventory, args.eyesim, before)
                failures = []
                inventory = load_inventory(args.manifest, failures)
                manifest = inventory.manifest
                verify_manifest(inventory, failures)
                verify_eyesim(manifest, args.eyesim, failures)
                if failures:
                    raise SystemExit(
                        "Regenerated baseline failed:\n- " + "\n- ".join(failures)
                    )

    counts = {status: 0 for status in EXPECTED_STATUSES}
    for case in manifest["cases"]:
        counts[case["status"]] += 1
    print(
        "Baseline contract: "
        f"{len(manifest['rows'])} rows, {len(manifest['cases'])} cases; "
        + ", ".join(f"{status}={counts[status]}" for status in EXPECTED_STATUSES)
        + "."
    )
    excluded = [record["id"] for record in manifest.get("out_of_baseline", [])]
    if excluded:
        print(
            f"Out of baseline: {len(excluded)} case{'s' if len(excluded) != 1 else ''} "
            f"({', '.join(excluded)}), not counted above."
        )
    if args.list_cases:
        for status in EXPECTED_STATUSES:
            ids = [case["id"] for case in manifest["cases"] if case["status"] == status]
            print(f"{status}: {', '.join(ids) or '-'}")
        print(f"out-of-baseline: {', '.join(excluded) or '-'}")
    if moved and not args.write and not args.dry_run:
        raise SystemExit(
            f"The pin moved to {pin}: every registered fixture was regenerated, its digest "
            "refreshed, and every check passes on the new fixtures. This run still fails so that "
            "no gate passes on a tree it rewrote: review and commit the changes, then rerun."
        )


if __name__ == "__main__":
    main()
