#!/usr/bin/env python3
"""Pin admission behavior; independently check row, geometry and time accounting."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tarfile
import tempfile

sys.dont_write_bytecode = True
from generate_reference import ROOT, HERE, REVISION

INPUT = HERE / "fixtures/baseline-cases.json"


def reference(checkout):
    env = os.environ | {"LC_ALL": "C", "LANG": "C", "RGL_USE_NULL": "TRUE"}
    with tempfile.TemporaryDirectory(prefix="eyes4s-admission-") as name:
        tmp = Path(name)
        src, lib = tmp / "source", tmp / "library"
        src.mkdir(); lib.mkdir()
        archive = tmp / "source.tar"
        subprocess.run(["git", "-C", str(checkout), "archive", "--format=tar", "--output", str(archive), REVISION], check=True)
        with tarfile.open(archive) as tar:
            tar.extractall(src, filter="data")
        install = subprocess.run(["R", "CMD", "INSTALL", f"--library={lib}", str(src)], env=env, capture_output=True, text=True)
        if install.returncode:
            raise RuntimeError(install.stdout + install.stderr)
        output = tmp / "admission.json"
        subprocess.run(["Rscript", "--vanilla", str(HERE / "admission.R"), str(lib), str(INPUT), str(output)], env=env, check=True)
        return json.loads(output.read_text())


def verify(ref, rows):
    # Oracle does not call R grouping/clipping or any eyes4s implementation.
    def expected(source, bounds=(0, 100, 0, 50)):
        groups = {}
        xmin, xmax = sorted(bounds[:2]); ymin, ymax = sorted(bounds[2:])
        for row in source:
            if row["x"] is None or not (xmin <= row["x"] <= xmax and ymin <= row["y"] <= ymax):
                continue
            groups.setdefault((row["participant"], row["trial"]), []).append(row)
        return [(key, values) for key, values in sorted(groups.items())]
    variants = dict(original=rows, reversed=list(reversed(rows)), valid=[rows[0], rows[3]],
                    duplicate=[rows[0], rows[3], rows[0]],
                    missing=[rows[0] | {"x": None}, *rows[1:]],
                    boundary=[rows[0] | {"x": 100, "y": 50}, rows[3]])
    for name, source in variants.items():
        got = ref[name]["value"]["groups"]
        want = expected(source)
        assert len(got) == len(want), (name, got, want)
        for g, (key, values) in zip(got, want):
            assert (g["participant"], g["trial"]) == key
            assert g["data"]["coords"] == [[r["x"], r["y"]] for r in values]
            for field in ("onset", "duration"):
                actual = g["data"][field]
                assert (actual if isinstance(actual, list) else [actual]) == [r[field] for r in values]
    assert "negative" in ref["negative"]["value"]["error"]
    assert "error" in ref["empty"]["value"]
    assert "error" in ref["empty_group"]["value"]
    assert ref["negative_group"]["value"]["duration"][0] == -1
    assert ref["reclassify"]["value"]["names"] == "unrelated"
    for name, expected_coords in (("shifted", [[10, 20], [90, 40]]), ("flipped", [[90, 30], [10, 10]])):
        assert [g["data"]["coords"][0] for g in ref[name]["value"]["groups"]] == expected_coords


def scala(rows, ref):
    header = (ROOT / "io/src/main/scala/eyes4s/io/FixationCsv.scala").read_text().split("package ")[0]
    quoted = json.dumps
    lines = [header.rstrip(), "", "package eyes4s.io", "", "// Generated by tools/r-parity/generate_admission.py. Do not hand-edit.", "// format: off",
             "object AdmissionReference:",
             "  final case class Row(id: String, participant: String, trial: String, x: Double, y: Double, onset: Long, duration: Long)",
             "  val rows = Vector("]
    for row in rows:
        lines.append("    Row(" + ", ".join([quoted(row[k]) for k in ("id", "participant", "trial")] + [str(float(row[k])) for k in ("x", "y")] + [str(row[k]) + "L" for k in ("onset", "duration")]) + "),")
    lines += ["  )", "  val referenceRetained = Vector(" + ", ".join(quoted(r["id"]) for r in rows if r["x"] >= 0) + ")",
              "  val referenceEmptyGroupError = " + quoted(ref["empty_group"]["value"]["error"]), "// format: on", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--eyesim", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = json.loads(INPUT.read_text())["admission"]["rows"]
    ref = reference(args.eyesim)
    verify(ref, rows)
    doc = dict(eyesim_revision=REVISION, input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(), reference=ref,
               eyes4s_expected=dict(accepted=["valid-b"], rejected=["valid-a", "outside-left", "zero-duration"],
                   reason="Half-open frame and positive intervals; a bad keyed row quarantines its entire trial, without clipping."))
    outputs = {HERE / "fixtures/admission.json": json.dumps(doc, indent=2) + "\n",
               ROOT / "io/src/test/scala/eyes4s/io/AdmissionReference.scala": scala(rows, ref)}
    for path, content in outputs.items():
        if args.check:
            if path.read_text() != content:
                raise RuntimeError(f"Admission fixture drift: {path}")
        else:
            path.write_text(content)
    print("Admission reference and independent clipping/group/time oracle pass.")


if __name__ == "__main__":
    main()
