#!/usr/bin/env python3
"""Pinned KDE backends and density lookup, with independent direct Gaussian and index oracles."""
import argparse,hashlib,json,math
from pathlib import Path
import sys
sys.dont_write_bytecode=True
import parity
HERE,ROOT=parity.HERE,parity.ROOT
INPUT=HERE/'fixtures/cases/eyesim-kde.json'
OUTPUT=HERE/'fixtures/kde.json'
SCALA=ROOT/'surface/src/test/scala/eyes4s/surface/KdeReference.scala'
def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--eyesim',type=Path,required=True);p.add_argument('--check',action='store_true');args=p.parse_args()
    inputs=json.loads(INPUT.read_text())
    with parity.r_session('eyes4s-kde-') as session:
        lib=session.install_eyesim(args.eyesim);out=session.tmp/'reference.json'
        session.rscript(HERE/'kde.R',lib,INPUT,out);actual=json.loads(out.read_text())
    # Keep approximation/backend differences, including missing results, in the fixture.
    direct={}
    for name,record in actual['estimates'].items():
        d=record['value']
        if d is None or 'error' in d:continue
        backend,weighted,normalized=name.split('-'); sigma=inputs['sigma']/(4 if backend=='MASS' else 1)
        weights=inputs['durations_us'] if weighted=='TRUE' else [1]*len(inputs['x'])
        values=[sum(w*math.exp(-((x-px)**2+(y-py)**2)/(2*sigma*sigma))/(2*math.pi*sigma*sigma) for px,py,w in zip(inputs['x'],inputs['y'],weights,strict=True))/sum(weights) for y in d['y'] for x in d['x']]
        if normalized=='TRUE':values=[v/sum(values) for v in values]
        error=max(abs(a-b) for a,b in zip(values,d['z'],strict=True))
        direct[name]=dict(values=values,max_absolute_difference=error)
        if backend=='MASS':assert error<=1e-7,(name,error)
    expected_sigma=math.sqrt((2**2+1**2)/2)/1.349*3**(-1/6)
    assert abs(actual['suggested']['raw']-expected_sigma)<=1e-12
    assert actual['suggested']['bounded']==0.6 and actual['suggested']['constant']==0.04
    assert actual['suggested']['singleton'] is None
    assert actual['groups']['value']['groups']=='full'
    assert actual['groups_mass']['value']['groups']==[]
    assert actual['window']['value'] is None
    assert 'error' in actual['invalid_grid']['value']
    assert actual['defaults']['value']['sigma']==50
    assert actual['explicit_weights']['value']==actual['estimates']['MASS-FALSE-TRUE']['value']
    header=(ROOT/'surface/src/main/scala/eyes4s/surface/Smoother.scala').read_text().split('package ')[0]
    scala=header+'package eyes4s.surface\n\n// Generated by tools/r-parity/generate_kde.py.\n// format: off\nobject KdeReference:\n'
    def vec(v):return 'Vector('+','.join(repr(float(x)) for x in v)+')'
    for key in ['x','y','lookup_values','query_x','query_y']:
        scala+=f'  val {key}: Vector[Double] = '+vec(inputs[key])+'\n'
    for key in ['onsets_us','durations_us','times_us']:
        scala+=f'  val {key}: Vector[Long] = Vector('+','.join(str(x)+'L' for x in inputs[key])+')\n'
    scala+='  val lookup: Vector[(String,Vector[Double])] = Vector('+','.join('('+json.dumps(mode)+','+vec([r['z'] for r in rec['value']])+')' for mode,rec in actual['lookup'].items())+')\n'
    for key in ['timed','template_sample']:
        scala+=f'  val {key}: Vector[Option[Double]] = Vector('+','.join('None' if r['z'] is None else f"Some({float(r['z'])!r})" for r in actual[key]['value'])+')\n'
    scala+='  val suggested: Vector[Double] = '+vec([actual['suggested'][k] for k in ['raw','bounded','constant']])+'\n'
    scala+='// format: on\n' 
    document=dict(eyesim_revision=parity.pinned_revision(),input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),direct_gaussian=direct,reference=actual)
    for path,content in [(OUTPUT,json.dumps(document,indent=2)+'\n'),(SCALA,scala)]:
        if args.check:assert path.read_text()==content,f'Fixture drift: {path}'
        else:path.write_text(content)
    print('KDE backends, direct Gaussian differences, lookup and shared trajectory composition measured.')
if __name__=='__main__':main()
