#!/usr/bin/env python3
"""Independent 60-digit closed-form Gaussian oracle for the 2x2 fixation study."""
import argparse
import csv
import hashlib
import json
from collections import defaultdict
from decimal import Decimal, localcontext
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSV = ROOT / 'tools/r-parity/fixtures/matched-control.csv'
JSON = ROOT / 'tools/r-parity/fixtures/multiscale.json'
SCALA = ROOT / 'codec/src/test/scala/eyes4s/codec/MultiscaleFixtures.scala'
CONSUMER = ROOT / 'tools/study-consumer/src/test/scala/example/ConsumerFixtures.scala'


def generate():
    counts = defaultdict(lambda: [Decimal(0)] * 4)
    for row in csv.DictReader(CSV.open()):
        key = (row['participant'], row['image'], row['phase'])
        cell = int(Decimal(row['x_px'])) + 2 * int(Decimal(row['y_px']))
        counts[key][cell] += Decimal(row['duration_us'])
    result = {'input_sha256': hashlib.sha256(CSV.read_bytes()).hexdigest(),
              'oracle': '60-digit closed-form 2x2 Gaussian cell transfer; no convolution implementation',
              'scope': 'All four cells are corners; source edge correction is constant and cancels after mass normalization. Both edge policies therefore share these normalized targets only for this symmetric fixture.',
              'scales': []}
    with localcontext() as ctx:
        ctx.prec = 60
        for sigma in [Decimal('0.5'), Decimal('1'), Decimal('2')]:
            t = (-1 / (2 * sigma * sigma)).exp()
            masses = {}
            for key, v in sorted(counts.items()):
                total = sum(v)
                masses[key] = [(v[i] + t * (v[i ^ 1] + v[i ^ 2]) + t*t*v[i ^ 3]) / (total * (1+t)**2) for i in range(4)]
            def cosine(a, b):
                return sum(x*y for x, y in zip(a,b)) / (sum(x*x for x in a)*sum(y*y for y in b)).sqrt()
            differences = {}
            for key, mass in masses.items():
                person, stimulus, phase = key
                if phase != 'recall':
                    continue
                matched = cosine(mass, masses[(person, stimulus, 'encode')])
                controls = [cosine(mass, m) for (p,s,f),m in masses.items() if p == person and s != stimulus and f == 'encode']
                differences['/'.join(key)] = str(matched - sum(controls)/len(controls))
            result['scales'].append({'sigma': str(sigma), 'masses': {'/'.join(k): [str(x) for x in v] for k,v in masses.items()}, 'differences': differences})
    payload = json.dumps(result, indent=2) + '\n'
    header = (ROOT / 'design/src/main/scala/eyes4s/design/Analysis.scala').read_text().split('package eyes4s.design')[0]
    source = header + 'package eyes4s.codec\n\n// Generated by tools/r-parity/generate_multiscale.py; do not edit.\n// format: off\nobject MultiscaleFixtures:\n  final case class Scale(sigma: Double, masses: Vector[(String, Vector[Double])], differences: Vector[(String, Double)])\n  val scales = Vector(\n'
    for scale in result['scales']:
        masses = ', '.join(json.dumps(k) + ' -> Vector(' + ', '.join(str(float(x)) for x in v) + ')' for k,v in scale['masses'].items())
        diffs = ', '.join(json.dumps(k) + ' -> ' + str(float(v)) for k,v in scale['differences'].items())
        source += f'    Scale({float(scale["sigma"])}, Vector({masses}), Vector({diffs})),\n'
    source += '  )\n// format: on\n'
    consumer = header + 'package example\n\n// Generated by tools/r-parity/generate_multiscale.py; data only.\n// format: off\nobject ConsumerFixtures:\n  val csv = """' + CSV.read_text() + '"""\n  val gaussianTargets = Vector(\n'
    for scale in result['scales']:
        targets = []
        for key, value in scale['differences'].items():
            person, stimulus, phase = key.split('/')
            custom_key = f"{person}/{ord(stimulus) - ord('a') + 1}/{phase}"
            targets.append(json.dumps(custom_key) + ' -> ' + str(float(value)))
        consumer += f'    {float(scale["sigma"])} -> Map(' + ', '.join(targets) + '),\n'
    consumer += '  )\n// format: on\n'
    return {JSON: payload, SCALA: source, CONSUMER: consumer}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in generate().items():
        if args.check:
            assert path.read_text() == text, f'Stale oracle: {path}'
        else:
            path.write_text(text)
    print('Verified 3 scales, 36 normalized maps, and 18 matched/control contrasts.' if args.check else 'Generated multiscale oracle.')
