#!/usr/bin/env python3
"""Measure exported eyesim scanpath and fixation comparison routes under the lock."""
import argparse, json, hashlib, sys, math
from pathlib import Path

sys.dont_write_bytecode = True
import parity

HERE, ROOT = parity.HERE, parity.ROOT
INPUT = HERE / "fixtures/cases/eyesim-scanpath.json"
OUTPUT = HERE / "fixtures/scanpath.json"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--eyesim", type=Path, required=True)
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    with parity.r_session("eyes4s-scanpath-") as r:
        lib = r.install_eyesim(args.eyesim)
        out = r.tmp / "reference.json"
        r.rscript(HERE / "scanpath.R", lib, INPUT, out)
        actual = json.loads(out.read_text())
    # Analytic translation, duration and one-plan transport expectations are independent.
    for row in actual["paths"][:6]:
        assert row["direct"]["result"]["values"] == row["facade"]["result"]["values"]
    for group in actual["overlap"]:
        distance = 50 if group["method"] == "euclidean" else 70
        for row in group["rows"]:
            # Five of the six queries have support: -20 precedes both paths and 220 holds the last fixation.
            count = 5 if distance < row["threshold"] else 0
            assert row["out"]["result"]["overlap"] == count
            assert abs(row["out"]["result"]["perc"] - count / 6) <= 1e-12
    assert actual["defaults"]["direct"]["result"]["overlap"] == 11
    # The facade defaults to the direct threshold 60, so the Euclidean distance 50 overlaps.
    assert abs(actual["defaults"]["facade"]["result"]["values"] - 5 / 6) <= 1e-12
    # The default grid spans both paths' onsets, 0 to 400 by 20: 11 of 21 points overlap.
    asymmetric = actual["defaults"]["asymmetric_grid"]["result"]
    assert asymmetric["overlap"] == 11 and abs(asymmetric["perc"] - 11 / 21) <= 1e-12
    table = actual["scanpath_table"]["result"][0]
    for name, value in zip(
        actual["paths"][1]["direct"]["result"]["names"],
        actual["paths"][1]["direct"]["result"]["values"],
        strict=True,
    ):
        assert table[name] == value
    translated = actual["paths"][1]["direct"]["result"]["values"]
    expected = [1, 1, 1, 1 - 50 / math.hypot(800, 400), 1]
    assert (
        max(abs(a - b) for a, b in zip(translated[:5], expected, strict=True)) <= 1e-12
    )
    assert abs(actual["paths"][2]["direct"]["result"]["values"][4] - 0.5) <= 1e-12
    assert (
        abs(
            actual["transport"]["singleton"]["result"]["values"]
            - 1 / (1 + math.sqrt(1.25))
        )
        <= 1e-12
    )
    two = actual["transport"]["two_point"]["result"]
    assert abs(two["distance"] - math.sqrt(1 / (1 + math.exp(2)))) <= 1e-12
    header = (
        (ROOT / "compare/src/main/scala/eyes4s/compare/Distribution.scala")
        .read_text()
        .split("package ")[0]
    )
    inputs = json.loads(INPUT.read_text())

    def vec(xs):
        return "Vector(" + ",".join(repr(float(x)) for x in xs) + ")"

    scala = (
        header
        + "package eyes4s.compare\n\n// Generated by tools/r-parity/generate_scanpath.py.\n// format: off\nobject ScanpathReference:\n"
    )
    scala += "  final case class Path(name: String,x: Vector[Double],y: Vector[Double],onset: Vector[Double],duration: Vector[Double],expected: Vector[Double])\n"
    scala += (
        "  val paths: Vector[Path] = Vector(\n"
        + ",\n".join(
            "    Path("
            + ",".join(
                [json.dumps(p["name"])]
                + [vec(p[k]) for k in ["x", "y", "onset", "duration"]]
                + [vec(r["direct"]["result"]["values"])]
            )
            + ")"
            for p, r in zip(inputs["paths"], actual["paths"], strict=True)
            if p["name"]
            in ["base", "translated", "duration", "changed", "tie", "stationary"]
        )
        + "\n  )\n"
    )
    scala += (
        "  val tieSelf: Vector[Double] = "
        + vec(actual["tie_self"]["result"]["values"])
        + "\n"
    )
    scala += (
        "  val overlap: Vector[(String,Double,Int,Double)] = Vector("
        + ",".join(
            "("
            + ",".join(
                [
                    json.dumps(group["method"]),
                    repr(row["threshold"]),
                    str(row["out"]["result"]["overlap"]),
                    repr(row["out"]["result"]["perc"]),
                ]
            )
            + ")"
            for group in actual["overlap"]
            for row in group["rows"]
        )
        + ")\n"
    )
    # Independent small primal scaling oracle; records every default-backend discrepancy.
    oracle = []
    a, b = inputs["paths"][:2]
    cost = [
        [
            ((x - u) / 1000) ** 2 + ((y - v) / 1000) ** 2 + ((t - r) / 3000 * 0.8) ** 2
            for u, v, r in zip(b["x"], b["y"], b["onset"], strict=True)
        ]
        for x, y, t in zip(a["x"], a["y"], a["onset"], strict=True)
    ]
    for row in actual["transport"]["lambdas"]:
        l = row["lambda"]
        k = [[math.exp(-c / l) for c in line] for line in cost]
        u = [1.0] * 3
        v = [1.0] * 3
        for iteration in range(100000):
            u = [(1 / 3) / sum(k[i][j] * v[j] for j in range(3)) for i in range(3)]
            v = [(1 / 3) / sum(k[i][j] * u[i] for i in range(3)) for j in range(3)]
            plan = [[u[i] * k[i][j] * v[j] for j in range(3)] for i in range(3)]
            residual = max(abs(sum(line) - 1 / 3) for line in plan)
            if residual <= 1e-14:
                break
        assert residual <= 1e-14
        squared = sum(plan[i][j] * cost[i][j] for i in range(3) for j in range(3))
        value = 1 / (1 + math.sqrt(squared))
        reference = row["result"]["result"]["values"]
        oracle.append(
            dict(
                lambda_value=l,
                similarity=value,
                squared_cost=squared,
                marginal_residual=residual,
                iterations=iteration + 1,
                reference_delta=reference - value,
                reference_pass_1e_7=abs(reference - value) <= 1e-7,
            )
        )
    actual["transport"]["independent_primal_oracle"] = oracle
    scala += (
        "  val transport: Vector[(Double,Double,Double,Boolean)] = Vector("
        + ",".join(
            "("
            + repr(row["lambda_value"])
            + ","
            + repr(row["similarity"])
            + ","
            + repr(row["similarity"] + row["reference_delta"])
            + ","
            + str(row["reference_pass_1e_7"]).lower()
            + ")"
            for row in oracle
        )
        + ")\n// format: on\n"
    )
    target = ROOT / "compare/src/test/scala/eyes4s/compare/ScanpathReference.scala"
    if args.check:
        assert target.read_text() == scala, "Scanpath Scala fixture drift"
    else:
        target.write_text(scala)
    content = (
        json.dumps(
            dict(
                eyesim_revision=parity.pinned_revision(),
                input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),
                reference=actual,
            ),
            indent=2,
        )
        + "\n"
    )
    if args.check:
        assert OUTPUT.read_text() == content, "Scanpath fixture drift"
    else:
        OUTPUT.write_text(content)
    print("Exported scanpath/fixation outputs and every missing/error result recorded.")


if __name__ == "__main__":
    main()
