#!/usr/bin/env python3
"""Independent integer-overlap and 60-digit cosine targets for repeated temporal studies."""
import argparse
import csv
from decimal import Decimal, localcontext
import hashlib
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
WINDOWS = [('early',0,300000),('middle',300000,600000),('late',600000,950000),('outside',950000,1100000)]
REPEATS = [('recall-encode','recall','encode'),('retest-recall','retest','recall')]


def generate():
    rows = list(csv.DictReader((HERE/'fixtures/matched-control.csv').open()))
    rows += [dict(row, phase='retest', x_px=str(2-float(row['y_px'])), y_px=row['x_px']) for row in rows if row['phase']=='recall']
    buf=io.StringIO(); writer=csv.DictWriter(buf,fieldnames=list(rows[0]),lineterminator='\n');writer.writeheader();writer.writerows(rows)
    csv_text=buf.getvalue()
    grouped={}
    for row in rows:
        key='/'.join(row[x] for x in ['participant','image','phase'])
        grouped.setdefault(key,[]).append(row)
    support={key: ([(0,350000),(500000,930000)] if key=='s2/b/retest' else [(0,930000)]) for key in grouped}
    targets=[]; ledgers=[]; pairs=[]
    with localcontext() as ctx:
        ctx.prec=60
        for window,start,end in WINDOWS:
            masses={}
            for key,fixations in grouped.items():
                counts=[0]*4; retained=[]
                for fix in fixations:
                    onset=int(fix['onset_us']);offset=onset+int(fix['duration_us'])
                    duration=sum(max(0,min(end,offset,b)-max(start,onset,a)) for a,b in support[key])
                    retained.append(duration)
                    counts[int(float(fix['x_px']))+2*int(float(fix['y_px']))]+=duration
                observed=sum(max(0,min(end,b)-max(start,a)) for a,b in support[key])
                ledgers.append(dict(key=key,window=window,retained=retained,observed=observed,missing=end-start-observed))
                masses[key]=counts
            for sigma in [None,1.0]:
                maps={}
                for key,v in masses.items():
                    if not sum(v):
                        maps[key]=None;continue
                    if sigma is None:
                        maps[key]=[Decimal(x)/sum(v) for x in v]
                    else:
                        t=(-Decimal(1)/2).exp()
                        maps[key]=[(v[i]+t*(v[i^1]+v[i^2])+t*t*v[i^3])/(sum(v)*(1+t)**2) for i in range(4)]
                def cosine(a,b):
                    if a is None or b is None:return None
                    return sum(x*y for x,y in zip(a,b))/(sum(x*x for x in a)*sum(x*x for x in b)).sqrt()
                for repeat,focal,reference in REPEATS:
                    for key in sorted(k for k in grouped if k.split('/')[2]==focal):
                        person,image,_=key.split('/')
                        matched=[];control=[]
                        for target in sorted(k for k in grouped if k.split('/')[2]==reference):
                            p,s,_=target.split('/')
                            if person!=p:continue
                            kind='matched' if image==s else 'control'
                            (matched if kind=='matched' else control).append(cosine(maps[key],maps[target]))
                            if window=='early' and sigma is None:pairs.append(dict(repetition=repeat,left=key,right=target,kind=kind))
                        assert len(matched)==1 and len(control)==2
                        value=None if any(x is None for x in matched+control) else matched[0]-sum(control)/len(control)
                        targets.append(dict(repetition=repeat,key=key,window=window,sigma=sigma,difference=None if value is None else str(value)))
    data=dict(input_sha256=hashlib.sha256(csv_text.encode()).hexdigest(),windows=WINDOWS,repetitions=REPEATS,coverage=support,ledgers=ledgers,pairs=pairs,targets=targets)
    header=(ROOT/'codec/src/test/scala/eyes4s/codec/StudyCodecSuite.scala').read_text().split('package eyes4s.codec')[0]
    scala=header+'package eyes4s.codec\n\n// Generated by tools/r-parity/generate_temporal.py; data only.\n// format: off\nobject TemporalFixtures:\n'
    scala+='  val csv = """'+csv_text+'"""\n'
    scala+='  val windows = Vector('+','.join(f'({json.dumps(n)}, {a}L, {b}L)' for n,a,b in WINDOWS)+')\n'
    scala+='  val repetitions = Vector('+','.join('('+','.join(json.dumps(x) for x in xs)+')' for xs in REPEATS)+')\n'
    scala+='  val coverage = Map('+','.join(json.dumps(k)+' -> Vector('+','.join(f'({a}L,{b}L)' for a,b in intervals)+')' for k,intervals in support.items())+')\n'
    scala+='  final case class Target(repetition: String, key: String, window: String, sigma: Option[Double], difference: Option[Double])\n  val targets = Vector(\n'
    for t in targets:
        opt=lambda x:'None' if x is None else f'Some({float(x)})'
        scala+='    Target('+','.join(json.dumps(t[x]) for x in ['repetition','key','window'])+','+opt(t['sigma'])+','+opt(t['difference'])+'),\n'
    scala+='  )\n  val ledgers = Vector(\n'
    for t in ledgers:
        scala+=f'    ({json.dumps(t["key"])},{json.dumps(t["window"])},Vector('+','.join(str(x)+'L' for x in t['retained'])+f'),{t["observed"]}L,{t["missing"]}L),\n'
    scala+='  )\n  val pairs = Vector('+','.join('('+','.join(json.dumps(p[x]) for x in ['repetition','left','right','kind'])+')' for p in pairs)+')\n// format: on\n'
    # The isolated consumer (tools/study-consumer) carries the same data in its own package.
    consumer=scala.replace('package eyes4s.codec\n','package example\n',1).replace('object TemporalFixtures:','object TemporalConsumerFixtures:',1)
    return {HERE/'fixtures/temporal-study.csv':csv_text,HERE/'fixtures/temporal.json':json.dumps(data,indent=2)+'\n',ROOT/'codec/src/test/scala/eyes4s/codec/TemporalFixtures.scala':scala,ROOT/'tools/study-consumer/src/test/scala/example/TemporalConsumerFixtures.scala':consumer}

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,value in generate().items():
        if args.check:assert path.read_text()==value,f'Stale fixture {path}'
        else:path.write_text(value)
    print('Temporal oracle: 72 fixations, 18 trials, 72 window ledgers, 36 pairs and 96 contrasts including empty windows.')
