#!/usr/bin/env python3
"""Pin public eyesim repetition calls and independent exact pair expectations."""
import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import sys

sys.dont_write_bytecode = True
import parity  # noqa: E402
from generate_reference import ROOT, HERE, INPUT, REVISION, oracle, TOLERANCE  # noqa: E402


def expected(weights):
    result = []
    for key, vector in weights.items():
        score = lambda other: Fraction(sum(a * b for a, b in zip(vector, weights[other])), 25)
        same = [other for other in weights if other != key and other[2] == key[2]]
        different = [other for other in weights if other[2] != key[2]]
        targets = [other for other in weights if other[0] == key[0] and other[1] == key[1] and other[2] != key[2]]
        controls = [other for other in weights if other[0] == key[0] and other[1] != key[1] and other[2] != key[2]]
        mean = lambda keys: str(sum(map(score, keys), Fraction()) / len(keys))
        result.append(dict(id="/".join(key), weights=list(vector),
            reference_same=mean(same), reference_other=mean(different),
            reference_pairs=[str(score(k)) for k in same],
            target=mean(targets), control=mean(controls),
            targets=["/".join(k) for k in targets], controls=["/".join(k) for k in controls]))
    return result


def verify(reference, rows, weights):
    for name in ("pairwise", "reduced"):
        assert len(reference[name]["rows"]) == len(rows)
        for got, want in zip(reference[name]["rows"], rows):
            assert got["id"] == want["id"]
            for key in ("same", "other"):
                assert abs(got[key] - float(Fraction(want["reference_" + key]))) <= TOLERANCE
            if name == "pairwise":
                assert len(got["pairs"]) == 5
                assert all(abs(a - float(Fraction(b))) <= TOLERANCE
                           for a, b in zip(got["pairs"], want["reference_pairs"]))
    duplicate_keys = list(weights) + [next(iter(weights))]
    assert len(reference["duplicate"]["rows"]) == 13
    for i, got in enumerate(reference["duplicate"]["rows"]):
        key = duplicate_keys[i]
        for field, equal in (("same", True), ("other", False)):
            candidates = [k for j, k in enumerate(duplicate_keys) if j != i and ((key[2] == k[2]) == equal)]
            score = lambda other: Fraction(sum(a*b for a,b in zip(weights[key],weights[other])),25)
            want = sum(map(score,candidates),Fraction()) / len(candidates)
            assert abs(got[field] - float(want)) <= TOLERANCE
    assert reference["singleton"]["rows"][0]["same"] == "NA"
    assert reference["singleton"]["rows"][0]["other"] == "NA"
    assert reference["empty"]["rows"] == []
    assert any(Fraction(r["target"]) != Fraction(r["reference_same"]) for r in rows)


def scala(rows, reference):
    header = (ROOT / "design/src/main/scala/eyes4s/design/Repetition.scala").read_text().split("package ")[0]
    lines = [header.rstrip(), "", "package eyes4s.design", "",
        "// Generated by tools/r-parity/generate_repetition.py. Do not hand-edit.",
        "// format: off", "object RepetitionReference:",
        "  final case class Row(id: String, weights: Vector[Double], target: Double, control: Double, referenceSame: Double, referenceOther: Double, targets: Vector[String], controls: Vector[String])",
        "  val rows = Vector("]
    vector = lambda values: "Vector(" + ", ".join(values) + ")"
    for row, ref in zip(rows, reference["pairwise"]["rows"]):
        values = [json.dumps(row["id"]), vector([str(float(x)) for x in row["weights"]]),
            str(float(Fraction(row["target"]))), str(float(Fraction(row["control"]))),
            repr(ref["same"]), repr(ref["other"]),
            vector([json.dumps(x) for x in row["targets"]]), vector([json.dumps(x) for x in row["controls"]])]
        lines.append("    Row(" + ", ".join(values) + "),")
    return "\n".join(lines + ["  )", "// format: on", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--eyesim", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    _, weights, _ = oracle()
    rows = expected(weights)
    # The pinned archive in the locked R session; never an arbitrary installed eyesim package.
    with parity.r_session("eyes4s-repetition-", args.eyesim) as r:
        output = r.tmp / "repetition.json"
        r.rscript(HERE / "repetition.R", r.eyesim_library, INPUT, output)
        reference = json.loads(output.read_text())
    verify(reference, rows, weights)
    document = dict(eyesim_revision=REVISION, input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),
        tolerance=dict(absolute=TOLERANCE, relative=0), exact=rows, reference=reference)
    files = {HERE / "fixtures/repetition.json": json.dumps(document, indent=2) + "\n",
        ROOT / "design/src/test/scala/eyes4s/design/RepetitionReference.scala": scala(rows, reference)}
    for path, content in files.items():
        if args.check:
            if path.read_text() != content:
                raise RuntimeError(f"Repetition fixture drift: {path}")
        else:
            path.write_text(content)
    print("Checked repetition reference: pairwise/reduced, duplicate, singleton and empty; exact oracle passes.")


if __name__ == "__main__":
    main()
