#!/usr/bin/env python3
"""Pin trajectory, duration replication and finite controls without emulating R as production code."""
import argparse, hashlib, json, math
from pathlib import Path
import sys

sys.dont_write_bytecode = True
import parity

HERE, ROOT = parity.HERE, parity.ROOT
INPUT = HERE / "fixtures/cases/eyesim-sampling.json"
OUTPUT = HERE / "fixtures/sampling.json"
SCALA = ROOT / "core/src/test/scala/eyes4s/core/SamplingReference.scala"
CONTROL = ROOT / "design/src/test/scala/eyes4s/design/FiniteControlReference.scala"


def sequence(v):
    return v if isinstance(v, list) else [v]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--eyesim", type=Path, required=True)
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    inputs = json.loads(INPUT.read_text())
    with parity.r_session("eyes4s-sampling-") as session:
        lib = session.install_eyesim(args.eyesim)
        out = session.tmp / "reference.json"
        session.rscript(HERE / "sampling.R", lib, INPUT, out)
        actual = json.loads(out.read_text())
    # floor(duration * resolution) with a floating-point tolerance: 0.29 s at 100 Hz is 29 copies.
    assert sequence(actual["replication"]["counts"]) == [29, 1, 1, 1, 3]
    # The fast and slow paths sample the same positions at the pin: both hold the last fixation
    # and take the last tied onset. Only their returned duration columns differ.
    for t in actual["trajectories"]:
        fast, slow = t["fast"]["result"], t["slow"]["result"]
        if "error" in fast or "error" in slow:
            assert fast == slow, t["name"]
        else:
            assert (fast["x"], fast["y"]) == (slow["x"], slow["y"]), t["name"]
    refs = {r["match"]: r["values"] for r in inputs["controls"]}
    refvalues = list(refs.values())
    for case in actual["controls"]:
        if case["cap"] == 0:
            continue
        for row, indices in zip(
            case["rows"], case["selected_reference_indices"], strict=True
        ):
            indices = sequence(indices) if indices is not None else []
            source = next(
                r["values"] for r in inputs["controls"] if r["key"] == row["key"]
            )
            scores = [
                sum(x * y for x, y in zip(source, refvalues[i - 1]))
                / math.sqrt(
                    sum(x * x for x in source) * sum(y * y for y in refvalues[i - 1])
                )
                for i in indices
            ]
            assert row["n_perm"] == len(indices)
            assert (row["perm_sim"] is None and not scores) or abs(
                row["perm_sim"] - sum(scores) / len(scores)
            ) <= 1e-12
    for density, fixation in zip(
        actual["controls"], actual["fixation_controls"], strict=True
    ):
        assert "error" not in fixation["result"], fixation
        for dr, fr in zip(density["rows"], fixation["result"], strict=True):
            assert dr["key"] == fr["key"]
            if density["cap"] == 20:
                assert dr["n_perm"] == fr["n_perm"], (dr, fr)
    header = (
        (ROOT / "core/src/main/scala/eyes4s/core/Scanpath.scala")
        .read_text()
        .split("package ")[0]
    )
    scala = (
        header
        + "package eyes4s.core\n\n// Generated by tools/r-parity/generate_sampling.py.\n// format: off\nobject SamplingReference:\n"
    )
    scala += "  final case class Case(name: String,onsets: Vector[Long],durations: Vector[Long],x: Vector[Double],y: Vector[Double],queries: Vector[Long],fast: Option[Vector[Option[(Double,Double)]]],slow: Option[Vector[Option[(Double,Double)]]])\n"

    def longs(v):
        return "Vector(" + ",".join(str(x) + "L" for x in v) + ")"

    def doubles(v):
        return "Vector(" + ",".join(repr(float(x)) for x in v) + ")"

    def expected(c):
        r = c["result"]
        if "error" in r:
            return "None"
        return (
            "Some(Vector("
            + ",".join(
                "None"
                if x is None or y is None
                else f"Some(({float(x)!r},{float(y)!r}))"
                for x, y in zip(sequence(r["x"]), sequence(r["y"]), strict=True)
            )
            + "))"
        )

    scala += (
        "  val cases: Vector[Case] = Vector(\n"
        + ",\n".join(
            "    Case("
            + ",".join(
                [
                    json.dumps(c["name"]),
                    longs(c["onsets"]),
                    longs(c["durations"]),
                    doubles(c["x"]),
                    doubles(c["y"]),
                    longs(c["queries"]),
                    expected(a["fast"]),
                    expected(a["slow"]),
                ]
            )
            + ")"
            for c, a in zip(inputs["trajectories"], actual["trajectories"], strict=True)
        )
        + "\n  )\n// format: on\n"
    )
    control = (
        header
        + "package eyes4s.design\n\n// Generated by tools/r-parity/generate_sampling.py.\n// format: off\nobject FiniteControlReference:\n"
    )
    control += "  final case class Source(key: String,matched: String,stratum: String,values: Vector[Double])\n"
    control += "  final case class Result(cap: Int,key: String,count: Option[Int],mean: Option[Double],selected: Vector[Int])\n"
    control += (
        "  val sources: Vector[Source] = Vector("
        + ",".join(
            "Source("
            + ",".join(
                [
                    json.dumps(r["key"]),
                    json.dumps(r["match"]),
                    json.dumps(r["stratum"]),
                    doubles(r["values"]),
                ]
            )
            + ")"
            for r in inputs["controls"]
        )
        + ")\n"
    )
    results = []
    for c in actual["controls"]:
        for r, selected in zip(c["rows"], c["selected_reference_indices"], strict=True):
            selected = sequence(selected) if selected is not None else []
            count = "None" if "n_perm" not in r else "Some(" + str(r["n_perm"]) + ")"
            mean = (
                "None"
                if r.get("perm_sim") is None
                else "Some(" + repr(float(r["perm_sim"])) + ")"
            )
            results.append(
                "Result("
                + ",".join(
                    [
                        str(c["cap"]),
                        json.dumps(r["key"]),
                        count,
                        mean,
                        "Vector(" + ",".join(map(str, selected)) + ")",
                    ]
                )
                + ")"
            )
    control += (
        "  val results: Vector[Result] = Vector(\n    "
        + ",\n    ".join(results)
        + "\n  )\n// format: on\n"
    )
    document = dict(
        eyesim_revision=parity.pinned_revision(),
        input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),
        tolerance=dict(absolute=1e-12, relative=0),
        reference=actual,
    )
    for path, content in [
        (OUTPUT, json.dumps(document, indent=2) + "\n"),
        (SCALA, scala),
        (CONTROL, control),
    ]:
        if args.check:
            assert path.read_text() == content, f"Fixture drift: {path}"
        else:
            path.write_text(content)
    print(
        "Pinned trajectories, replication and finite-control calls measured; errors, missing values and realized denominators retained."
    )


if __name__ == "__main__":
    main()
