#!/usr/bin/env python3
"""Pin complete repetition dispatch and independently compute directed/nested means."""
import argparse,json,hashlib,sys
from pathlib import Path
sys.dont_write_bytecode=True
import parity
from generate_compare import oracle
HERE,ROOT=parity.HERE,parity.ROOT
INPUT=HERE/'fixtures/cases/eyesim-repetition.json'
OUTPUT=HERE/'fixtures/repetition-methods.json'
SCALA=ROOT/'design/src/test/scala/eyes4s/design/RepetitionMethodsReference.scala'
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--eyesim',type=Path,required=True);p.add_argument('--check',action='store_true');args=p.parse_args()
 inputs=json.loads(INPUT.read_text());rows=inputs['rows']
 with parity.r_session('eyes4s-repetition-methods-') as r:
  lib=r.install_eyesim(args.eyesim);out=r.tmp/'reference.json';r.rscript(HERE/'repetition_methods.R',lib,INPUT,out);actual=json.loads(out.read_text())
 expected=[]
 def mean(v):
  valid=[x for x in v if x is not None];return sum(valid)/len(valid) if valid else None
 def near(a,b):return a is None and b is None or a is not None and b is not None and abs(a-b)<=1e-12
 for method in inputs['methods'][:-1]:
  records=[]
  for i,a in enumerate(rows):
   same=[j for j,b in enumerate(rows) if j!=i and a['occasion']==b['occasion']]
   other=[j for j,b in enumerate(rows) if a['occasion']!=b['occasion']]
   def scores(js):return [oracle(a['values'],rows[j]['values'],method) for j in js]
   def scale_scores(js):return [[oracle(a['scale1'],rows[j]['scale1'],method),oracle(a['values'],rows[j]['values'],method)] for j in js]
   one=dict(key=a['key'],same=same,other=other,scores_same=scores(same),scores_other=scores(other),scales_same=scale_scores(same),scales_other=scale_scores(other))
   one.update(mean_same=mean(one['scores_same']),mean_other=mean(one['scores_other']),nested_same=mean([mean(v) for v in one['scales_same']]),nested_other=mean([mean(v) for v in one['scales_other']]),pooled_same=mean([x for v in one['scales_same'] for x in v]))
   records.append(one)
   ref=actual['methods'][method]
   for name in ['pairwise','reduced']:
    got=ref['single'][name]['result'][i];assert near(got['repsim'],one['mean_same']),(method,name,i,got,one);assert near(got['othersim'],one['mean_other'])
    if name=='pairwise':
     pair_values=got['pairwise_repsim'];pair_values=pair_values if isinstance(pair_values,list) else [pair_values]
     assert len(pair_values)==len(one['scores_same']) and all(near(a,b) for a,b in zip(pair_values,one['scores_same'],strict=True))
   for name in ['mean','none']:
    got=ref['scales'][name]['result'][i];assert near(got['repsim'],one['nested_same']),(method,name,i,got,one);assert near(got['othersim'],one['nested_other'])
  expected.append(dict(method=method,rows=records))
 assert any(r['nested_same'] is not None and r['pooled_same'] is not None and abs(r['nested_same']-r['pooled_same'])>1e-3 for m in expected for r in m['rows'])
 header=(ROOT/'design/src/main/scala/eyes4s/design/Repetition.scala').read_text().split('package ')[0]
 def vec(v):return 'Vector('+','.join(repr(float(x)) for x in v)+')'
 def option(x):return 'None' if x is None else 'Some('+repr(x)+')'
 scala=header+'package eyes4s.design\n\n// Generated by tools/r-parity/generate_repetition_methods.py.\n// format: off\nobject RepetitionMethodsReference:\n'
 scala+='  final case class Row(key: String,participant: String,stimulus: String,occasion: String,values: Vector[Double],scale1: Vector[Double])\n'
 scala+='  val rows: Vector[Row] = Vector(\n'+',\n'.join('    Row('+','.join([json.dumps(r[k]) for k in ['key','participant','stimulus','occasion']]+[vec(r['values']),vec(r['scale1'])])+')' for r in rows)+'\n  )\n'
 scala+='  final case class Mean(key: String,same: Option[Double],other: Option[Double],nestedSame: Option[Double],nestedOther: Option[Double],pooledSame: Option[Double])\n'
 scala+='  val methods: Vector[(String,Vector[Mean])] = Vector(\n'+',\n'.join('    ('+json.dumps(m['method'])+',Vector('+','.join('Mean('+','.join([json.dumps(r['key'])]+[option(r[k]) for k in ['mean_same','mean_other','nested_same','nested_other','pooled_same']])+')' for r in m['rows'])+'))' for m in expected)+'\n  )\n// format: on\n'
 document=dict(eyesim_revision=parity.pinned_revision(),input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),independent=expected,reference=actual)
 for path,content in [(OUTPUT,json.dumps(document,indent=2)+'\n'),(SCALA,scala)]:
  if args.check:assert path.read_text()==content,f'Fixture drift: {path}'
  else:path.write_text(content)
 print('Repetition methods, directed Cartesian means and heterogeneous nested scale denominators verified.')
if __name__=='__main__':main()
