#!/usr/bin/env python3
"""Measure pinned public template CV and independent analytic cosine/fold exclusion evidence."""
import argparse, hashlib, json, math
from pathlib import Path
import sys
sys.dont_write_bytecode = True
import parity
HERE, ROOT = parity.HERE, parity.ROOT
INPUT = HERE/'fixtures/cases/eyesim-template.json'
OUTPUT = HERE/'fixtures/template-cv.json'
SCALA = ROOT/'design/src/test/scala/eyes4s/design/TemplateCvReference.scala'
def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--eyesim',type=Path,required=True)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    inputs=json.loads(INPUT.read_text())
    with parity.r_session('eyes4s-template-cv-') as session:
        lib=session.install_eyesim(args.eyesim)
        result=session.tmp/'reference.json'
        session.rscript(HERE/'template_cv.R',lib,INPUT,result)
        actual=json.loads(result.read_text())
    bykey={r['key']:r for r in inputs['source']}
    refs={r['match']:r['values'] for r in inputs['reference']}
    for r in actual['normal']['rows']:
        a=bykey[r['key']]['values']; b=refs[r['matched']]
        expected=sum(x*y for x,y in zip(a,b))/math.sqrt(sum(x*x for x in a)*sum(x*x for x in b))
        assert abs(expected-r['eye_sim']) <= 1e-12,(r,expected)
    # Preserve the pinned RNG side effect as measured, rather than changing the oracle.
    assert actual['duplicate_reference']['rows']==actual['normal']['rows']
    assert [r['key'] for r in actual['missing_reference']['rows']]==['s2','s3','s4','s5']
    header=(ROOT/'design/src/main/scala/eyes4s/design/TemplateFit.scala').read_text().split('package ')[0]
    scala=header+'package eyes4s.design\n\n// Generated by tools/r-parity/generate_template_cv.py.\n// format: off\nobject TemplateCvReference:\n'
    scala+='  final case class Row(key: String, group: String, matched: String, values: Vector[Double], fold: Int, expected: Double)\n'
    def vector(v): return 'Vector('+','.join(repr(float(x)) for x in v)+')'
    scala+='  val rows: Vector[Row] = Vector(\n'+',\n'.join('    Row('+','.join([json.dumps(r['key']),json.dumps(r['participant']),json.dumps(r['matched']),vector(bykey[r['key']]['values']),str(r['.cv_fold']),repr(r['eye_sim'])])+')' for r in actual['normal']['rows'])+'\n  )\n'
    scala+='  val references: Vector[(String,Vector[Double])] = Vector('+','.join('('+json.dumps(k)+','+vector(v)+')' for k,v in refs.items())+')\n'
    scala+='  val folds: Vector[(Int,Int,Int,Int)] = Vector('+','.join('('+','.join(str(f[k]) for k in ['fold','train_source_n','eval_source_n','dropped_overlap_train_n'])+')' for f in actual['normal']['metadata']['folds'])+')\n// format: on\n'
    out=dict(eyesim_revision=parity.pinned_revision(),input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),tolerance=dict(absolute=1e-12,relative=0),reference=actual)
    for p,c in [(OUTPUT,json.dumps(out,indent=2)+'\n'),(SCALA,scala)]:
        if args.check: assert p.read_text()==c,f'Fixture drift: {p}'
        else: p.write_text(c)
    print('Template CV cosine, fold exclusions, duplicate/missing behavior and RNG side effect measured against pinned exported call.')
if __name__=='__main__': main()
