#!/usr/bin/env python3
"""Pin public eyesim OLS calls against an independent exact rational elimination oracle."""
import argparse
from fractions import Fraction as F
import hashlib
import json
from pathlib import Path
import sys
sys.dont_write_bytecode = True
import parity
HERE, ROOT = parity.HERE, parity.ROOT
INPUT = HERE / 'fixtures/cases/bd-01KYD6SYK02ZRV99MG7FX939ZS.json'
OUTPUT = HERE / 'fixtures/decomposition.json'
SCALA = ROOT / 'laws/src/test/scala/eyes4s/laws/DecompositionReference.scala'
TOLERANCE = 1e-12

def oracle(case):
    def norm(xs): return [F(x, sum(xs)) for x in xs]
    a, b, y = (norm(case[k]) for k in ('a','b','y'))
    x = [([F(1)] if case['intercept'] else []) + [u,v] for u,v in zip(a,b)]
    p = len(x[0])
    # Exact normal equations + Gauss-Jordan; independent of floating Householder QR.
    matrix = [[sum(row[i]*row[j] for row in x) for j in range(p)] +
              [sum(row[i]*value for row,value in zip(x,y))] for i in range(p)]
    for k in range(p):
        pivot = next(i for i in range(k,p) if matrix[i][k])
        matrix[k],matrix[pivot] = matrix[pivot],matrix[k]
        divisor = matrix[k][k]
        matrix[k] = [v/divisor for v in matrix[k]]
        for i in range(p):
            if i != k:
                factor = matrix[i][k]
                matrix[i] = [v-factor*w for v,w in zip(matrix[i],matrix[k])]
    beta = [row[-1] for row in matrix]
    fitted = [sum(u*v for u,v in zip(row,beta)) for row in x]
    residuals = [u-v for u,v in zip(y,fitted)]
    mean = sum(y)/len(y) if case['intercept'] else F(0)
    r2 = 1-sum(v*v for v in residuals)/sum((v-mean)**2 for v in y)
    return dict(a=a,b=b,y=y,coefficients=beta,fitted=fitted,residuals=residuals,r_squared=r2)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--eyesim',type=Path,required=True)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    cases=json.loads(INPUT.read_text())['cases']
    with parity.r_session('eyes4s-decomposition-') as session:
        lib=session.install_eyesim(args.eyesim)
        out=session.tmp/'reference.json'
        session.rscript(HERE/'decomposition.R',lib,INPUT,out)
        reference=json.loads(out.read_text())
    exact=[]
    for case, actual in zip(cases,reference['results'],strict=True):
        values=oracle(case)
        for key in ('coefficients','fitted','residuals'):
            for a,b in zip(actual[key],values[key],strict=True):
                assert abs(a-float(b)) <= TOLERANCE,(case['name'],key,a,b)
        assert abs(actual['r_squared']-float(values['r_squared'])) <= TOLERANCE
        if case['intercept']:
            assert all(abs(a-float(b)) <= TOLERANCE for a,b in zip(actual['regression_slopes'],values['coefficients'][1:],strict=True))
        exact.append({k:([str(x) for x in v] if isinstance(v,list) else str(v)) for k,v in values.items()})
    document=dict(eyesim_revision=parity.pinned_revision(),input_sha256=hashlib.sha256(INPUT.read_bytes()).hexdigest(),
                  tolerance=dict(absolute=TOLERANCE,relative=0),exact=exact,reference=reference)
    header=(ROOT/'design/src/main/scala/eyes4s/design/Template.scala').read_text().split('package ')[0]
    scala=header+'package eyes4s.laws\n\n// Generated by tools/r-parity/generate_decomposition.py. Do not hand-edit.\n// format: off\nobject DecompositionReference:\n'
    scala+='  final case class Case(name: String, a: Vector[Double], b: Vector[Double], y: Vector[Double], intercept: Boolean, coefficients: Vector[Double], fitted: Vector[Double], residuals: Vector[Double], rSquared: Double)\n'
    scala+='  val cases: Vector[Case] = Vector(\n'
    rows=[]
    for c in cases:
        v=oracle(c)
        def vec(k): return 'Vector('+','.join(repr(float(x)) for x in v[k])+')'
        rows.append('    Case('+json.dumps(c['name'])+','+','.join(vec(k) for k in ('a','b','y'))+','+str(c['intercept']).lower()+','+','.join(vec(k) for k in ('coefficients','fitted','residuals'))+','+repr(float(v['r_squared']))+')')
    scala+=',\n'.join(rows)+'\n  )\n// format: on\n'
    for path, content in {OUTPUT:json.dumps(document,indent=2)+'\n',SCALA:scala}.items():
        if args.check: assert path.read_text()==content,f'Fixture drift: {path}'
        else: path.write_text(content)
    print('Surface OLS: public lm calls agree with exact rational coefficients, fitted values, residuals and R-squared.')
if __name__ == '__main__': main()
