/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.laws

// Generated by tools/r-parity/generate_decomposition_constrained.py. Do not hand-edit.
// format: off
object ConstrainedDecompositionReference:
  /** Integer cell weights, normalized to masses, and pinned eyesim template_multireg(method = "nnls") coefficients. */
  final case class Nnls(name: String, predictors: Vector[(String, Vector[Int])], response: Vector[Int], coefficients: Vector[Double])
  /** Pinned eyesim template_regression(method = "rank") outputs and ppcor Pearson on the same layout. */
  final case class Rank(name: String, source: Vector[Int], baseline: Vector[Int], reference: Vector[Int], betaBaseline: Double, betaSource: Double, pearsonBaseline: Double, pearsonSource: Double)
  val nnls: Vector[Nnls] = Vector(
    Nnls("two-maps-interior",Vector(("a",Vector(5,1,0,2,3,1)),("b",Vector(0,2,4,1,1,4))),Vector(3,2,2,1,2,3),Vector(0.506075768406005,0.509374828173971)),
    Nnls("three-maps-boundary",Vector(("a",Vector(6,1,0,1,2,0)),("b",Vector(0,1,5,1,0,3)),("c",Vector(1,4,1,4,1,1))),Vector(7,0,1,0,3,1),Vector(0.94606542882405,0.13262599469496,0.0)),
    Nnls("exact-equal-mixture",Vector(("a",Vector(2,0,1,1,0,0)),("b",Vector(0,1,0,1,1,1))),Vector(2,1,1,2,1,1),Vector(0.5,0.5))
  )
  val rank: Vector[Rank] = Vector(
    Rank("tied-ranks",Vector(3,1,3,2,0,3,5,2),Vector(1,2,3,4,5,6,7,8),Vector(5,1,4,1,2,6,3,3),0.111239424274839,0.669801703958598,0.218729834180969,0.506990618763548),
    Rank("distinct-ranks",Vector(9,2,7,4,1,8),Vector(3,8,1,6,5,2),Vector(4,1,9,2,7,3),-0.777713771047819,-0.628618557093712,-0.938093328490015,-0.833813359769239)
  )
// format: on
