/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.studio.desktop.platform

import eyes4s.studio.app.about.{AboutBox, AboutComponent, ComponentKind}
import eyes4s.studio.core.engine.StudioBuild
import eyes4s.studio.desktop.shell.DesktopAbout

import java.io.File
import java.nio.charset.StandardCharsets.UTF_8
import java.security.MessageDigest

/** The third-party notices the desktop ships (ticket S1.14): generated by
  * the build from the resolved runtime graph, present in the application's
  * resources (so in the packaged app), naming OpenJFX, scaladock, Intaglio,
  * PDFBox and the fonts with their licences, each licence with its pinned
  * text, and listing exactly the libraries on this JVM's runtime classpath.
  */
class NoticesSuite extends munit.FunSuite:

  private val dir = "eyes4s/studio/desktop/notices/"

  private def resource(name: String): Option[Array[Byte]] =
    Option(getClass.getClassLoader.getResourceAsStream(dir + name)).map { in =>
      try in.readAllBytes
      finally in.close()
    }

  private def text(name: String): String =
    String(resource(name).getOrElse(fail(s"$dir$name is not a resource")), UTF_8)

  private lazy val components: Vector[AboutComponent] =
    DesktopAbout.componentsText.flatMap(AboutBox.parse).fold(fail(_), identity)

  private def libraries = components.filter(_.kind == ComponentKind.Library)

  test("the generated list and its text, the index and the licence texts are resources") {
    Vector(
      "components.tsv",
      "THIRD-PARTY-COMPONENTS.txt",
      "THIRD-PARTY.txt",
      "licences/SOURCES.md"
    )
      .foreach(n => assert(resource(n).nonEmpty, n))
    val listing = text("THIRD-PARTY-COMPONENTS.txt")
    components.foreach(c =>
      assert(
        listing.contains(s"${c.group}:${c.name} ${c.version}"),
        s"${c.name} not in the text"
      )
    )
    assert(listing.contains(s"Libraries (${libraries.size})"), listing.take(400))
  }

  test("OpenJFX, scaladock, Intaglio, PDFBox and the fonts are listed with their licences") {
    def licenceOf(group: String, prefix: String) =
      libraries
        .filter(c => c.group == group && c.name.startsWith(prefix))
        .map(_.licence)
        .distinct
    val openjfx = libraries.filter(_.group == "org.openjfx")
    assertEquals(
      openjfx.map(_.name).sorted,
      Vector("javafx-base", "javafx-controls", "javafx-graphics")
    )
    assert(openjfx.forall(_.version == StudioBuild.javaFxVersion), openjfx.toString)
    assertEquals(
      licenceOf("org.openjfx", "javafx-"),
      Vector("GPL-2.0-only WITH Classpath-exception-2.0")
    )
    assertEquals(licenceOf("io.github.canardlapin", "scaladock-"), Vector("Apache-2.0"))
    assertEquals(licenceOf("io.github.canardlapin", "intaglio-"), Vector("Apache-2.0"))
    assertEquals(licenceOf("org.apache.pdfbox", "pdfbox"), Vector("Apache-2.0"))
    assertEquals(
      components.filter(_.kind == ComponentKind.Bundled).map(c => (c.name, c.licence)),
      Vector(
        "IBM Plex Sans"  -> "OFL-1.1",
        "IBM Plex Mono"  -> "OFL-1.1",
        "Source Serif 4" -> "OFL-1.1"
      )
    )
  }

  test("every licence the list names has its text, pinned by SHA-256") {
    val ids = components
      .flatMap(_.licence.replace("(", " ").replace(")", " ").split("\\s+"))
      .filter(t => t.nonEmpty && !Set("AND", "OR", "WITH")(t))
      .distinct
    assert(ids.contains("GPL-2.0-only") && ids.contains("Classpath-exception-2.0"), ids)
    val sources = text("licences/SOURCES.md")
    ids.foreach { id =>
      val bytes = resource(s"licences/$id.txt").getOrElse(fail(s"no text for $id"))
      val sha   =
        MessageDigest.getInstance("SHA-256").digest(bytes).map(b => f"${b & 0xff}%02x").mkString
      assert(
        sources.contains(s"| `$id.txt` | `$sha` |"),
        s"$id.txt is not the pinned text ($sha)"
      )
    }
  }

  test("the list is the runtime classpath: every listed library's jar is on it") {
    val jars =
      sys.props("java.class.path").split(File.pathSeparator).map(p => File(p).getName).toSet
    val missing = libraries.filterNot(c =>
      jars.exists(j => j.startsWith(s"${c.name}-${c.version}") || j == s"${c.name}.jar")
    )
    assertEquals(missing.map(c => s"${c.group}:${c.name}:${c.version}"), Vector.empty)
    // And no runtime library is left out: every jar of a listed group is listed.
    val listedNames = libraries.map(_.name).toSet
    val unlisted    = jars.filter(j =>
      Vector(
        "javafx-",
        "pdfbox",
        "fontbox",
        "cats-",
        "fs2-",
        "circe-",
        "scaladock-",
        "intaglio-"
      )
        .exists(j.startsWith) && !listedNames.exists(n => j.startsWith(n))
    )
    assertEquals(unlisted, Set.empty[String])
  }
