/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import sbt._

import scala.collection.mutable

/** Source generators for the studio fixture (ticket S3.0).
  *
  * studio-core cross-builds for Scala.js and may not read files, so the mock
  * study (`docs/studio/fixture/fixture.json`) is embedded as a generated Scala
  * string, and the acceptance fixture (`fixtures/studio-golden`) as a
  * generated inventory with every trial's disposition. Both run at build time,
  * where file I/O is fine, and only when an input changes.
  */
object StudioFixture {

  /** Generate both sources into `out`, cached on the content of every input. */
  def generate(root: File, out: File, cache: File): Seq[File] = {
    val json    = root / "docs" / "studio" / "fixture" / "fixture.json"
    val golden  = root / "fixtures" / "studio-golden"
    val stimuli =
      Option((golden / "stimuli").listFiles()).toSeq.flatten.filter(_.getName.endsWith(".png"))
    val inputs = Set(json, golden / "trials.csv", golden / "fixations.csv") ++ stimuli
    val failed = selfTest
    if (failed.nonEmpty) sys.error(s"StudioFixture self-test failed: ${failed.mkString("; ")}")
    val cached = FileFunction.cached(cache, FilesInfo.hash, FilesInfo.exists) { _ =>
      Set(
        embedJson(json, out / "FixtureJson.scala"),
        goldenInventory(golden, out / "GoldenInventory.scala")
      )
    }
    // The stimulus folder's listing is an input too: a removed image changes it.
    val listing = cache / "stimuli.txt"
    val names   = stimuli.map(_.getName).sorted.mkString("\n")
    if (!listing.exists || IO.read(listing) != names) IO.write(listing, names)
    // The generator's own source is an input too: changing what it emits must
    // regenerate even when the fixture files are unchanged (found at merge of S2.1).
    val generator = root / "project" / "StudioFixture.scala"
    cached(inputs + listing + generator).toSeq.sortBy(_.getName)
  }

  /** JVM class files cap one string constant at 65,535 modified-UTF-8 bytes;
    * a chunk of this many characters, each escaped to ASCII, stays well under.
    */
  private val chunkChars = 8000

  private def literal(s: String): String = {
    val b = new StringBuilder("\"")
    s.foreach {
      case '"'                     => b.append("\\\"")
      case '\\'                    => b.append("\\\\")
      case '\n'                    => b.append("\\n")
      case '\r'                    => b.append("\\r")
      case '\t'                    => b.append("\\t")
      case c if c < ' ' || c > '~' => b.append(f"\\u${c.toInt}%04x")
      case c                       => b.append(c)
    }
    b.append('"').toString
  }

  private def chunked(text: String): String =
    text.grouped(chunkChars).map(literal).mkString(",\n    ")

  private val header =
    "// Generated by project/StudioFixture.scala. Do not edit.\n"

  /** `private[core] object FixtureJson` with the file's exact text. */
  def embedJson(source: File, out: File): File = {
    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of docs/studio/fixture/fixture.json. */
          |private[core] object FixtureJson:
          |  val text: String = Vector(
          |    ${chunked(IO.read(source, IO.utf8))}
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }

  // ---------------------------------------------------------------------------
  // fixtures/studio-golden
  // ---------------------------------------------------------------------------

  // Geometry from fixtures/studio-golden/README.md: half-open boxes in screen px.
  private val screen = (0.0, 0.0, 1920.0, 1080.0)
  private val window = (448.0, 156.0, 1472.0, 924.0)

  private def inside(box: (Double, Double, Double, Double), x: Double, y: Double): Boolean =
    box._1 <= x && x < box._3 && box._2 <= y && y < box._4

  private def finite(d: Double): Boolean = !d.isNaN && !d.isInfinite

  private def rows(file: File): (Vector[String], Vector[Vector[String]]) = {
    val lines = IO.readLines(file, IO.utf8).filter(_.nonEmpty).toVector
    // The golden CSVs quote nothing; a comma never occurs inside a field.
    (lines.head.split(",", -1).toVector, lines.tail.map(_.split(",", -1).toVector))
  }

  private final case class Rec(
      number: Int,
      ordinal: Option[Int],
      x: Double,
      y: Double,
      onset: Double,
      duration: Double,
      samples: Option[Int]
  ) {

    /** FixationCsv.read's row-level admission as the fixture README states it,
      * under the default `OffScreenPolicy.ExcludeRecord` (DESIGN_SPEC section
      * 13): a finite position off the screen admits the record; only a
      * non-finite one rejects it.
      */
    def valid: Boolean =
      ordinal.exists(_ >= 0) && samples.exists(_ > 0) && finite(x) && finite(y) && duration > 0

    def offScreen: Boolean       = !inside(screen, x, y)
    def offWindow: Boolean       = !offScreen && !inside(window, x, y)
    def micros(ms: Double): Long = math.round(ms * 1000.0)
  }

  /** `Instant.render`: exact microseconds as milliseconds. */
  private def ms(micros: Long): String = {
    val whole = micros / 1000L
    val rest  = micros % 1000L
    if (rest == 0L) s"$whole.0ms"
    else s"$whole.${f"$rest%03d".reverse.dropWhile(_ == '0').reverse}ms"
  }

  /** The trial's status and, for an overlap, eyes4s `Overlap(index, previous,
    * current)` with `Interval.render` spans. The clock is named after the key;
    * eyes4s names it after the key's digest.
    */
  private def status(key: String, recs: Vector[Rec]): Seq[String] = {
    val valid = recs.filter(_.valid)
    if (valid.isEmpty) Seq("no-fixations")
    else if (valid.size != recs.size) Seq("quarantine.rejected-records")
    else {
      val ords = valid.flatMap(_.ordinal)
      if (ords.distinct.size != ords.size) Seq("quarantine.duplicate-ordinals")
      else {
        val ordered      = valid.sortBy(_.ordinal.getOrElse(0))
        def span(r: Rec) = {
          val on = r.micros(r.onset)
          s"[${ms(on)}, ${ms(on + r.micros(r.duration))}) on fixation-trial:$key"
        }
        (1 until ordered.size).find(i =>
          ordered(i).micros(ordered(i).onset) <
            ordered(i - 1).micros(ordered(i - 1).onset + ordered(i - 1).duration)
        ) match {
          case Some(i) =>
            Seq("quarantine.overlap", i.toString, span(ordered(i - 1)), span(ordered(i)))
          case None => Seq("admitted")
        }
      }
    }
  }

  /** The ExcludeRecord rule on planted records the golden fixture lacks: a
    * finite off-screen record is admitted, counted outside the screen and not
    * outside the window, and leaves its trial admitted; a non-finite one is
    * rejected. Returns the failures.
    */
  def selfTest: Seq[String] = {
    val off       = Rec(1, Some(1), -5.0, 100.0, 0.0, 100.0, Some(50))
    val on        = Rec(2, Some(2), 900.0, 500.0, 200.0, 100.0, Some(50))
    val nonFinite = Rec(3, Some(3), Double.NaN, 500.0, 400.0, 100.0, Some(50))
    Seq(
      "an off-screen record is admitted"               -> off.valid,
      "an off-screen record is outside the screen"     -> off.offScreen,
      "an off-screen record is not outside the window" -> !off.offWindow,
      "its trial stays admitted"        -> (status("t", Vector(off, on)) == Seq("admitted")),
      "a non-finite record is rejected" -> !nonFinite.valid,
      "and quarantines its trial"       ->
        (status("t", Vector(on, nonFinite)) == Seq("quarantine.rejected-records"))
    ).collect { case (rule, false) => rule }
  }

  private def sha256(file: File): String =
    java.security.MessageDigest
      .getInstance("SHA-256")
      .digest(IO.readBytes(file))
      .map(b => f"${b & 0xff}%02x")
      .mkString

  /** `GoldenInventory`: every golden trial with its disposition, and the
    * window totals of the admitted trials.
    */
  def goldenInventory(dir: File, out: File): File = {
    val (th, trials)                              = rows(dir / "trials.csv")
    val (fh, fixes)                               = rows(dir / "fixations.csv")
    def col(h: Vector[String], name: String): Int = {
      val i = h.indexOf(name)
      require(i >= 0, s"studio-golden: no column $name in ${h.mkString(",")}")
      i
    }
    type Key = (String, String, String, String)
    def key(h: Vector[String], r: Vector[String]): Key =
      (
        r(col(h, "participant")),
        r(col(h, "phase")),
        r(col(h, "trial")),
        r(col(h, "occurrence"))
      )
    def render(k: Key)    = s"${k._1}/${k._2}/${k._3}#${k._4}"
    def int(s: String)    = scala.util.Try(s.trim.toInt).toOption
    def double(s: String) = scala.util.Try(s.trim.toDouble).getOrElse(Double.NaN)

    val byTrial = mutable.LinkedHashMap.empty[Key, Vector[Rec]]
    fixes.zipWithIndex.foreach { case (r, i) =>
      val k = key(fh, r)
      byTrial(k) = byTrial.getOrElse(k, Vector.empty) :+ Rec(
        i + 1,
        int(r(col(fh, "ordinal"))),
        double(r(col(fh, "x"))),
        double(r(col(fh, "y"))),
        double(r(col(fh, "onset_ms"))),
        double(r(col(fh, "duration_ms"))),
        int(r(col(fh, "sample_count")))
      )
    }
    val statuses = trials.map { r =>
      val k = key(th, r)
      k -> byTrial.get(k).fold(Seq("absent"))(status(render(k), _))
    }
    val admitted             = statuses.collect { case (k, Seq("admitted")) => byTrial(k) }
    val tallied              = admitted.flatten
    def micros(rs: Seq[Rec]) = rs.map(r => r.micros(r.duration)).sum

    val items   = trials.map(r => r(col(th, "item"))).distinct
    val pngs    = Option((dir / "stimuli").listFiles()).toVector.flatten.map(_.getName)
    val present = pngs.filter(_.endsWith(".png")).map(_.stripSuffix(".png")).toSet
    val missing = items.filterNot(present).sorted
    // Tab-separated: participant, phase, trial, occurrence, item, response,
    // outside-frame records (number@x@y, `|`-separated), status, operands.
    val lines = trials.zip(statuses).map { case (r, (k, s)) =>
      val offScreen = byTrial
        .getOrElse(k, Vector.empty)
        .filter(rec => rec.valid && rec.offScreen)
        .map(rec => s"${rec.number}@${rec.x}@${rec.y}")
        .mkString("|")
      (Seq(k._1, k._2, k._3, k._4, r(col(th, "item")), r(col(th, "response")), offScreen) ++ s)
        .mkString("\t")
    }
    // S3.4: each admitted trial's scanpath as data record numbers (header
    // excluded), in ordinal order. Off-screen records are admitted but kept out
    // of the scanpath under ExcludeRecord, so they have no fixation position.
    val scanpaths = statuses.collect { case (k, Seq("admitted")) =>
      val records = byTrial(k).filter(rec => rec.valid && !rec.offScreen)
      (Seq(k._1, k._2, k._3, k._4) :+
        records.sortBy(_.ordinal.getOrElse(0)).map(_.number).mkString(",")).mkString("\t")
    }

    // S2.10: each trial's display as trials.csv states it (participant, phase,
    // trial, occurrence, item, display_kind, image_file), and each stimulus
    // file's name, SHA-256 and byte length.
    val displays = trials.map(r =>
      Seq("participant", "phase", "trial", "occurrence", "item", "display_kind", "image_file")
        .map(c => r(col(th, c)))
        .mkString("\t")
    )
    val stimulusFiles = Option((dir / "stimuli").listFiles()).toVector.flatten
      .filter(_.getName.endsWith(".png"))
      .sortBy(_.getName)
      .map(f => s"${f.getName}\t${sha256(f)}\t${f.length}")

    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** fixtures/studio-golden, read at build time: every inventory trial with
          |  * its disposition, recomputed from the fixture README's statement of the
          |  * eyes4s `FixationCsv.read` rules under `OffScreenPolicy.ExcludeRecord`
          |  * (not by eyes4s), and the window totals of the admitted trials.
          |  */
          |private[core] object GoldenInventory:
          |  val sourceRecords: Int = ${fixes.size}
          |  /** SHA-256 of the exact bytes of trials.csv and fixations.csv (S2.1). */
          |  val trialsSha256: String = ${literal(sha256(dir / "trials.csv"))}
          |  val fixationsSha256: String = ${literal(sha256(dir / "fixations.csv"))}
          |  val distinctItems: Int = ${items.size}
          |  val imagesPresent: Int = ${items.count(present)}
          |  val missingImages: Vector[String] = ${missing
           .map(literal)
           .mkString("Vector(", ", ", ")")}
          |  val talliedTrials: Int = ${admitted.size}
          |  val talliedRecords: Int = ${tallied.size}
          |  val talliedMicros: Long = ${micros(tallied)}L
          |  val outsideScreen: Int = ${tallied.count(_.offScreen)}
          |  val outsideScreenMicros: Long = ${micros(tallied.filter(_.offScreen))}L
          |  val trialsOutsideScreen: Int = ${admitted.count(_.exists(_.offScreen))}
          |  val outsideWindow: Int = ${tallied.count(_.offWindow)}
          |  val outsideWindowMicros: Long = ${micros(tallied.filter(_.offWindow))}L
          |  val trialsOutsideWindow: Int = ${admitted.count(_.exists(_.offWindow))}
          |
          |  /** One tab-separated line per trial, in inventory order: participant,
          |    * phase, trial, occurrence, item, response, outside-frame records
          |    * (`number@x@y`, `|`-separated), then the status (`admitted`,
          |    * `absent`, `no-fixations` or a quarantine code) and its operands.
          |    */
          |  val trials: String = Vector(
          |    ${chunked(lines.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per admitted trial, in inventory order:
          |    * participant, phase, trial, occurrence, then its scanpath's
          |    * fixations.csv data records (1-based, header excluded), in ordinal
          |    * order and `,`-separated. Off-screen records are not in a scanpath.
          |    */
          |  val scanpaths: String = Vector(
          |    ${chunked(scanpaths.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per trial, in inventory order: participant,
          |    * phase, trial, occurrence, item, display_kind and image_file, exactly
          |    * as trials.csv holds them (S2.10).
          |    */
          |  val displays: String = Vector(
          |    ${chunked(displays.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per file of stimuli/, by name: the file
          |    * name, the SHA-256 of its bytes and its length in bytes (S2.10).
          |    */
          |  val stimuli: String = Vector(
          |    ${chunked(stimulusFiles.mkString("\n"))}
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }
}
