/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import sbt._

import scala.collection.mutable

/** Source generators for the studio fixture (ticket S3.0).
  *
  * studio-core cross-builds for Scala.js and may not read files, so the mock
  * study (`docs/studio/fixture/fixture.json`) is embedded as a generated Scala
  * string, and the acceptance fixture (`fixtures/studio-golden`) as a
  * generated inventory with every trial's disposition. Both run at build time,
  * where file I/O is fine, and only when an input changes.
  */
object StudioFixture {

  /** Generate both sources into `out`, cached on the content of every input. */
  def generate(root: File, out: File, cache: File): Seq[File] = {
    val json    = root / "docs" / "studio" / "fixture" / "fixture.json"
    val golden  = root / "fixtures" / "studio-golden"
    val stimuli =
      Option((golden / "stimuli").listFiles()).toSeq.flatten.filter(_.getName.endsWith(".png"))
    val inputs = Set(json, golden / "trials.csv", golden / "fixations.csv") ++ stimuli
    val failed = selfTest
    if (failed.nonEmpty) sys.error(s"StudioFixture self-test failed: ${failed.mkString("; ")}")
    val cached = FileFunction.cached(cache, FilesInfo.hash, FilesInfo.exists) { _ =>
      Set(
        embedJson(json, out / "FixtureJson.scala"),
        goldenInventory(golden, out / "GoldenInventory.scala"),
        embedFixationsCsv(golden / "fixations.csv", out / "GoldenFixationsCsv.scala")
      )
    }
    // The stimulus folder's listing is an input too: a removed image changes it.
    val listing = cache / "stimuli.txt"
    val names   = stimuli.map(_.getName).sorted.mkString("\n")
    if (!listing.exists || IO.read(listing) != names) IO.write(listing, names)
    // The generator's own source is an input too: changing what it emits must
    // regenerate even when the fixture files are unchanged (found at merge of S2.1).
    val generator = root / "project" / "StudioFixture.scala"
    cached(inputs + listing + generator).toSeq.sortBy(_.getName)
  }

  /** JVM class files cap one string constant at 65,535 modified-UTF-8 bytes;
    * a chunk of this many characters, each escaped to ASCII, stays well under.
    */
  private val chunkChars = 8000

  private def literal(s: String): String = {
    val b = new StringBuilder("\"")
    s.foreach {
      case '"'                     => b.append("\\\"")
      case '\\'                    => b.append("\\\\")
      case '\n'                    => b.append("\\n")
      case '\r'                    => b.append("\\r")
      case '\t'                    => b.append("\\t")
      case c if c < ' ' || c > '~' => b.append(f"\\u${c.toInt}%04x")
      case c                       => b.append(c)
    }
    b.append('"').toString
  }

  private def chunked(text: String): String =
    text.grouped(chunkChars).map(literal).mkString(",\n    ")

  private val header =
    "// Generated by project/StudioFixture.scala. Do not edit.\n"

  /** `private[core] object FixtureJson` with the file's exact text. */
  def embedJson(source: File, out: File): File = {
    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of docs/studio/fixture/fixture.json. */
          |private[core] object FixtureJson:
          |  val text: String = Vector(
          |    ${chunked(IO.read(source, IO.utf8))}
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }

  /** `private[core] object GoldenFixationsCsv` with the exact text of
    * fixtures/studio-golden/fixations.csv (S6.4: the source records table
    * shows each record's verbatim line).
    */
  def embedFixationsCsv(source: File, out: File): File = {
    // The fake reads one record per line and one cell per comma: a CR or a
    // quote in the file would break both, so refuse it here.
    val text = IO.read(source, IO.utf8)
    if (text.contains('\r') || text.contains('"'))
      sys.error(
        s"StudioFixture: ${source.getName} holds a CR or a quote; the fake's source " +
          "records read LF-ended lines of unquoted cells"
      )
    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of fixtures/studio-golden/fixations.csv. */
          |private[core] object GoldenFixationsCsv:
          |  val text: String = Vector(
          |    ${chunked(text)}
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }

  // ---------------------------------------------------------------------------
  // fixtures/studio-golden
  // ---------------------------------------------------------------------------

  // Geometry from fixtures/studio-golden/README.md: half-open boxes in screen px.
  private val screen = (0.0, 0.0, 1920.0, 1080.0)
  private val window = (448.0, 156.0, 1472.0, 924.0)

  private def inside(box: (Double, Double, Double, Double), x: Double, y: Double): Boolean =
    box._1 <= x && x < box._3 && box._2 <= y && y < box._4

  private def finite(d: Double): Boolean = !d.isNaN && !d.isInfinite

  private def rows(file: File): (Vector[String], Vector[Vector[String]]) =
    table(IO.readLines(file, IO.utf8))

  private def table(lines: Seq[String]): (Vector[String], Vector[Vector[String]]) = {
    val nonEmpty = lines.filter(_.nonEmpty).toVector
    // The golden CSVs quote nothing; a comma never occurs inside a field.
    (nonEmpty.head.split(",", -1).toVector, nonEmpty.tail.map(_.split(",", -1).toVector))
  }

  private final case class Rec(
      number: Int,
      ordinal: Option[Int],
      x: Double,
      y: Double,
      onset: Double,
      duration: Double,
      samples: Option[Int]
  ) {

    /** FixationCsv.read's row-level admission as the fixture README states it,
      * under the default `OffScreenPolicy.ExcludeRecord` (DESIGN_SPEC section
      * 13): a finite position off the screen admits the record; only a
      * non-finite one rejects it.
      */
    def valid: Boolean =
      ordinal.exists(_ >= 0) && samples.exists(_ > 0) && finite(x) && finite(y) && duration > 0

    // The raw x/y, while eyes4s classifies the corrected centre
    // (io FixationCsv.parseRows applies the trial's correction rule before
    // `frame.contains`). They agree only while the fixture's admission has no
    // correction rules; a correction would need to be applied here first.
    def offScreen: Boolean       = !inside(screen, x, y)
    def offWindow: Boolean       = !offScreen && !inside(window, x, y)
    def micros(ms: Double): Long = math.round(ms * 1000.0)
  }

  /** `Instant.render`: exact microseconds as milliseconds. */
  private def ms(micros: Long): String = {
    val whole = micros / 1000L
    val rest  = micros % 1000L
    if (rest == 0L) s"$whole.0ms"
    else s"$whole.${f"$rest%03d".reverse.dropWhile(_ == '0').reverse}ms"
  }

  /** The trial's status and, for an overlap, eyes4s `Overlap(index, previous,
    * current)` with `Interval.render` spans. The clock is named after the key;
    * eyes4s names it after the key's digest.
    */
  private def status(key: String, recs: Vector[Rec]): Seq[String] = {
    val valid = recs.filter(_.valid)
    if (valid.isEmpty) Seq("no-fixations")
    else if (valid.size != recs.size) Seq("quarantine.rejected-records")
    else {
      val ords = valid.flatMap(_.ordinal)
      if (ords.distinct.size != ords.size) Seq("quarantine.duplicate-ordinals")
      else {
        val ordered      = valid.sortBy(_.ordinal.getOrElse(0))
        def span(r: Rec) = {
          val on = r.micros(r.onset)
          s"[${ms(on)}, ${ms(on + r.micros(r.duration))}) on fixation-trial:$key"
        }
        (1 until ordered.size).find(i =>
          ordered(i).micros(ordered(i).onset) <
            ordered(i - 1).micros(ordered(i - 1).onset + ordered(i - 1).duration)
        ) match {
          case Some(i) =>
            Seq("quarantine.overlap", i.toString, span(ordered(i - 1)), span(ordered(i)))
          case None => Seq("admitted")
        }
      }
    }
  }

  /** The ExcludeRecord rule on planted records the golden fixture lacks: a
    * finite off-screen record is admitted, counted outside the screen and not
    * outside the window, and leaves its trial admitted; a non-finite one is
    * rejected. Returns the failures.
    */
  def selfTest: Seq[String] = {
    val off       = Rec(1, Some(1), -5.0, 100.0, 0.0, 100.0, Some(50))
    val on        = Rec(2, Some(2), 900.0, 500.0, 200.0, 100.0, Some(50))
    val nonFinite = Rec(3, Some(3), Double.NaN, 500.0, 400.0, 100.0, Some(50))
    Seq(
      "an off-screen record is admitted"               -> off.valid,
      "an off-screen record is outside the screen"     -> off.offScreen,
      "an off-screen record is not outside the window" -> !off.offWindow,
      "its trial stays admitted"        -> (status("t", Vector(off, on)) == Seq("admitted")),
      "a non-finite record is rejected" -> !nonFinite.valid,
      "and quarantines its trial"       ->
        (status("t", Vector(on, nonFinite)) == Seq("quarantine.rejected-records"))
    ).collect { case (rule, false) => rule }
  }

  private def sha256(file: File): String =
    java.security.MessageDigest
      .getInstance("SHA-256")
      .digest(IO.readBytes(file))
      .map(b => f"${b & 0xff}%02x")
      .mkString

  private type Key = (String, String, String, String)

  private def col(h: Vector[String], name: String): Int = {
    val i = h.indexOf(name)
    require(i >= 0, s"studio-golden: no column $name in ${h.mkString(",")}")
    i
  }

  private def key(h: Vector[String], r: Vector[String]): Key =
    (
      r(col(h, "participant")),
      r(col(h, "phase")),
      r(col(h, "trial")),
      r(col(h, "occurrence"))
    )

  private def render(k: Key): String = s"${k._1}/${k._2}/${k._3}#${k._4}"

  /** fixations.csv's records by trial, in file order, numbered from 1 in file
    * order (header excluded).
    */
  private def recordsByTrial(
      fh: Vector[String],
      fixes: Vector[Vector[String]]
  ): mutable.LinkedHashMap[Key, Vector[Rec]] = {
    def int(s: String)    = scala.util.Try(s.trim.toInt).toOption
    def double(s: String) = scala.util.Try(s.trim.toDouble).getOrElse(Double.NaN)
    val byTrial           = mutable.LinkedHashMap.empty[Key, Vector[Rec]]
    fixes.zipWithIndex.foreach { case (r, i) =>
      val k = key(fh, r)
      byTrial(k) = byTrial.getOrElse(k, Vector.empty) :+ Rec(
        i + 1,
        int(r(col(fh, "ordinal"))),
        double(r(col(fh, "x"))),
        double(r(col(fh, "y"))),
        double(r(col(fh, "onset_ms"))),
        double(r(col(fh, "duration_ms"))),
        int(r(col(fh, "sample_count")))
      )
    }
    byTrial
  }

  /** The marker of a scanpath record whose position is off the screen. */
  val OutsideScreenMark: String = ":outside-screen"

  /** S3.4: one admitted trial's scanpath line: participant, phase, trial,
    * occurrence, then every record of the trial in ordinal order (so a
    * record's index is its eyes4s `ScanpathPosition`), `,`-separated. Under
    * `ExcludeRecord` eyes4s admits an off-screen record into the scanpath and
    * places it `OutsideScreen`; it keeps its position and is written with
    * [[OutsideScreenMark]]. An admitted trial has only valid records.
    */
  private def scanpathLine(k: Key, records: Vector[Rec]): String =
    (Seq(k._1, k._2, k._3, k._4) :+
      records
        .sortBy(_.ordinal.getOrElse(0))
        .map(r => if (r.offScreen) s"${r.number}$OutsideScreenMark" else r.number.toString)
        .mkString(",")).mkString("\t")

  /** S6.2: one admitted trial's fixations, in ordinal order, each
    * `record@x@y@onset@duration`.
    */
  private def fixationLine(k: Key, records: Vector[Rec]): String =
    (Seq(k._1, k._2, k._3, k._4) :+
      records
        .sortBy(_.ordinal.getOrElse(0))
        .map(r => s"${r.number}@${r.x}@${r.y}@${r.onset}@${r.duration}")
        .mkString(",")).mkString("\t")

  /** `GoldenInventory`: every golden trial with its disposition, and the
    * window totals of the admitted trials.
    */
  def goldenInventory(dir: File, out: File): File = {
    val (th, trials) = rows(dir / "trials.csv")
    val (fh, fixes)  = rows(dir / "fixations.csv")
    val byTrial      = recordsByTrial(fh, fixes)
    val statuses     = trials.map { r =>
      val k = key(th, r)
      k -> byTrial.get(k).fold(Seq("absent"))(status(render(k), _))
    }
    val admitted             = statuses.collect { case (k, Seq("admitted")) => byTrial(k) }
    val tallied              = admitted.flatten
    def micros(rs: Seq[Rec]) = rs.map(r => r.micros(r.duration)).sum

    val items   = trials.map(r => r(col(th, "item"))).distinct
    val pngs    = Option((dir / "stimuli").listFiles()).toVector.flatten.map(_.getName)
    val present = pngs.filter(_.endsWith(".png")).map(_.stripSuffix(".png")).toSet
    val missing = items.filterNot(present).sorted
    // Tab-separated: participant, phase, trial, occurrence, item, response,
    // outside-frame records (number@x@y, `|`-separated), status, operands.
    val lines = trials.zip(statuses).map { case (r, (k, s)) =>
      val offScreen = byTrial
        .getOrElse(k, Vector.empty)
        .filter(rec => rec.valid && rec.offScreen)
        .map(rec => s"${rec.number}@${rec.x}@${rec.y}")
        .mkString("|")
      (Seq(k._1, k._2, k._3, k._4, r(col(th, "item")), r(col(th, "response")), offScreen) ++ s)
        .mkString("\t")
    }
    // S3.4: each admitted trial's scanpath as data record numbers (header
    // excluded), in ordinal order, off-screen records included and marked.
    val scanpaths = statuses.collect { case (k, Seq("admitted")) =>
      scanpathLine(k, byTrial(k))
    }
    // S6.2: each admitted trial's fixations in scanpath (ordinal) order, as
    // fixations.csv states them: record, x, y, onset and duration.
    val fixationLines = statuses.collect { case (k, Seq("admitted")) =>
      fixationLine(k, byTrial(k))
    }

    // S2.10: each trial's display as trials.csv states it (participant, phase,
    // trial, occurrence, item, display_kind, image_file), and each stimulus
    // file's name, SHA-256 and byte length.
    val displays = trials.map(r =>
      Seq("participant", "phase", "trial", "occurrence", "item", "display_kind", "image_file")
        .map(c => r(col(th, c)))
        .mkString("\t")
    )
    val stimulusFiles = Option((dir / "stimuli").listFiles()).toVector.flatten
      .filter(_.getName.endsWith(".png"))
      .sortBy(_.getName)
      .map(f => s"${f.getName}\t${sha256(f)}\t${f.length}")

    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** fixtures/studio-golden, read at build time: every inventory trial with
          |  * its disposition, recomputed from the fixture README's statement of the
          |  * eyes4s `FixationCsv.read` rules under `OffScreenPolicy.ExcludeRecord`
          |  * (not by eyes4s), and the window totals of the admitted trials.
          |  */
          |private[core] object GoldenInventory:
          |  val sourceRecords: Int = ${fixes.size}
          |  /** SHA-256 of the exact bytes of trials.csv and fixations.csv (S2.1). */
          |  val trialsSha256: String = ${literal(sha256(dir / "trials.csv"))}
          |  val fixationsSha256: String = ${literal(sha256(dir / "fixations.csv"))}
          |  val distinctItems: Int = ${items.size}
          |  val imagesPresent: Int = ${items.count(present)}
          |  val missingImages: Vector[String] = ${missing
           .map(literal)
           .mkString("Vector(", ", ", ")")}
          |  val talliedTrials: Int = ${admitted.size}
          |  val talliedRecords: Int = ${tallied.size}
          |  val talliedMicros: Long = ${micros(tallied)}L
          |  val outsideScreen: Int = ${tallied.count(_.offScreen)}
          |  val outsideScreenMicros: Long = ${micros(tallied.filter(_.offScreen))}L
          |  val trialsOutsideScreen: Int = ${admitted.count(_.exists(_.offScreen))}
          |  val outsideWindow: Int = ${tallied.count(_.offWindow)}
          |  val outsideWindowMicros: Long = ${micros(tallied.filter(_.offWindow))}L
          |  val trialsOutsideWindow: Int = ${admitted.count(_.exists(_.offWindow))}
          |
          |  /** One tab-separated line per trial, in inventory order: participant,
          |    * phase, trial, occurrence, item, response, outside-frame records
          |    * (`number@x@y`, `|`-separated), then the status (`admitted`,
          |    * `absent`, `no-fixations` or a quarantine code) and its operands.
          |    */
          |  val trials: String = Vector(
          |    ${chunked(lines.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per admitted trial, in inventory order:
          |    * participant, phase, trial, occurrence, then its scanpath's
          |    * fixations.csv data records (1-based, header excluded), in ordinal
          |    * order and `,`-separated: a record's index is its eyes4s
          |    * `ScanpathPosition`. An off-screen record stays in the scanpath
          |    * (eyes4s places it `OutsideScreen`) and is written `n$OutsideScreenMark`.
          |    */
          |  val scanpaths: String = Vector(
          |    ${chunked(scanpaths.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per admitted trial, in inventory order:
          |    * participant, phase, trial, occurrence, then its fixations in
          |    * scanpath (ordinal) order, `,`-separated, each
          |    * `record@x@y@onset_ms@duration_ms` as fixations.csv states them
          |    * (S6.2). A fixation's index in the line is its scanpath position.
          |    */
          |  val fixations: String = Vector(
          |    ${chunked(fixationLines.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per trial, in inventory order: participant,
          |    * phase, trial, occurrence, item, display_kind and image_file, exactly
          |    * as trials.csv holds them (S2.10).
          |    */
          |  val displays: String = Vector(
          |    ${chunked(displays.mkString("\n"))}
          |  ).mkString
          |
          |  /** One tab-separated line per file of stimuli/, by name: the file
          |    * name, the SHA-256 of its bytes and its length in bytes (S2.10).
          |    */
          |  val stimuli: String = Vector(
          |    ${chunked(stimulusFiles.mkString("\n"))}
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }

  // ---------------------------------------------------------------------------
  // Planted scanpaths (test scope)
  // ---------------------------------------------------------------------------

  /** Records the golden fixture lacks, in its fixations.csv layout: in P90
    * enc_01 two off-screen records sit between on-screen ones (record 3,
    * ordinal 2, left of the screen; record 4, ordinal 4, past its corner) and
    * one record (2) is out of ordinal order in the file; in P90 enc_02 record
    * 7 lies on the screen's excluded right edge (x = 1920, half-open).
    */
  val plantedFixations: String =
    Seq(
      "participant,phase,trial,occurrence,ordinal,x,y,onset_ms,duration_ms,sample_count",
      "P90,Encoding,enc_01,1,1,900.0,500.0,0,100,50",
      "P90,Encoding,enc_01,1,3,1000.0,600.0,400,100,50",
      "P90,Encoding,enc_01,1,2,-5.0,100.0,200,100,50",
      "P90,Encoding,enc_01,1,4,1950.5,1100.0,600,100,50",
      "P90,Encoding,enc_01,1,5,1471.9,923.9,800,100,50",
      "P90,Encoding,enc_02,1,1,300.0,500.0,0,100,50",
      "P90,Encoding,enc_02,1,2,1920.0,500.0,200,100,50",
      "P90,Encoding,enc_02,1,3,700.0,400.0,400,100,50"
    ).mkString("", "\n", "\n")

  /** `PlantedScanpaths` (test scope): [[plantedFixations]] and the scanpath
    * lines this generator writes for them, through the code that writes
    * `GoldenInventory.scanpaths`, so a test can hold them against eyes4s's
    * own admission. Written only when its text changes.
    */
  def plantedScanpaths(out: File): Seq[File] = {
    val (fh, fixes) = table(plantedFixations.split("\n").toSeq)
    val byTrial     = recordsByTrial(fh, fixes)
    val lines       = byTrial.toVector.map { case (k, recs) =>
      val s = status(render(k), recs)
      require(s == Seq("admitted"), s"planted trial ${render(k)} is not admitted: $s")
      scanpathLine(k, recs)
    }
    val text =
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** project/StudioFixture.scala's planted records and the scanpath
          |  * lines it writes for them, in the format of `GoldenInventory.scanpaths`.
          |  */
          |object PlantedScanpaths:
          |  val fixationsCsv: String = ${literal(plantedFixations)}
          |  val scanpaths: String = ${literal(lines.mkString("\n"))}
          |""".stripMargin
    if (!out.exists || IO.read(out, IO.utf8) != text) IO.write(out, text, IO.utf8)
    Seq(out)
  }

  /** `GoldenCsv` (test scope, S5.4): the exact text of fixtures/studio-golden's
    * trials.csv and fixations.csv, so a JVM test can admit them with eyes4s
    * under the story's recorded mappings without reading files. Written only
    * when its text changes.
    */
  /** `object GoldenScores` with the exact text of
    * fixtures/studio-golden/SCORES.json (S0.7b), against which the real
    * backend's results are checked (S3.7 slice 5).
    */
  def goldenScores(root: File, out: File): Seq[File] = {
    val text =
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of fixtures/studio-golden/SCORES.json. */
          |object GoldenScores:
          |  val text: String = Vector(
          |    ${chunked(IO.read(root / "fixtures" / "studio-golden" / "SCORES.json", IO.utf8))}
          |  ).mkString
          |""".stripMargin
    if (!out.exists || IO.read(out, IO.utf8) != text) IO.write(out, text, IO.utf8)
    Seq(out)
  }

  def goldenCsv(root: File, out: File): Seq[File] = {
    val golden = root / "fixtures" / "studio-golden"
    val text   =
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of fixtures/studio-golden/{trials,fixations}.csv. */
          |object GoldenCsv:
          |  val trials: String = Vector(
          |    ${chunked(IO.read(golden / "trials.csv", IO.utf8))}
          |  ).mkString
          |  val fixations: String = Vector(
          |    ${chunked(IO.read(golden / "fixations.csv", IO.utf8))}
          |  ).mkString
          |""".stripMargin
    if (!out.exists || IO.read(out, IO.utf8) != text) IO.write(out, text, IO.utf8)
    Seq(out)
  }
}
