/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.File
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.Files

/** Eyes Studio's third-party notices (ticket S1.14), generated from the
  * resolved studio-desktop runtime graph and the reviewed licence table
  * `studio/desktop/licences.tsv`, never written by hand.
  *
  * The table has one row per rule, tab-separated:
  *
  * {{{
  * dependency  <group>  <artifact>       *          <SPDX expression>  <copyright>
  * bundled     <kind>   <name>           <version>  <SPDX expression>  <copyright>
  * }}}
  *
  * A dependency rule names one artifact exactly (no glob), so a new
  * artifact of a known group needs a reviewed row. A bundled row names a file
  * Studio ships that no resolver sees (the fonts). Every SPDX licence id an
  * expression names must have its text in `notices/licences/<id>.txt`.
  */
object StudioNotices {

  final case class Module(group: String, name: String, version: String) {
    def coordinates: String = s"$group:$name"
  }

  final case class Rule(
      kind: String,
      group: String,
      pattern: String,
      version: String,
      licence: String,
      copyright: String
  ) {
    def matches(m: Module): Boolean =
      kind == "dependency" && group == m.group && pattern == m.name
  }

  /** One component the notices list: a resolved module or a bundled file. */
  final case class Component(
      kind: String,
      group: String,
      name: String,
      version: String,
      licence: String,
      copyright: String
  )

  /** The table's rules, or why a line is not one. */
  def parse(text: String): Either[String, Vector[Rule]] = {
    val rows = text.linesIterator.zipWithIndex
      .map { case (l, i) => (l, i + 1) }
      .filterNot { case (l, _) => l.trim.isEmpty || l.trim.startsWith("#") }
      .toVector
    val parsed = rows.map { case (line, n) =>
      line.split("\t", -1).toVector.map(_.trim) match {
        case Vector("dependency", _, p, _, _, _) if p.contains("*") =>
          Left(s"licences.tsv line $n names artifacts by a glob ($p); name each one")
        case Vector(kind, g, p, v, l, c)
            if Set("dependency", "bundled")(kind) && Seq(g, p, v, l, c).forall(_.nonEmpty) =>
          Right(Rule(kind, g, p, v, l, c))
        case other => Left(s"licences.tsv line $n is not a rule: ${other.mkString(" | ")}")
      }
    }
    parsed.collectFirst { case Left(e) => e }.toLeft(parsed.collect { case Right(r) => r })
  }

  /** The SPDX licence ids an expression names (`A AND (B OR C WITH D)`). */
  def licenceIds(expression: String): Vector[String] =
    expression
      .replace("(", " ")
      .replace(")", " ")
      .split("\\s+")
      .toVector
      .filter(t => t.nonEmpty && !Set("AND", "OR", "WITH")(t))
      .distinct

  /** Every resolved module with its rule, bundled files, and the modules no
    * rule covers.
    */
  def components(
      modules: Seq[Module],
      rules: Vector[Rule]
  ): (Vector[Component], Vector[Module]) = {
    val resolved = modules.distinct.sortBy(m => (m.group, m.name)).toVector
    val matched  = resolved.map(m => m -> rules.find(_.matches(m)))
    val found    = matched.collect { case (m, Some(r)) =>
      Component("dependency", m.group, m.name, m.version, r.licence, r.copyright)
    }
    val bundled = rules
      .filter(_.kind == "bundled")
      .map(r => Component("bundled", r.group, r.pattern, r.version, r.licence, r.copyright))
    (found ++ bundled, matched.collect { case (m, None) => m })
  }

  /** `components.tsv`: kind, group, name, version, licence, copyright. */
  def tsv(cs: Vector[Component]): String =
    cs.map(c => Seq(c.kind, c.group, c.name, c.version, c.licence, c.copyright).mkString("\t"))
      .mkString("", "\n", "\n")

  /** `THIRD-PARTY-COMPONENTS.txt`: the human-readable list. */
  def text(cs: Vector[Component]): String = {
    def line(c: Component) =
      s"${c.group}:${c.name} ${c.version}\n  Licence: ${c.licence}\n  Copyright: ${c.copyright}"
    val deps    = cs.filter(_.kind == "dependency")
    val bundled = cs.filter(_.kind == "bundled")
    (Seq(
      "Eyes Studio: third-party components (generated by the sbt build, S1.14)",
      "",
      "Every library on the studio-desktop runtime classpath and every bundled",
      "file, with its licence (an SPDX expression) and copyright holder. The",
      "licence texts are in licences/<SPDX id>.txt beside this file; libraries'",
      "own LICENSE and NOTICE files, where they ship them, are beside it too.",
      "",
      s"Libraries (${deps.size})",
      ""
    ) ++ deps.map(line) ++ Seq("", s"Bundled files (${bundled.size})", "") ++ bundled.map(line))
      .mkString("", "\n", "\n")
  }

  /** Writes both files into `dir`, only when their text changes. */
  def write(dir: File, cs: Vector[Component]): Seq[File] = {
    Files.createDirectories(dir.toPath)
    Seq("components.tsv" -> tsv(cs), "THIRD-PARTY-COMPONENTS.txt" -> text(cs)).map {
      case (name, content) =>
        val f = new File(dir, name)
        if (!f.exists || new String(Files.readAllBytes(f.toPath), UTF_8) != content)
          Files.write(f.toPath, content.getBytes(UTF_8))
        f
    }
  }

  /** What the check reports: modules without a rule, licence ids without a
    * text, and rules that match nothing (stale or pre-declared).
    */
  final case class Findings(
      unlicensed: Vector[Module],
      missingTexts: Vector[String],
      unused: Vector[Rule],
      staleCopies: Vector[String]
  )

  private val Copy = "(.+)-(\\d[^-]*)-(LICENSE|NOTICE)\\.txt".r

  /** Library LICENSE/NOTICE copies named `<artifact>-<version>-…txt` whose
    * artifact is not resolved at that version: a bump left them stale.
    */
  def staleCopies(files: Seq[String], modules: Seq[Module]): Vector[String] =
    files.sorted.toVector.collect {
      case f @ Copy(artifact, version, _)
          if !modules.exists(m => m.name == artifact && m.version == version) =>
        val resolved = modules.filter(_.name == artifact).map(_.version).distinct
        if (resolved.isEmpty) s"$f: $artifact is not resolved"
        else s"$f: $artifact resolves at ${resolved.mkString(", ")}"
    }

  def check(
      modules: Seq[Module],
      rules: Vector[Rule],
      texts: Set[String],
      copies: Seq[String]
  ): Findings = {
    val (cs, missing) = components(modules, rules)
    val ids           = cs.flatMap(c => licenceIds(c.licence)).distinct.sorted
    val unused        = rules.filter(r => r.kind == "dependency" && !modules.exists(r.matches))
    Findings(missing, ids.filterNot(texts), unused, staleCopies(copies, modules))
  }

  /** The check's self-test: a planted module without a rule, and a licence
    * without a text, are found; a covered graph passes.
    */
  def selfTest: Vector[String] = {
    val rules = Vector(Rule("dependency", "org.example", "lib-a", "*", "MIT", "Example"))
    val ok    =
      check(
        Seq(Module("org.example", "lib-a", "1")),
        rules,
        Set("MIT"),
        Seq("lib-a-1-LICENSE.txt")
      )
    val bad = check(
      Seq(
        Module("org.example", "lib-a", "1"),
        Module("org.example", "lib-b", "1"),
        Module("org.other", "x", "2")
      ),
      rules,
      Set.empty,
      Seq("lib-a-0.9-NOTICE.txt")
    )
    def unless(ok: Boolean, problem: String) = if (ok) None else Some(problem)
    Vector(
      unless(
        ok.unlicensed.isEmpty && ok.missingTexts.isEmpty && ok.staleCopies.isEmpty,
        "a covered graph fails"
      ),
      unless(
        bad.unlicensed == Vector(
          Module("org.example", "lib-b", "1"),
          Module("org.other", "x", "2")
        ),
        "a module without a rule (even of a known group) is not found"
      ),
      unless(bad.staleCopies.size == 1, "a stale LICENSE/NOTICE copy is not found"),
      unless(
        parse("dependency\torg.example\tlib-*\t*\tMIT\tExample").isLeft,
        "a glob rule is accepted"
      ),
      unless(bad.missingTexts == Vector("MIT"), "a licence without a text is not found"),
      unless(
        licenceIds("MIT AND (EPL-1.0 OR LGPL-2.1-only)") == Vector(
          "MIT",
          "EPL-1.0",
          "LGPL-2.1-only"
        ),
        "licence expressions are not split into ids"
      )
    ).flatten
  }
}
