/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import sbt._

import scala.collection.mutable

/** Source generators for the studio fixture (ticket S3.0).
  *
  * studio-core cross-builds for Scala.js and may not read files, so the mock
  * study (`docs/studio/fixture/fixture.json`) is embedded as a generated Scala
  * string, and the acceptance fixture's CSV tallies (`fixtures/studio-golden`)
  * as a generated test object. Both run at build time, where file I/O is fine.
  */
object StudioFixture {

  /** JVM class files cap one string constant at 65,535 modified-UTF-8 bytes;
    * a chunk of this many characters, each escaped to ASCII, stays well under.
    */
  private val chunkChars = 8000

  private def literal(s: String): String = {
    val b = new StringBuilder("\"")
    s.foreach {
      case '"'                     => b.append("\\\"")
      case '\\'                    => b.append("\\\\")
      case '\n'                    => b.append("\\n")
      case '\r'                    => b.append("\\r")
      case '\t'                    => b.append("\\t")
      case c if c < ' ' || c > '~' => b.append(f"\\u${c.toInt}%04x")
      case c                       => b.append(c)
    }
    b.append('"').toString
  }

  private val header =
    "// Generated by project/StudioFixture.scala. Do not edit.\n"

  /** `private[core] object FixtureJson` with the file's exact text. */
  def embedJson(source: File, out: File): File = {
    val text   = IO.read(source, IO.utf8)
    val chunks = text.grouped(chunkChars).map(literal).mkString(",\n    ")
    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** The exact text of docs/studio/fixture/fixture.json. */
          |private[core] object FixtureJson:
          |  val text: String = Vector(
          |    $chunks
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }

  // ---------------------------------------------------------------------------
  // fixtures/studio-golden tallies
  // ---------------------------------------------------------------------------

  // Geometry from fixtures/studio-golden/README.md: half-open boxes in screen px.
  private val screen = (0.0, 0.0, 1920.0, 1080.0)
  private val window = (448.0, 156.0, 1472.0, 924.0)

  private def inside(box: (Double, Double, Double, Double), x: Double, y: Double): Boolean =
    box._1 <= x && x < box._3 && box._2 <= y && y < box._4

  private def rows(file: File): (Vector[String], Vector[Vector[String]]) = {
    val lines = IO.readLines(file, IO.utf8).filter(_.nonEmpty).toVector
    // The golden CSVs quote nothing; a comma never occurs inside a field.
    (lines.head.split(",", -1).toVector, lines.tail.map(_.split(",", -1).toVector))
  }

  private final case class Rec(
      ordinal: Option[Int],
      x: Double,
      y: Double,
      onset: Double,
      duration: Double,
      samples: Option[Int]
  ) {
    // FixationCsv.read's row-level admission, as the fixture README states it.
    def valid: Boolean =
      ordinal.exists(_ >= 0) && samples.exists(_ > 0) && !x.isNaN && !y.isNaN &&
        !x.isInfinite && !y.isInfinite && inside(screen, x, y) && duration > 0
  }

  private def status(recs: Vector[Rec]): String = {
    val valid = recs.filter(_.valid)
    if (valid.isEmpty) "no-fixations"
    else if (valid.size != recs.size) "rejected-records"
    else {
      val ords = valid.flatMap(_.ordinal)
      if (ords.distinct.size != ords.size) "duplicate-ordinals"
      else {
        val ordered = valid.sortBy(_.ordinal.getOrElse(0))
        val overlap = ordered.zip(ordered.drop(1)).exists { case (a, b) =>
          b.onset < a.onset + a.duration
        }
        if (overlap) "overlap" else "admitted"
      }
    }
  }

  /** `GoldenInventory`: the golden CSVs and stimulus folder, tallied. */
  def goldenInventory(dir: File, out: File): File = {
    val (th, trials)                              = rows(dir / "trials.csv")
    val (fh, fixes)                               = rows(dir / "fixations.csv")
    def col(h: Vector[String], name: String): Int = {
      val i = h.indexOf(name)
      require(i >= 0, s"studio-golden: no column $name in ${h.mkString(",")}")
      i
    }
    def key(h: Vector[String], r: Vector[String]): (String, String, String, String) =
      (
        r(col(h, "participant")),
        r(col(h, "phase")),
        r(col(h, "trial")),
        r(col(h, "occurrence"))
      )
    def int(s: String)    = scala.util.Try(s.trim.toInt).toOption
    def double(s: String) = scala.util.Try(s.trim.toDouble).getOrElse(Double.NaN)

    val byTrial = mutable.LinkedHashMap.empty[(String, String, String, String), Vector[Rec]]
    var outsideRecords = 0
    val outsideTrials  = mutable.Set.empty[(String, String, String, String)]
    fixes.foreach { r =>
      val k   = key(fh, r)
      val rec = Rec(
        int(r(col(fh, "ordinal"))),
        double(r(col(fh, "x"))),
        double(r(col(fh, "y"))),
        double(r(col(fh, "onset_ms"))),
        double(r(col(fh, "duration_ms"))),
        int(r(col(fh, "sample_count")))
      )
      byTrial(k) = byTrial.getOrElse(k, Vector.empty) :+ rec
      if (inside(screen, rec.x, rec.y) && !inside(window, rec.x, rec.y)) {
        outsideRecords += 1
        outsideTrials += k
      }
    }
    val statuses = trials.map { r =>
      val k = key(th, r)
      k -> byTrial.get(k).fold("absent")(status)
    }
    val items = trials.map(r => r(col(th, "item"))).distinct
    val pngs  = (dir / "stimuli").listFiles().toVector.map(_.getName).filter(_.endsWith(".png"))
    val present = pngs.map(_.stripSuffix(".png")).toSet
    val missing = items.filterNot(present).sorted
    val lines   = trials.zip(statuses).map { case (r, ((p, ph, t, o), s)) =>
      Seq(p, ph, t, o, r(col(th, "item")), r(col(th, "response")), s).mkString(",")
    }
    val chunks = lines.mkString("\n").grouped(chunkChars).map(literal).mkString(",\n    ")

    IO.write(
      out,
      s"""|${header}package eyes4s.studio.core.fixture
          |
          |/** fixtures/studio-golden, tallied at build time: every inventory trial with
          |  * its status under the fixture README's reading of eyes4s `FixationCsv.read`.
          |  */
          |private[core] object GoldenInventory:
          |  val fixationRecords: Int = ${fixes.size}
          |  val distinctItems: Int = ${items.size}
          |  val imagesPresent: Int = ${items.count(present)}
          |  val missingImages: Vector[String] = ${missing
           .map(literal)
           .mkString("Vector(", ", ", ")")}
          |  val outsideWindowRecords: Int = $outsideRecords
          |  val outsideWindowTrials: Int = ${outsideTrials.size}
          |
          |  /** One line per trial, in inventory order:
          |    * participant,phase,trial,occurrence,item,response,status, where status is
          |    * admitted, absent or a quarantine cause slug.
          |    */
          |  val trials: String = Vector(
          |    $chunks
          |  ).mkString
          |""".stripMargin,
      IO.utf8
    )
    out
  }
}
