/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.kernel

import eyes4s.kernel.Unit2D.Px

import scala.compiletime.testing.typeCheckErrors

/** Pins entropy and map arithmetic to public eyesim output and an independent
  * oracle (baseline cases `fixation-entropy`, `density-map-mean-and-difference`,
  * `density-map-log-ratio` and `signed-maps-as-mass`).
  *
  * [[EntropyFixtures]] is generated by `tools/r-parity/generate_entropy.py`
  * from an isolated installation of the pinned eyesim revision. Its
  * `fixation_entropy.eye_density` method (`entropy_from_mass` on the cells)
  * and `Ops.eye_density` are called on hand-built `eye_density` objects over
  * the two-by-two lattice in `baseline-cases.json`, and every output is
  * recorded verbatim, including `NA`, `Inf`, `-Inf`, `NaN` and errors. The
  * oracle is exact rational arithmetic for the mean and the difference and a
  * 60-digit decimal logarithm for entropy and the log ratio away from zero.
  *
  * Three things are established here. On positive maps eyes4s and eyesim
  * agree to `1e-12`. At a zero cell the log ratio is an intended divergence:
  * eyesim returns a non-finite value and eyes4s floors both cells at `1e-12`.
  * On signed maps eyesim answers with `NA` or a finite number computed from
  * the positive cells alone, and eyes4s refuses at the type or at
  * construction; the eyesim value is pinned so that refusal is evidenced.
  */
class EntropyConformanceSuite extends munit.FunSuite:

  import EntropyFixtures.*

  private val tol = EntropyFixtures.tolerance

  /** eyesim's `x`/`y` lattice is the cell-centre lattice of this grid. */
  private val screen: Frame[Px] =
    Frame.screen("display", frameWidth.toInt, frameHeight.toInt).toOption.get
  private val grid: Grid[Px] = Grid.over(screen, nx, ny).toOption.get

  private val origin = Provenance.raw(ContentHash.empty)

  private def mass(cells: Vector[Double]): Mass[Px] =
    Surface.mass(grid, IArray.from(cells), origin).toOption.get

  private val p = mass(massP)
  private val q = mass(massQ)
  private val r = mass(massR)

  private def finite(v: RValue): Double = v match
    case RValue.Finite(x) => x
    case other            => fail(s"expected a finite eyesim value, got $other")

  private def assertCells(actual: IArray[Double], expected: Seq[Double], what: String): Unit =
    assertEquals(actual.length, expected.length, what)
    actual.indices.foreach { i =>
      assertEqualsDouble(actual(i), expected(i), tol, clue((what, i)))
    }

  private def assertEyesimCells(actual: IArray[Double], expected: Operation): Unit =
    assertCells(actual, expected.cells.map(finite), expected.name)

  // -------------------------------------------------------------------------
  // The lattice
  // -------------------------------------------------------------------------

  test("the pinned lattice is the cell-centre lattice of the 2 by 2 grid over 100 by 50") {
    assertEquals(grid.size, latticeX.length * latticeY.length)
    for
      iy <- 0 until ny
      ix <- 0 until nx
    do
      val k      = iy * nx + ix
      val centre = grid.cellCentre(k).getOrElse(fail(s"no cell $k"))
      assertEqualsDouble(centre.x, latticeX(ix), tol, clue(k))
      assertEqualsDouble(centre.y, latticeY(iy), tol, clue(k))
  }

  // -------------------------------------------------------------------------
  // Entropy on positive maps: verified equivalent
  // -------------------------------------------------------------------------

  test(
    "entropy and relative entropy on positive maps equal eyesim and the oracle in both bases"
  ) {
    val cases = Vector(
      ("p", p, eyesimEntropyP, exactEntropyP),
      ("q", q, eyesimEntropyQ, exactEntropyQ),
      ("r", r, eyesimEntropyR, exactEntropyR)
    )
    cases.foreach { case (name, m, eyesim, exact) =>
      val bits = m.entropy(LogBase.Two)
      val nats = m.entropy(LogBase.E)
      assertEquals(bits.base, LogBase.Two)
      assertEqualsDouble(bits.value, finite(eyesim.bits), tol, clue(name))
      assertEqualsDouble(bits.value, exact.bits, tol, clue(name))
      assertEqualsDouble(nats.value, finite(eyesim.nats), tol, clue(name))
      assertEqualsDouble(nats.value, exact.nats, tol, clue(name))
      // eyesim `normalize = TRUE` divides by log(cell count); so does relativeEntropy.
      assertEqualsDouble(
        m.relativeEntropy(LogBase.Two),
        finite(eyesim.relativeBits),
        tol,
        clue(name)
      )
      assertEqualsDouble(
        m.relativeEntropy(LogBase.E),
        finite(eyesim.relativeNats),
        tol,
        clue(name)
      )
      assertEqualsDouble(m.relativeEntropy(LogBase.E), exact.relativeNats, tol, clue(name))
    }
    // The selected mass really has 1.5 bits, and the uniform one is maximal.
    assertEqualsDouble(p.entropy(LogBase.Two).value, 1.5, tol)
    assertEqualsDouble(q.relativeEntropy(), 1.0, tol)
  }

  test("an unnormalised count map normalises to the entropy eyesim computes from the counts") {
    val estimate = Surface.intensity(grid, IArray.from(counts), origin).toOption.get
    val m        = estimate.normalised.toOption.get
    assertCells(m.values, massP, "counts normalised")
    assertEqualsDouble(m.entropy(LogBase.Two).value, finite(eyesimEntropyCounts.bits), tol)
    assertEqualsDouble(m.entropy(LogBase.E).value, finite(eyesimEntropyCounts.nats), tol)
    assertEqualsDouble(
      m.relativeEntropy(LogBase.E),
      finite(eyesimEntropyCounts.relativeNats),
      tol
    )
    assertEquals(eyesimEntropyCounts, eyesimEntropyP, "eyesim sum-normalises before the sum")
    // The other public entropy method, on the bare `density` class, is the same routine.
    assertEquals(eyesimEntropyPDensityClass, eyesimEntropyP)
  }

  // -------------------------------------------------------------------------
  // Map arithmetic: + and - verified equivalent, / verified where finite
  // -------------------------------------------------------------------------

  test(
    "eyesim + is the two-map mean, and Mass.mean coincides with it and with the exact rational"
  ) {
    val m = Mass.mean(Seq(p, q)).toOption.get
    assertEyesimCells(m.values, eyesimPlusPQ)
    assertCells(m.values, exactMeanPQ, "exact mean")
    assertEqualsDouble(m.sum, 1.0, tol)
    assertEquals(eyesimPlusPQ.firstClass, "eye_density_add")
  }

  test(
    "eyesim - is the cell-wise difference, and Mass.difference coincides with it, typed Signed"
  ) {
    val d: Signed[Px] = p.difference(q).toOption.get
    assertEyesimCells(d.values, eyesimMinusPQ)
    assertCells(d.values, exactDifferencePQ, "exact difference")
    assertEqualsDouble(d.sum, 0.0, tol)
    // eyesim tags the signed result as a density; eyes4s tags it Signed.
    assertEquals(eyesimMinusPQ.firstClass, "eye_density_delta")
  }

  test(
    "eyesim / is the natural-log ratio, and Mass.logRatio coincides with it where no cell is zero"
  ) {
    val rq = r.logRatio(q).toOption.get
    assertEyesimCells(rq.values, eyesimDivRQ)
    assertCells(rq.values, exactLogRatioRQ, "exact log ratio r/q")
    assert(eyesimDivRQ.cells.forall(_.isInstanceOf[RValue.Finite]))
    // p / q away from p's zero cell.
    val pq = p.logRatio(q).toOption.get
    exactLogRatioPQ.zipWithIndex.foreach {
      case (Some(expected), i) =>
        assertEqualsDouble(pq.values(i), expected, tol, clue(i))
        assertEqualsDouble(pq.values(i), finite(eyesimDivPQ.cells(i)), tol, clue(i))
      case (None, _) => ()
    }
    assertEquals(exactLogRatioPQ.count(_.isEmpty), 1, "exactly one zero cell in p")
  }

  test(
    "at a zero cell eyesim / is -Inf, Inf or NaN; eyes4s floors both cells at 1e-12 and stays finite"
  ) {
    val zero = massP.indexOf(0.0)
    assertEquals(zero, 3)
    assertEquals(exactLogRatioPQ(zero), None)
    // Pinned eyesim output: the three non-finite spellings, one per case.
    assertEquals(eyesimDivPQ.cells(zero), RValue.NegInf)
    assertEquals(eyesimDivQP.cells(zero), RValue.Inf)
    assertEquals(eyesimDivPP.cells(zero), RValue.NaN)
    // eyes4s: log(floor / q) and log(q / floor), and 0 where both are floored.
    val pq = p.logRatio(q).toOption.get
    val qp = q.logRatio(p).toOption.get
    val pp = p.logRatio(p).toOption.get
    assertEqualsDouble(pq.values(zero), math.log(floor / massQ(zero)), tol)
    assertCells(pq.values, flooredLogRatioPQ, "floored p/q")
    assertCells(qp.values, flooredLogRatioQP, "floored q/p")
    assertCells(pp.values, flooredLogRatioPP, "floored p/p")
    assert(pq.values.forall(_.isFinite) && qp.values.forall(_.isFinite))
    // The floor is a named argument, so a caller who wants eyesim's behaviour
    // at zero cells can ask for it and get the infinity explicitly.
    val raw = p.logRatio(q, floor = 0.0)
    assertEquals(raw, Left(SurfaceError.NonFiniteValue(zero, Double.NegativeInfinity)))
  }

  test("eyesim * stops with 'undefined operation'; eyes4s has no product spelling at all") {
    val product = eyesimOutcomes.find(_.operation == "product_p_q").get
    assertEquals(product.outcome, "error")
    assertEquals(product.detail, "undefined operation")
    val errs = typeCheckErrors("""
      import eyes4s.kernel.*
      import eyes4s.kernel.Unit2D.Px
      val a: Mass[Px] = ???
      val b: Mass[Px] = ???
      a * b
    """)
    assert(errs.nonEmpty, "a product of masses compiled")
  }

  test("a shifted lattice: eyesim stops in stopifnot, eyes4s returns GridMismatch") {
    val shifted = eyesimOutcomes.find(_.operation == "shifted_lattice_minus").get
    assertEquals(shifted.outcome, "error")
    assertEquals(shifted.detail, "all(e1$x == e2$x) is not TRUE")
    val other = Grid.over(Frame.screen("shifted", 100, 50).toOption.get, nx, ny).toOption.get
    val q2    = Surface.mass(other, IArray.from(massQ), origin).toOption.get
    assertEquals(p.difference(q2), Left(SurfaceError.GridMismatch(grid.id, other.id)))
    assertEquals(p.logRatio(q2), Left(SurfaceError.GridMismatch(grid.id, other.id)))
    assertEquals(Mass.mean(Seq(p, q2)), Left(SurfaceError.GridMismatch(grid.id, other.id)))
  }

  test("every eyesim operator result is still classed eye_density and carries no sigma") {
    val results =
      Vector(eyesimPlusPQ, eyesimMinusPQ, eyesimDivPQ, eyesimDivQP, eyesimDivRQ, eyesimDivPP)
    results.foreach { op =>
      assert(clue(op.firstClass).startsWith("eye_density_"), op.name)
      assert(!op.hasSigma, s"${op.name} kept a sigma")
    }
  }

  // -------------------------------------------------------------------------
  // Signed maps treated as mass: verified intentional divergence
  // -------------------------------------------------------------------------

  private def assertRefusesNegativeMass(e: EyesimEntropy, what: String): Unit =
    Vector(e.bits, e.relativeBits, e.nats, e.relativeNats).foreach {
      case RValue.Error(message) =>
        assert(message.contains("requires non-negative mass"), clue((what, message)))
      case other => fail(s"$what: expected eyesim to refuse a map with a negative cell, got $other")
    }

  test(
    "an exact difference map: eyesim refuses it because a cell is negative, whatever its total"
  ) {
    assertRefusesNegativeMass(eyesimEntropyDifferencePQ, "difference p - q")
    assertEqualsDouble(machineEpsilon, Math.ulp(1.0), 0.0)
    assertEqualsDouble(exactDifferencePQ.sum, 0.0, 0.0)
  }

  test("an exact difference map: eyes4s cannot ask, by type or by construction") {
    val errs = typeCheckErrors("""
      import eyes4s.kernel.*
      import eyes4s.kernel.Unit2D.Px
      val a: Mass[Px] = ???
      val b: Mass[Px] = ???
      a.difference(b).map(_.entropy())
    """)
    assert(errs.nonEmpty, "entropy was available on a difference map")
    val cells = IArray.from(exactDifferencePQ)
    assertEquals(Surface.mass(grid, cells, origin), Left(SurfaceError.NegativeValue(3, -0.25)))
    assertEquals(
      Surface.intensity(grid, cells, origin),
      Left(SurfaceError.NegativeValue(3, -0.25))
    )
    assert(Surface.signed(grid, cells, origin).isRight, "the same cells are a valid Signed map")
  }

  test(
    "a signed map with positive total: eyesim refuses it, as eyes4s does, rather than scoring its positive cells"
  ) {
    // Earlier eyesim revisions returned -(0.5 ln 0.5 + 0.75 ln 0.75), the
    // positive cells over the signed total, which is not the entropy of anything.
    assertRefusesNegativeMass(eyesimEntropySigned, "signed")
    assertEqualsDouble(signed.sum, 1.0, 0.0)
  }

  test(
    "a signed map with positive total: eyes4s refuses to build the Mass and names the cell"
  ) {
    val cells = IArray.from(signed)
    assertEquals(Surface.mass(grid, cells, origin), Left(SurfaceError.NegativeValue(1, -0.25)))
    assertEquals(
      Surface.intensity(grid, cells, origin),
      Left(SurfaceError.NegativeValue(1, -0.25))
    )
    val s = Surface.signed(grid, cells, origin).toOption.get
    assertEqualsDouble(s.sum, 1.0, tol)
    val errs = typeCheckErrors("""
      import eyes4s.kernel.*
      import eyes4s.kernel.Unit2D.Px
      val s: Signed[Px] = ???
      s.relativeEntropy()
    """)
    assert(errs.nonEmpty, "relative entropy was available on a signed map")
  }

  test(
    "the log-ratio map: eyesim drops the -Inf cell and reports entropy exactly 0; the NaN map is NA"
  ) {
    assertEquals(
      eyesimEntropyLogRatioPQ,
      EyesimEntropy(
        RValue.Finite(0.0),
        RValue.Finite(0.0),
        RValue.Finite(0.0),
        RValue.Finite(0.0)
      )
    )
    assertEquals(
      eyesimEntropyLogRatioPP,
      EyesimEntropy(RValue.NA, RValue.NA, RValue.NA, RValue.NA)
    )
    // The finite cells of p / q are [ln 2, 0, 0]: the single positive cell has
    // all the "mass", hence 0. eyes4s's log ratio is Signed and has no entropy.
    val pq: Signed[Px] = p.logRatio(q).toOption.get
    assert(pq.values.exists(_ < 0.0))
  }
