/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.kernel

// Generated by tools/r-parity/generate_entropy.py. Do not hand-edit.
// format: off
object EntropyFixtures:
  val eyesimRevision = "aeb098e242a99f0bf9197e767bac4c75e4483aab"
  val inputSha256 = "0b2e5036ee1c8aee63e27b3a99d08f8e4bffa3402e9ff67e4cba5bd68aef0300"
  val tolerance = 1e-12
  /** The eyes4s Mass.logRatio default floor, restated so the floored oracle names it. */
  val floor = 1e-12
  val machineEpsilon = 2.220446049250313e-16
  /** A value as R reports it. NA is not a Double, so it is a case of its own; Error is a refusal and its message. */
  enum RValue derives CanEqual:
    case Finite(value: Double)
    case NA
    case NaN
    case Inf
    case NegInf
    case Error(message: String)
  /** eyesim entropy output: base 2 raw and normalised, then base e raw and normalised. */
  final case class EyesimEntropy(bits: RValue, relativeBits: RValue, nats: RValue, relativeNats: RValue)
  final case class ExactEntropy(bits: Double, relativeBits: Double, nats: Double, relativeNats: Double)
  /** One Ops.eye_density result: its cells in Grid index order, its first class, and whether a sigma survives. */
  final case class Operation(name: String, cells: Vector[RValue], firstClass: String, hasSigma: Boolean)
  final case class Outcome(operation: String, outcome: String, detail: String)
  val frameWidth = 100.0 / 1.0
  val frameHeight = 50.0 / 1.0
  val nx = 2
  val ny = 2
  val latticeX = Vector(25.0 / 1.0, 75.0 / 1.0)
  val latticeY = Vector(25.0 / 2.0, 75.0 / 2.0)
  val massP = Vector(1.0 / 2.0, 1.0 / 4.0, 1.0 / 4.0, 0.0 / 1.0)
  val massQ = Vector(1.0 / 4.0, 1.0 / 4.0, 1.0 / 4.0, 1.0 / 4.0)
  val massR = Vector(2.0 / 5.0, 3.0 / 10.0, 1.0 / 5.0, 1.0 / 10.0)
  val counts = Vector(2.0 / 1.0, 1.0 / 1.0, 1.0 / 1.0, 0.0 / 1.0)
  val signed = Vector(1.0 / 2.0, -1.0 / 4.0, 3.0 / 4.0, 0.0 / 1.0)
  // eyesim entropy_from_mass, reached through the public eye_density entropy method.
  val eyesimEntropyP = EyesimEntropy(RValue.Finite(1.5), RValue.Finite(0.75), RValue.Finite(1.0397207708399179), RValue.Finite(0.75))
  val eyesimEntropyQ = EyesimEntropy(RValue.Finite(2.0), RValue.Finite(1.0), RValue.Finite(1.3862943611198906), RValue.Finite(1.0))
  val eyesimEntropyR = EyesimEntropy(RValue.Finite(1.8464393446710157), RValue.Finite(0.9232196723355078), RValue.Finite(1.2798542258336676), RValue.Finite(0.9232196723355078))
  val eyesimEntropyCounts = EyesimEntropy(RValue.Finite(1.5), RValue.Finite(0.75), RValue.Finite(1.0397207708399179), RValue.Finite(0.75))
  // The p cells under the bare `density` class, through the other public entropy method.
  val eyesimEntropyPDensityClass = EyesimEntropy(RValue.Finite(1.5), RValue.Finite(0.75), RValue.Finite(1.0397207708399179), RValue.Finite(0.75))
  // The same entry point on maps eyes4s refuses by type.
  val eyesimEntropySigned = EyesimEntropy(RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."))
  val eyesimEntropyDifferencePQ = EyesimEntropy(RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."), RValue.Error("the eyesim entry point requires non-negative mass, but the map has negative values (for example a difference of two densities)."))
  val eyesimEntropyLogRatioPQ = EyesimEntropy(RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(0.0))
  val eyesimEntropyLogRatioPP = EyesimEntropy(RValue.NA, RValue.NA, RValue.NA, RValue.NA)
  // 60-digit decimal oracle of the Shannon entropy of each normalised vector.
  val exactEntropyP = ExactEntropy(1.5, 0.75, 1.0397207708399179, 0.75)
  val exactEntropyQ = ExactEntropy(2.0, 1.0, 1.3862943611198906, 1.0)
  val exactEntropyR = ExactEntropy(1.8464393446710154, 0.9232196723355077, 1.2798542258336674, 0.9232196723355077)
  // Ops.eye_density at the pinned revision.
  val eyesimPlusPQ = Operation("plus_p_q", Vector(RValue.Finite(0.375), RValue.Finite(0.25), RValue.Finite(0.25), RValue.Finite(0.125)), "eye_density_add", false)
  val eyesimMinusPQ = Operation("minus_p_q", Vector(RValue.Finite(0.25), RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(-0.25)), "eye_density_delta", false)
  val eyesimDivPQ = Operation("div_p_q", Vector(RValue.Finite(0.6931471805599453), RValue.Finite(0.0), RValue.Finite(0.0), RValue.NegInf), "eye_density_div", false)
  val eyesimDivQP = Operation("div_q_p", Vector(RValue.Finite(-0.6931471805599453), RValue.Finite(0.0), RValue.Finite(0.0), RValue.Inf), "eye_density_div", false)
  val eyesimDivRQ = Operation("div_r_q", Vector(RValue.Finite(0.47000362924573563), RValue.Finite(0.1823215567939546), RValue.Finite(-0.2231435513142097), RValue.Finite(-0.916290731874155)), "eye_density_div", false)
  val eyesimDivPP = Operation("div_p_p", Vector(RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(0.0), RValue.NaN), "eye_density_div", false)
  // Exact rational mean and difference; decimal log ratio, None where a cell is zero.
  val exactMeanPQ = Vector(3.0 / 8.0, 1.0 / 4.0, 1.0 / 4.0, 1.0 / 8.0)
  val exactDifferencePQ = Vector(1.0 / 4.0, 0.0 / 1.0, 0.0 / 1.0, -1.0 / 4.0)
  val exactLogRatioRQ = Vector(0.4700036292457356, 0.18232155679395462, -0.22314355131420976, -0.9162907318741551)
  val exactLogRatioPQ = Vector(Some(0.6931471805599453), Some(0.0), Some(0.0), None)
  val exactLogRatioQP = Vector(Some(-0.6931471805599453), Some(0.0), Some(0.0), None)
  val exactLogRatioPP = Vector(Some(0.0), Some(0.0), Some(0.0), None)
  // The eyes4s floored log ratio, computed from the same rationals with both cells floored at `floor`.
  val flooredLogRatioPQ = Vector(0.6931471805599453, 0.0, 0.0, -26.244726754808656)
  val flooredLogRatioQP = Vector(-0.6931471805599453, 0.0, 0.0, 26.244726754808656)
  val flooredLogRatioPP = Vector(0.0, 0.0, 0.0, 0.0)
  // Observed failures: the product and a shifted lattice.
  val eyesimOutcomes = Vector(
    Outcome("product_p_q", "error", "undefined operation"),
    Outcome("shifted_lattice_minus", "error", "all(e1$x == e2$x) is not TRUE"),
  )
// format: on
