/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.compare

// Generated by tools/r-parity/generate_compare.py.
// format: off
object MapReference:
  final case class Case(name: String,a: Vector[Double],b: Vector[Double],expected: Vector[(String,Double)])
  val cases: Vector[Case] = Vector(
    Case("regular",Vector(0.05,0.1,0.15,0.2,0.25,0.25),Vector(0.3,0.1,0.1,0.2,0.1,0.2),Vector(("pearson",-0.35000000000000003),("spearman",-0.23483410915693106),("fisherz",-0.3654437542713962),("cosine",0.7749999999999999),("l1",0.75),("jaccard",0.6326530612244898),("dcov",0.5467003647630306))),
    Case("ties",Vector(0.0,0.2,0.2,0.6),Vector(0.6,0.2,0.2,0.0),Vector(("pearson",-0.8947368421052632),("spearman",-1.0),("fisherz",-1.4451858789480823),("cosine",0.18181818181818182),("l1",0.4),("jaccard",0.1),("dcov",0.9147320339189784))),
    Case("orthogonal",Vector(1.0,0.0,0.0,0.0),Vector(0.0,1.0,0.0,0.0),Vector(("pearson",-0.3333333333333333),("spearman",-0.3333333333333333),("fisherz",-0.34657359027997264),("cosine",0.0),("l1",0.0),("jaccard",0.0),("dcov",0.3333333333333333))),
    Case("identical",Vector(0.1,0.2,0.3,0.4),Vector(0.1,0.2,0.3,0.4),Vector(("pearson",1.0),("spearman",1.0),("fisherz",18.36840028483855),("cosine",1.0),("l1",1.0),("jaccard",1.0),("dcov",1.0)))
  )
  val orderedScales: Vector[(String,Vector[(Double,Double)])] = Vector(("pearson",Vector((2.0,1),(1.0,-1))),("spearman",Vector((2.0,1),(1.0,-1))),("fisherz",Vector((2.0,18.3684002848386),(1.0,-18.3684002848386))),("cosine",Vector((2.0,1),(1.0,0.666666666666667))),("l1",Vector((2.0,1),(1.0,0.6))),("jaccard",Vector((2.0,1),(1.0,0.5))),("dcov",Vector((2.0,1),(1.0,1))))
  val emdDiracSimilarity: Double = 0.414213562373095
  val emdSplitSimilarity: Double = 0.500000000000001
// format: on
