/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by tools/python-conformance/generate_multimatch_fixtures.py.
// Oracle: multimatch-gaze 0.1.3, grouping = false.
// Do not edit by hand.

package eyes4s.compare

private[compare] object MultiMatchPythonFixtures:

  final case class Fixation(x: Double, y: Double, durationSeconds: Double)

  final case class Expected(
      shape: Double,
      direction: Double,
      length: Double,
      position: Double,
      duration: Double
  )

  final case class Case(
      name: String,
      left: Vector[Fixation],
      right: Vector[Fixation],
      expected: Expected
  )

  val screenWidth: Int  = 1000
  val screenHeight: Int = 800

  val cases: Vector[Case] = Vector(
    Case(
      "identical",
      Vector(
        Fixation(100.0, 100.0, 0.1),
        Fixation(400.0, 120.0, 0.16),
        Fixation(430.0, 410.0, 0.12),
        Fixation(760.0, 460.0, 0.2)
      ),
      Vector(
        Fixation(100.0, 100.0, 0.1),
        Fixation(400.0, 120.0, 0.16),
        Fixation(430.0, 410.0, 0.12),
        Fixation(760.0, 460.0, 0.2)
      ),
      Expected(
        shape = 1.0,
        direction = 1.0,
        length = 1.0,
        position = 1.0,
        duration = 1.0
      )
    ),
    Case(
      "near-copy",
      Vector(
        Fixation(100.0, 100.0, 0.1),
        Fixation(400.0, 120.0, 0.16),
        Fixation(430.0, 410.0, 0.12),
        Fixation(760.0, 460.0, 0.2),
        Fixation(850.0, 700.0, 0.14)
      ),
      Vector(
        Fixation(112.0, 94.0, 0.12),
        Fixation(392.0, 135.0, 0.14),
        Fixation(445.0, 398.0, 0.18),
        Fixation(740.0, 480.0, 0.15),
        Fixation(865.0, 680.0, 0.22)
      ),
      Expected(
        shape = 0.9838180715706589,
        direction = 0.9655387871743071,
        length = 0.9829259055460986,
        position = 0.9858626151197343,
        duration = 0.7916666666666667
      )
    ),
    Case(
      "translated-shape",
      Vector(
        Fixation(80.0, 100.0, 0.1),
        Fixation(280.0, 100.0, 0.2),
        Fixation(280.0, 300.0, 0.15),
        Fixation(520.0, 360.0, 0.12)
      ),
      Vector(
        Fixation(380.0, 300.0, 0.1),
        Fixation(580.0, 300.0, 0.2),
        Fixation(580.0, 500.0, 0.15),
        Fixation(820.0, 560.0, 0.12)
      ),
      Expected(
        shape = 1.0,
        direction = 1.0,
        length = 1.0,
        position = 0.7184537468142635,
        duration = 1.0
      )
    ),
    Case(
      "unequal-length",
      Vector(
        Fixation(80.0, 80.0, 0.11),
        Fixation(230.0, 110.0, 0.17),
        Fixation(390.0, 260.0, 0.09),
        Fixation(600.0, 240.0, 0.21),
        Fixation(830.0, 500.0, 0.13)
      ),
      Vector(
        Fixation(95.0, 70.0, 0.15),
        Fixation(250.0, 125.0, 0.12),
        Fixation(610.0, 230.0, 0.18),
        Fixation(815.0, 520.0, 0.2)
      ),
      Expected(
        shape = 0.9738052216082074,
        direction = 0.9168687244349287,
        length = 0.9740960294823869,
        position = 0.9379876803529408,
        duration = 0.8035714285714286
      )
    ),
    Case(
      "direction-wrap-around",
      Vector(
        Fixation(500.0, 400.0, 0.1),
        Fixation(300.0, 405.0, 0.12),
        Fixation(120.0, 390.0, 0.14),
        Fixation(100.0, 650.0, 0.16)
      ),
      Vector(
        Fixation(500.0, 400.0, 0.11),
        Fixation(300.0, 395.0, 0.1),
        Fixation(120.0, 410.0, 0.18),
        Fixation(90.0, 640.0, 0.13)
      ),
      Expected(
        shape = 0.9882869678583546,
        direction = 0.9831516521323501,
        length = 1.0,
        position = 0.9921913119055698,
        duration = 0.8333333333333334
      )
    ),
    Case(
      "duration-only",
      Vector(
        Fixation(150.0, 150.0, 0.08),
        Fixation(350.0, 150.0, 0.12),
        Fixation(350.0, 350.0, 0.2),
        Fixation(650.0, 350.0, 0.1)
      ),
      Vector(
        Fixation(150.0, 150.0, 0.16),
        Fixation(350.0, 150.0, 0.09),
        Fixation(350.0, 350.0, 0.25),
        Fixation(650.0, 350.0, 0.2)
      ),
      Expected(
        shape = 1.0,
        direction = 1.0,
        length = 1.0,
        position = 1.0,
        duration = 0.75
      )
    )
  )

end MultiMatchPythonFixtures
