/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.core

// Generated by tools/r-parity/generate_sampling.py.
// format: off
object SamplingReference:
  final case class Case(name: String,onsets: Vector[Long],durations: Vector[Long],x: Vector[Double],y: Vector[Double],queries: Vector[Long],fast: Option[Vector[Option[(Double,Double)]]],slow: Option[Vector[Option[(Double,Double)]]])
  val cases: Vector[Case] = Vector(
    Case("ordered",Vector(100000L,200000L,500000L),Vector(50000L,30000L,10000L),Vector(0.0,4.0,10.0),Vector(1.0,3.0,5.0),Vector(-100000L,100000L,150000L,200000L,300000L,500000L,510000L,100000L),Some(Vector(None,Some((0.0,1.0)),Some((0.0,1.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((10.0,5.0)),Some((10.0,5.0)),Some((0.0,1.0)))),Some(Vector(None,Some((0.0,1.0)),Some((0.0,1.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((10.0,5.0)),Some((10.0,5.0)),Some((0.0,1.0))))),
    Case("singleton",Vector(100000L),Vector(10000L),Vector(3.0),Vector(4.0),Vector(-100000L,100000L,150000L,200000L,300000L,500000L,510000L,100000L),Some(Vector(None,Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)))),Some(Vector(None,Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0)),Some((3.0,4.0))))),
    Case("duplicate",Vector(100000L,100000L,500000L),Vector(10000L,10000L,10000L),Vector(0.0,4.0,10.0),Vector(1.0,3.0,5.0),Vector(-100000L,100000L,150000L,200000L,300000L,500000L,510000L,100000L),Some(Vector(None,Some((4.0,3.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((10.0,5.0)),Some((10.0,5.0)),Some((4.0,3.0)))),Some(Vector(None,Some((4.0,3.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((4.0,3.0)),Some((10.0,5.0)),Some((10.0,5.0)),Some((4.0,3.0))))),
    Case("empty",Vector(),Vector(),Vector(),Vector(),Vector(-100000L,100000L,150000L,200000L,300000L,500000L,510000L,100000L),None,None)
  )
// format: on
