/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.core

import eyes4s.kernel.*
import eyes4s.kernel.Unit2D.{Norm, Px}

/** Pins the basic coordinate transforms to public eyesim output and an exact
  * oracle (baseline case `basic-coordinate-transforms`).
  *
  * [[TransformFixtures]] is generated by `tools/r-parity/generate_transforms.py`
  * from an isolated installation of the pinned eyesim revision: `center`,
  * `rescale` and `normalize` are public `fixation_group` methods and their
  * outputs are recorded verbatim. The homogeneous affine, its training-only
  * solve and the held-out target have no eyesim coordinate entry point and are
  * exact rational values. eyesim's `affine_transform` and `contract_transform`
  * are fitted density-space maps, not coordinate maps; the fixture records how
  * they respond to coordinate tables and eyes4s does not implement them.
  *
  * Every eyes4s route declares its frames and units explicitly. eyesim never
  * flips an axis in these calls, so each target frame is built with the same
  * `YAxis` as the source; the test also shows that the other choice is a
  * different, visible answer rather than a silent one.
  */
class TransformConformanceSuite extends munit.FunSuite:

  import TransformFixtures.*

  private val tol   = TransformFixtures.tolerance
  private val clock = ClockId("tracker")

  private val (xMin, xMax, yMin, yMax) = bounds

  private def frameFor[U <: Unit2D](
      name: String,
      x0: Double,
      y0: Double,
      x1: Double,
      y1: Double,
      axis: YAxis = YAxis.Down
  ): Frame[U] =
    Frame.of(FrameId(name), Bounds.of[U](x0, y0, x1, y1).toOption.get, axis)

  /** eyesim fixation-group coordinates: origin top-left, `y` downward. */
  private val screen: Frame[Px] = frameFor[Px]("screen", xMin, yMin, xMax, yMax)

  private val centred =
    frameFor[Px]("centred", xMin - origin.x, yMin - origin.y, xMax - origin.x, yMax - origin.y)
  private val meanCentred = frameFor[Px](
    "mean-centred",
    xMin - meanOrigin.x,
    yMin - meanOrigin.y,
    xMax - meanOrigin.x,
    yMax - meanOrigin.y
  )
  private val scaled =
    frameFor[Px]("scaled", xMin * scale._1, yMin * scale._2, xMax * scale._1, yMax * scale._2)
  private val unit         = frameFor[Norm]("unit", 0.0, 0.0, 1.0, 1.0)
  private val affineTarget = frameFor[Px]("affine-target", -100.0, -100.0, 400.0, 300.0)

  private val centerWarp =
    Warp.affine(screen, centred, Mat3.translation(-origin.x, -origin.y)).toOption.get
  private val meanCenterWarp =
    Warp
      .affine(screen, meanCentred, Mat3.translation(-meanOrigin.x, -meanOrigin.y))
      .toOption
      .get
  private val rescaleWarp   = Warp.rescale(screen, scaled).toOption.get
  private val normalizeWarp = Warp.rescale(screen, unit).toOption.get
  private val affineMatrix  =
    Mat3.affine(affine.a, affine.b, affine.tx, affine.c, affine.d, affine.ty)
  private val affineWarp = Warp.affine(screen, affineTarget, affineMatrix).toOption.get

  private def pt(p: P): Pt[Px] = Pt[Px](p.x, p.y)

  private def assertClose[U <: Unit2D](
      got: Option[Pt[U]],
      want: P,
      label: String,
      delta: Double = tol
  ): Unit =
    got match
      case None    => fail(s"$label: the point has no image")
      case Some(q) =>
        assertEqualsDouble(q.x, want.x, delta, clue(label))
        assertEqualsDouble(q.y, want.y, delta, clue(label))

  private def far(p: P, q: P): Boolean =
    math.abs(p.x - q.x) > 1e-6 || math.abs(p.y - q.y) > 1e-6

  test(
    "the fixture is the pinned revision on non-square bounds, and the oracle agrees with eyesim"
  ) {
    assertEquals(eyesimRevision, "ecb9c496257bce51acd5330af6a5e7a8d5b84e05")
    assertNotEquals(xMax - xMin, yMax - yMin)
    Vector(
      "center"        -> (eyesimCenterSupplied, exactCenterSupplied),
      "center (mean)" -> (eyesimCenterDefault, exactCenterDefault),
      "rescale"       -> (eyesimRescale, exactRescale),
      "normalize"     -> (eyesimNormalize, exactNormalize)
    ).foreach { case (label, (r, e)) =>
      assertEquals(r.length, points.length, clue(label))
      r.zip(e).foreach { (a, b) =>
        assertEqualsDouble(a.x, b.x, tol, clue(label))
        assertEqualsDouble(a.y, b.y, tol, clue(label))
      }
    }
  }

  test("center with a supplied origin is a translation warp into a centred frame") {
    points.zip(eyesimCenterSupplied).foreach { (p, want) =>
      assertClose(centerWarp(pt(p)), want, s"center $p")
    }
    assertEquals(centerWarp.from.id, screen.id)
    assertEquals(centerWarp.to.id, centred.id)
  }

  test(
    "center without an origin translates by the mean, which eyes4s states rather than defaults"
  ) {
    assertEqualsDouble(meanOrigin.x, points.map(_.x).sum / points.length, tol)
    assertEqualsDouble(meanOrigin.y, points.map(_.y).sum / points.length, tol)
    points.zip(eyesimCenterDefault).foreach { (p, want) =>
      assertClose(meanCenterWarp(pt(p)), want, s"mean-center $p")
    }
    // The two eyesim calls are different maps, and the fixture can tell.
    assert(eyesimCenterSupplied.zip(eyesimCenterDefault).exists(far))
  }

  test(
    "rescale by per-axis factors is Warp.rescale onto the scaled frame, and an explicit scaling"
  ) {
    val explicit = Warp.affine(screen, scaled, Mat3.scaling(scale._1, scale._2)).toOption.get
    points.zip(eyesimRescale).foreach { (p, want) =>
      assertClose(rescaleWarp(pt(p)), want, s"rescale $p")
      assertClose(explicit(pt(p)), want, s"explicit scaling $p")
    }
    // A single isotropic factor would be the wrong answer on these bounds.
    val isotropic = Warp.affine(screen, scaled, Mat3.scaling(scale._1, scale._1)).toOption.get
    assert(points.zip(eyesimRescale).exists { (p, want) =>
      isotropic(pt(p)).exists(q => far(P(q.x, q.y), want))
    })
  }

  test("normalize to bounds is Warp.rescale onto the unit square with the same y-axis") {
    points.zip(eyesimNormalize).foreach { (p, want) =>
      assertClose(normalizeWarp(pt(p)), want, s"normalize $p")
    }
    // An axis flip is a different, explicit choice, not a convention to guess.
    val flipped =
      Warp.rescale(screen, frameFor[Norm]("unit-up", 0.0, 0.0, 1.0, 1.0, YAxis.Up)).toOption.get
    assert(points.zip(eyesimNormalize).exists { (p, want) =>
      flipped(pt(p)).exists(q => math.abs(q.y - want.y) > tol)
    })
    // Coordinate normalisation yields positions, not a distribution: the held-out
    // point lands at (0.7, 0.6), a pair that no one should ask to sum to one.
    val held: Option[Pt[Norm]] = normalizeWarp(pt(heldOut.source))
    assertClose(held, P(0.7, 0.6), "normalize held-out")
  }

  test(
    "the supplied affine reproduces every training pair and the held-out target; mutants miss it"
  ) {
    fitPairs.foreach { pr =>
      assertClose(affineWarp(pt(pr.source)), pr.target, s"training pair ${pr.source}")
    }
    points.zip(exactAffinePoints).foreach { (p, want) =>
      assertClose(affineWarp(pt(p)), want, s"affine $p")
    }
    assertClose(affineWarp(pt(heldOut.source)), heldOut.target, "held-out")

    val swapped = Warp
      .affine(
        screen,
        affineTarget,
        Mat3.affine(affine.b, affine.a, affine.tx, affine.d, affine.c, affine.ty)
      )
      .toOption
      .get
    val noTranslation = Warp
      .affine(
        screen,
        affineTarget,
        Mat3.affine(affine.a, affine.b, 0.0, affine.c, affine.d, 0.0)
      )
      .toOption
      .get
    assertClose(swapped(pt(heldOut.source)), mutantAxisSwapHeldOut, "axis-swap mutant")
    assertClose(
      noTranslation(pt(heldOut.source)),
      mutantNoTranslationHeldOut,
      "no-translation mutant"
    )
    assert(far(mutantAxisSwapHeldOut, heldOut.target))
    assert(far(mutantNoTranslationHeldOut, heldOut.target))
  }

  test("an affine solved from the training pairs alone maps the held-out point to its target") {
    // Three non-collinear pairs determine an affine exactly: one 3x3 solve per
    // output axis, using nothing but the kernel's own inverse. The held-out
    // pair never enters the solve, so agreement is evidence against leakage.
    val rows = Mat3(
      fitPairs(0).source.x,
      fitPairs(0).source.y,
      1.0,
      fitPairs(1).source.x,
      fitPairs(1).source.y,
      1.0,
      fitPairs(2).source.x,
      fitPairs(2).source.y,
      1.0
    )
    val inv = rows.inverse.getOrElse(fail("the training pairs are collinear"))
    def solve(t0: Double, t1: Double, t2: Double): (Double, Double, Double) =
      (
        inv.m00 * t0 + inv.m01 * t1 + inv.m02 * t2,
        inv.m10 * t0 + inv.m11 * t1 + inv.m12 * t2,
        inv.m20 * t0 + inv.m21 * t1 + inv.m22 * t2
      )
    val (a, b, tx) = solve(fitPairs(0).target.x, fitPairs(1).target.x, fitPairs(2).target.x)
    val (c, d, ty) = solve(fitPairs(0).target.y, fitPairs(1).target.y, fitPairs(2).target.y)

    val solveTol = 1e-9 // a floating-point inverse, checked against exact rationals
    assertEqualsDouble(a, exactFittedAffine.a, solveTol)
    assertEqualsDouble(b, exactFittedAffine.b, solveTol)
    assertEqualsDouble(tx, exactFittedAffine.tx, solveTol)
    assertEqualsDouble(c, exactFittedAffine.c, solveTol)
    assertEqualsDouble(d, exactFittedAffine.d, solveTol)
    assertEqualsDouble(ty, exactFittedAffine.ty, solveTol)
    assertEquals(exactFittedAffine, affine)

    val fitted = Warp.affine(screen, affineTarget, Mat3.affine(a, b, tx, c, d, ty)).toOption.get
    assertClose(fitted(pt(heldOut.source)), heldOut.target, "fitted held-out", solveTol)
  }

  test("Scanpath.warp carries every fixation through the map and changes nothing else") {
    val fixations = points.zipWithIndex.map { (p, i) =>
      Event.Fixation
        .withoutDispersion(
          Interval
            .of(clock, Instant.millis(i * 100L), Instant.millis(i * 100L + 100L))
            .toOption
            .get,
          pt(p),
          sampleCount = 100
        )
        .toOption
        .get
    }
    val path = Scanpath.of(screen, clock, IArray.from(fixations)).toOption.get

    val centredPath = path.warp(centerWarp).toOption.get
    assertEquals(centredPath.frame.id, centred.id)
    assertEquals(centredPath.n, path.n)
    assertEquals(centredPath.extent, path.extent)
    centredPath.fixations.toVector.zip(eyesimCenterSupplied).zipWithIndex.foreach {
      case ((f, want), i) =>
        assertClose(Some(f.centre), want, s"warped fixation $i")
        assertEquals(f.span, path.fixations(i).span)
        assertEquals(f.sampleCount, path.fixations(i).sampleCount)
    }

    val normPath: Scanpath[Norm] = path.warp(normalizeWarp).toOption.get
    assertEquals(normPath.frame.id, unit.id)
    normPath.fixations.toVector.zip(eyesimNormalize).zipWithIndex.foreach {
      case ((f, want), i) =>
        assertClose(Some(f.centre), want, s"normalised fixation $i")
    }

    // A warp whose source frame is not the path's frame is refused, not coerced.
    assert(centredPath.warp(normalizeWarp).isLeft)
  }

  test(
    "a perspective round trip returns the fixture points, so angular units are an explicit identity"
  ) {
    val perspective = Perspective.millimetres(600.0, 530.0, 265.0).toOption.get
    val angular     = Frame
      .angular(
        "angular",
        perspective.horizontalExtent.toDegrees,
        perspective.verticalExtent.toDegrees
      )
      .toOption
      .get
    val toDeg = Warp.tangent(screen, angular, perspective)
    val back  = toDeg.inverse.getOrElse(fail("the tangent projection is invertible"))
    points.foreach { p =>
      assertClose(toDeg(pt(p)).flatMap(back.apply), p, s"round trip $p", 1e-9)
    }
    // The projection is not the identity: degrees are a different frame.
    assert(points.exists(p => toDeg(pt(p)).exists(q => far(P(q.x, q.y), p))))
  }

  test("eyesim's fitted transforms are density-space maps that eyes4s does not implement") {
    assertEquals(
      eyesimFittedTransforms.map(_.entryPoint),
      Vector("affine_transform", "contract_transform")
    )
    eyesimFittedTransforms.foreach { outcome =>
      assert(outcome.detail.nonEmpty, clue(outcome))
      assert(Set("error", "value").contains(outcome.outcome), clue(outcome))
    }
  }
