/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.examples

// Generated by tools/r-parity/generate_reference.py. Do not hand-edit.
// format: off
object MatchedControlFixtures:
  val inputSha256 = "166519d85ee043cc56d70f8f32cee2d35d4ce7e5ca6b83a38c92675f1fc1084e"
  final case class FixationRow(participant: String, image: String, phase: String, ordinal: Int, x: Double, y: Double, onsetMicros: Long, durationMicros: Long, sampleCount: Int)
  final case class ExpectedPair(source: String, reference: String, kind: String, score: Double)
  final case class ExpectedReduction(id: String, matched: Double, control: Double, difference: Double)
  val fixations = Vector(
    FixationRow("s1", "a", "encode", 0, 0.5, 0.5, 0L, 100000L, 100),
    FixationRow("s1", "a", "encode", 1, 1.5, 0.5, 110000L, 200000L, 200),
    FixationRow("s1", "a", "encode", 2, 0.5, 1.5, 320000L, 200000L, 200),
    FixationRow("s1", "a", "encode", 3, 1.5, 1.5, 530000L, 400000L, 400),
    FixationRow("s1", "b", "encode", 0, 0.5, 0.5, 0L, 400000L, 400),
    FixationRow("s1", "b", "encode", 1, 1.5, 0.5, 410000L, 200000L, 200),
    FixationRow("s1", "b", "encode", 2, 0.5, 1.5, 620000L, 200000L, 200),
    FixationRow("s1", "b", "encode", 3, 1.5, 1.5, 830000L, 100000L, 100),
    FixationRow("s1", "c", "encode", 0, 0.5, 0.5, 0L, 200000L, 200),
    FixationRow("s1", "c", "encode", 1, 1.5, 0.5, 210000L, 400000L, 400),
    FixationRow("s1", "c", "encode", 2, 0.5, 1.5, 620000L, 100000L, 100),
    FixationRow("s1", "c", "encode", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s2", "a", "encode", 0, 0.5, 0.5, 0L, 200000L, 200),
    FixationRow("s2", "a", "encode", 1, 1.5, 0.5, 210000L, 100000L, 100),
    FixationRow("s2", "a", "encode", 2, 0.5, 1.5, 320000L, 400000L, 400),
    FixationRow("s2", "a", "encode", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s2", "b", "encode", 0, 0.5, 0.5, 0L, 100000L, 100),
    FixationRow("s2", "b", "encode", 1, 1.5, 0.5, 110000L, 400000L, 400),
    FixationRow("s2", "b", "encode", 2, 0.5, 1.5, 520000L, 200000L, 200),
    FixationRow("s2", "b", "encode", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s2", "c", "encode", 0, 0.5, 0.5, 0L, 400000L, 400),
    FixationRow("s2", "c", "encode", 1, 1.5, 0.5, 410000L, 100000L, 100),
    FixationRow("s2", "c", "encode", 2, 0.5, 1.5, 520000L, 200000L, 200),
    FixationRow("s2", "c", "encode", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s1", "a", "recall", 0, 0.5, 0.5, 0L, 100000L, 100),
    FixationRow("s1", "a", "recall", 1, 1.5, 0.5, 110000L, 200000L, 200),
    FixationRow("s1", "a", "recall", 2, 0.5, 1.5, 320000L, 200000L, 200),
    FixationRow("s1", "a", "recall", 3, 1.5, 1.5, 530000L, 400000L, 400),
    FixationRow("s1", "b", "recall", 0, 0.5, 0.5, 0L, 200000L, 200),
    FixationRow("s1", "b", "recall", 1, 1.5, 0.5, 210000L, 400000L, 400),
    FixationRow("s1", "b", "recall", 2, 0.5, 1.5, 620000L, 100000L, 100),
    FixationRow("s1", "b", "recall", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s1", "c", "recall", 0, 0.5, 0.5, 0L, 400000L, 400),
    FixationRow("s1", "c", "recall", 1, 1.5, 0.5, 410000L, 200000L, 200),
    FixationRow("s1", "c", "recall", 2, 0.5, 1.5, 620000L, 200000L, 200),
    FixationRow("s1", "c", "recall", 3, 1.5, 1.5, 830000L, 100000L, 100),
    FixationRow("s2", "a", "recall", 0, 0.5, 0.5, 0L, 400000L, 400),
    FixationRow("s2", "a", "recall", 1, 1.5, 0.5, 410000L, 100000L, 100),
    FixationRow("s2", "a", "recall", 2, 0.5, 1.5, 520000L, 200000L, 200),
    FixationRow("s2", "a", "recall", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s2", "b", "recall", 0, 0.5, 0.5, 0L, 100000L, 100),
    FixationRow("s2", "b", "recall", 1, 1.5, 0.5, 110000L, 400000L, 400),
    FixationRow("s2", "b", "recall", 2, 0.5, 1.5, 520000L, 200000L, 200),
    FixationRow("s2", "b", "recall", 3, 1.5, 1.5, 730000L, 200000L, 200),
    FixationRow("s2", "c", "recall", 0, 0.5, 0.5, 0L, 200000L, 200),
    FixationRow("s2", "c", "recall", 1, 1.5, 0.5, 210000L, 100000L, 100),
    FixationRow("s2", "c", "recall", 2, 0.5, 1.5, 320000L, 400000L, 400),
    FixationRow("s2", "c", "recall", 3, 1.5, 1.5, 730000L, 200000L, 200),
  )
  val pairs = Vector(
    ExpectedPair("s1/a/recall", "s1/a/encode", "matched", 1.0 / 1.0),
    ExpectedPair("s1/a/recall", "s1/b/encode", "control", 16.0 / 25.0),
    ExpectedPair("s1/a/recall", "s1/c/encode", "control", 4.0 / 5.0),
    ExpectedPair("s1/b/recall", "s1/a/encode", "control", 4.0 / 5.0),
    ExpectedPair("s1/b/recall", "s1/b/encode", "matched", 4.0 / 5.0),
    ExpectedPair("s1/b/recall", "s1/c/encode", "control", 1.0 / 1.0),
    ExpectedPair("s1/c/recall", "s1/a/encode", "control", 16.0 / 25.0),
    ExpectedPair("s1/c/recall", "s1/b/encode", "control", 1.0 / 1.0),
    ExpectedPair("s1/c/recall", "s1/c/encode", "matched", 4.0 / 5.0),
    ExpectedPair("s2/a/recall", "s2/a/encode", "matched", 21.0 / 25.0),
    ExpectedPair("s2/a/recall", "s2/b/encode", "control", 16.0 / 25.0),
    ExpectedPair("s2/a/recall", "s2/c/encode", "control", 1.0 / 1.0),
    ExpectedPair("s2/b/recall", "s2/a/encode", "control", 18.0 / 25.0),
    ExpectedPair("s2/b/recall", "s2/b/encode", "matched", 1.0 / 1.0),
    ExpectedPair("s2/b/recall", "s2/c/encode", "control", 16.0 / 25.0),
    ExpectedPair("s2/c/recall", "s2/a/encode", "control", 1.0 / 1.0),
    ExpectedPair("s2/c/recall", "s2/b/encode", "control", 18.0 / 25.0),
    ExpectedPair("s2/c/recall", "s2/c/encode", "matched", 21.0 / 25.0),
  )
  val reductions = Vector(
    ExpectedReduction("s1/a/recall", 1.0, 0.72, 0.28),
    ExpectedReduction("s1/b/recall", 0.8, 0.9, -0.1),
    ExpectedReduction("s1/c/recall", 0.8, 0.82, -0.02),
    ExpectedReduction("s2/a/recall", 0.84, 0.82, 0.02),
    ExpectedReduction("s2/b/recall", 1.0, 0.68, 0.32),
    ExpectedReduction("s2/c/recall", 0.84, 0.86, -0.02),
  )
  final case class Components(shape: Double, direction: Double, length: Double, position: Double, duration: Double)
  val structuredMatched = Components(9.0 / 10.0, 4.0 / 5.0, 7.0 / 10.0, 3.0 / 5.0, 1.0 / 2.0)
  val structuredControls = Vector(Components(1.0 / 5.0, 2.0 / 5.0, 3.0 / 5.0, 4.0 / 5.0, 1.0 / 1.0), Components(2.0 / 5.0, 3.0 / 5.0, 4.0 / 5.0, 1.0 / 1.0, 4.0 / 5.0))
  val structuredControlMean = Components(3.0 / 10.0, 1.0 / 2.0, 7.0 / 10.0, 9.0 / 10.0, 9.0 / 10.0)
  val structuredDifference = Components(3.0 / 5.0, 3.0 / 10.0, 0.0 / 1.0, -3.0 / 10.0, -2.0 / 5.0)
// format: on
