/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.io

// Generated by tools/r-parity/generate_admission.py. Do not hand-edit.
// format: off
object AdmissionReference:
  final case class Row(id: String, participant: String, trial: String, x: Double, y: Double, onset: Long, duration: Long)
  val rows = Vector(
    Row("valid-a", "p1", "a", 10.0, 20.0, 0L, 100L),
    Row("outside-left", "p1", "a", -1.0, 20.0, 100L, 100L),
    Row("zero-duration", "p1", "a", 30.0, 20.0, 200L, 0L),
    Row("valid-b", "p1", "b", 90.0, 40.0, 0L, 125L),
  )
  val referenceRetained = Vector("valid-a", "zero-duration", "valid-b")
  val referenceEmptyGroupError = "Tibble columns must have compatible sizes.\n* Size 2: Existing data.\n* Size 0: Column `x`.\ni Only values of size one are recycled."
// format: on
