/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.io

// Generated by tools/r-parity/generate_template.py. Do not hand-edit.
// format: off
object TemplateFitReference:
  val trainingCsv = "method,training_hash,basis,response_unit,row,fold,response,feature:template-a,feature:template-b\r\neyes4s.no-intercept-r-lm-qr/1,8a3a3b110b6bcfac,fixed-template-features/1,score,0,train-a,1.0,1.0,0.0\r\neyes4s.no-intercept-r-lm-qr/1,8a3a3b110b6bcfac,fixed-template-features/1,score,1,train-a,2.0,0.0,1.0\r\neyes4s.no-intercept-r-lm-qr/1,8a3a3b110b6bcfac,fixed-template-features/1,score,2,train-b,3.0,1.0,1.0\r\neyes4s.no-intercept-r-lm-qr/1,8a3a3b110b6bcfac,fixed-template-features/1,score,3,train-b,4.0,2.0,1.0\r\n"
  val receipt = "\"method\",\"training_hash\",\"feature\",\"coefficient\",\"rank\",\"observations\",\"backend\",\"rank_tolerance\"\r\n\"eyes4s.no-intercept-r-lm-qr/1\",\"8a3a3b110b6bcfac\",\"template-a\",\"1.0000000000000004\",2,4,\"R-4.5.1/stats-lm.fit\",\"9.9999999999999995e-08\"\r\n\"eyes4s.no-intercept-r-lm-qr/1\",\"8a3a3b110b6bcfac\",\"template-b\",\"2.0000000000000004\",2,4,\"R-4.5.1/stats-lm.fit\",\"9.9999999999999995e-08\"\r\n"
// format: on
