/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.surface

// Generated by tools/r-parity/generate_derived_entropy.py. Do not hand-edit.
// format: off
object DerivedEntropyReference:
  val eyesimRevision = "735d010911c5ec86fae430c8a0010b8107a4431c"
  val inputSha256 = "95529f30a07cba77c1b9977a66b9d7780ab8b5a471ef97da2dca6e82f2908541"
  val tolerance = 1e-12
  /** eyesim rounds each density map (zapsmall to 7 digits); the entropy of a continuous oracle of the unrounded map agrees to this. */
  val roundedMapTolerance = 1e-07
  /** A value as R reports it. NA is not a Double, so it is a case of its own; Error is a refusal and its message. */
  enum RValue derives CanEqual:
    case Finite(value: Double)
    case NA
    case NaN
    case Inf
    case NegInf
    case Error(message: String)
  /** eyesim entropy output: base 2 raw and normalised, then base e raw and normalised. */
  final case class EyesimEntropy(bits: RValue, relativeBits: RValue, nats: RValue, relativeNats: RValue)
  final case class ExactEntropy(bits: Double, relativeBits: Double, nats: Double, relativeNats: Double)
  /** eyesim aggregate = "none" output, (sigma, value) in eyesim's order, per base and normalisation. */
  final case class ScaleValues(bits: Vector[(Double, RValue)], relativeBits: Vector[(Double, RValue)], nats: Vector[(Double, RValue)], relativeNats: Vector[(Double, RValue)])
  final case class PaddedLattice(nx: Int, ny: Int, padding: Double, xMin: Double, xMax: Double, yMin: Double, yMax: Double, counts: Vector[Double], eyesim: EyesimEntropy, exact: ExactEntropy)

  // The fixation group, in the frame [0, width) x [0, height).
  val frameWidth = 60
  val frameHeight = 40
  val x = Vector(5.0, 15.0, 20.0, 33.0, 60.0, 70.0)
  val y = Vector(5.0, 8.0, 20.0, 21.0, 40.0, 12.0)
  val onsetMs = Vector(0, 200, 500, 900, 1300, 1700)
  val durationMs = Vector(100, 200, 250, 300, 150, 120)

  // method = "grid" on explicit bounds.
  val latticeNx = 3
  val latticeNy = 2
  val latticeBounds = Vector(0.0, 60.0, 0.0, 40.0)
  val clampedCounts = Vector(2.0, 0.0, 1.0, 0.0, 2.0, 1.0)
  val excludedCounts = Vector(2.0, 0.0, 0.0, 0.0, 2.0, 1.0)
  val durationCounts = Vector(300.0, 0.0, 120.0, 0.0, 550.0, 150.0)
  val outsideLattice = Vector(5)
  val eyesimGridExplicit = EyesimEntropy(RValue.Finite(1.9182958340544893), RValue.Finite(0.7420981285103055), RValue.Finite(1.3296613488547582), RValue.Finite(0.7420981285103057))
  val eyesimGridExplicitDurationWeighted = EyesimEntropy(RValue.Finite(1.9182958340544893), RValue.Finite(0.7420981285103055), RValue.Finite(1.3296613488547582), RValue.Finite(0.7420981285103057))
  val exactGridExplicit = ExactEntropy(1.9182958340544896, 0.7420981285103057, 1.3296613488547582, 0.7420981285103057)
  // eyes4s-only: the outside fixation excluded, and dwell in place of counts.
  val exactGridExcluded = ExactEntropy(1.5219280948873624, 0.5887621559162939, 1.0549201679861442, 0.5887621559162939)
  val exactGridDuration = ExactEntropy(1.7466012519246266, 0.6756775974264065, 1.2106517333340256, 0.6756775974264065)
  // eyesim's default bounds: the observed range padded by 5% of its span.
  val paddedLattices = Vector(
    PaddedLattice(4, 3, 0.05, 1.75, 73.25, 3.25, 41.75, Vector(2.0, 0.0, 0.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0), EyesimEntropy(RValue.Finite(1.9182958340544893), RValue.Finite(0.5350950905814502), RValue.Finite(1.3296613488547582), RValue.Finite(0.5350950905814502)), ExactEntropy(1.9182958340544896, 0.5350950905814502, 1.3296613488547582, 0.5350950905814502)),
    PaddedLattice(10, 10, 0.05, 1.75, 73.25, 3.25, 41.75, Vector(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0), EyesimEntropy(RValue.Finite(2.584962500721156), RValue.Finite(0.3890756251918218), RValue.Finite(1.7917594692280547), RValue.Finite(0.3890756251918217)), ExactEntropy(2.584962500721156, 0.3890756251918218, 1.791759469228055, 0.3890756251918218)),
  )
  val eyesimGridSingle = EyesimEntropy(RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(0.0), RValue.Finite(0.0))

  // method = "density": explicit sigma, bounds and output lattice.
  val sigma = 8.0
  val densityNx = 6
  val densityNy = 4
  // eyesim's own maps (eye_density with the same arguments), cell k = iy * nx + ix.
  val eyesimDensityMap = Vector(0.0647047, 0.09534181, 0.0352672, 0.00454908, 0.00107382, 0.0122897, 0.05348743, 0.13149296, 0.11724432, 0.05867965, 0.01108896, 0.03779985, 0.00525026, 0.04396303, 0.08867839, 0.06822979, 0.01825183, 0.02786388, 0.00016049, 0.0023588, 0.00582155, 0.00599804, 0.02768407, 0.08272041)
  val eyesimDensityMapDurationWeighted = Vector(0.03662115, 0.07242185, 0.034581, 0.00587123, 0.00105346, 0.00734741, 0.03422135, 0.12422109, 0.14189097, 0.08458136, 0.0147829, 0.02277902, 0.00500674, 0.05287401, 0.1180153, 0.09964258, 0.02191114, 0.01990982, 0.00019992, 0.00297382, 0.00789198, 0.00814767, 0.02130324, 0.06175099)
  val eyesimDensityX = Vector(0.0, 12.0, 24.0, 36.0, 48.0, 60.0)
  val eyesimDensityY = Vector(0.0, 13.333333333333334, 26.666666666666668, 40.0)
  val eyesimDensity = EyesimEntropy(RValue.Finite(3.9494434554639155), RValue.Finite(0.8613905685908485), RValue.Finite(2.7375455959357406), RValue.Finite(0.8613905685908484))
  val eyesimDensityDurationWeighted = EyesimEntropy(RValue.Finite(3.875200018484298), RValue.Finite(0.8451977563338366), RValue.Finite(2.6860839669182393), RValue.Finite(0.8451977563338366))
  // The continuous Gaussian at eyesim's evaluation points, unrounded.
  val continuousDensity = ExactEntropy(3.9494434048137372, 0.8613905575438273, 2.7375455608277126, 0.8613905575438273)
  val continuousDensityDurationWeighted = ExactEntropy(3.875200073884756, 0.8451977684169143, 2.6860840053189103, 0.8451977684169143)
  // The eyes4s native discrete estimate, by weighting and edge policy.
  val nativeUniformTruncate = ExactEntropy(3.922778742018685, 0.8555748801438794, 2.7190630249907404, 0.8555748801438794)
  val nativeUniformTruncateMass = Vector(0.11177953926755553, 0.11331686590444885, 0.043326018682623556, 0.00833662570244718, 0.0017557942932938694, 0.00015079159246030713, 0.05267864929393191, 0.06869796070839418, 0.06869796070839418, 0.05267864929393191, 0.01762158024981529, 0.0015712844754877911, 0.00833662570244718, 0.043326018682623556, 0.11331686590444885, 0.11177953926755553, 0.03842436728428804, 0.0034320008253824266, 0.0016699448992932551, 0.017689256313755525, 0.05114132265703858, 0.05111039811105901, 0.017590655703835723, 0.0015712844754877911)
  val nativeUniformRenormalise = ExactEntropy(3.844295975429991, 0.8384574519039866, 2.664662916607243, 0.8384574519039866)
  val nativeUniformRenormaliseMass = Vector(0.14969727026757523, 0.1369567318322119, 0.04779443480909451, 0.00790326653925255, 0.0014781948462050617, 0.00012534039026120103, 0.0697850963409004, 0.07668251876927101, 0.062496651770685425, 0.04423314409670653, 0.01465592473306751, 0.0013060768585015656, 0.00942446608827113, 0.037892285715891504, 0.09470842421969959, 0.09295572860726736, 0.031939774228940974, 0.002852734133326635, 0.0014382724649061804, 0.014741391231939262, 0.0425199001622641, 0.04248464329833284, 0.014621651736925957, 0.0013060768585015656)
  val nativeDurationTruncate = ExactEntropy(3.9435576207748113, 0.8601068427832376, 2.7334658462157466, 0.8601068427832376)
  val nativeDurationTruncateMass = Vector(0.06455143159195316, 0.08449233079960759, 0.03797220886909656, 0.009103501590734727, 0.0022498840500906636, 0.00019790983819315867, 0.031208766368757454, 0.057461248066835426, 0.07437044692413308, 0.06514146730846561, 0.022852457896654618, 0.002062267870677659, 0.006609795582710859, 0.046528962355934705, 0.1316048966824881, 0.1394299809204239, 0.04985755681022008, 0.00450440715525314, 0.001787928722343826, 0.019713807235961743, 0.05963283987827615, 0.06377832534863395, 0.022825310261876196, 0.002062267870677659)
  val nativeDurationRenormalise = ExactEntropy(3.9459308896756107, 0.8606244629165377, 2.7351108708630463, 0.8606244629165377)
  val nativeDurationRenormaliseMass = Vector(0.08881858705099449, 0.10540501876591624, 0.04395424989004659, 0.009009561667275552, 0.002022657057668312, 0.0001763695854952049, 0.04213895520225466, 0.0649920182817076, 0.07090699590326578, 0.058462172250425444, 0.02037330533262957, 0.0018378132833220143, 0.007265305808434251, 0.04278769487221171, 0.11772560583140729, 0.12429400667888012, 0.04443189971473284, 0.004014153263559657, 0.0016209903000768346, 0.017594792649436527, 0.05315141795053402, 0.05683756698131871, 0.02034104839508458, 0.0018378132833220143)
  // Default bandwidth: suggest_sigma with and without eyesim's padded display clamp.
  val eyesimDensityDefault = RValue.Finite(0.9624035442362294)
  /** The continuous oracle of that default call: sigma clamped on the padded range, padded bounds, 50 by 50, relative nats. */
  val continuousDensityDefault = 0.9624035444207601
  val eyesimSuggestedSigmaUnclamped = RValue.Finite(15.095475901179919)
  val eyesimSuggestedSigmaPadded = RValue.Finite(8.25)
  val eyesimSingleDensityDefault = RValue.NA
  val eyesimSingleDensityExplicitSigma = RValue.NA

  // eye_density with a sigma vector, requested in this order.
  val multiscaleSigmas = Vector(12.0, 6.0)
  val eyesimMultiscaleMaps = Vector(
    (12.0, Vector(0.05154418, 0.07264247, 0.05119728, 0.02141185, 0.01013106, 0.01822744, 0.05531128, 0.09721625, 0.09448406, 0.05646101, 0.02782994, 0.03458876, 0.02225693, 0.05396524, 0.07172389, 0.05550743, 0.03593405, 0.03837356, 0.00383429, 0.01219201, 0.01974526, 0.02113181, 0.03100555, 0.04328439)),
    (6.0, Vector(0.07455583, 0.10406102, 0.0204563, 0.00042365, 3.732e-05, 0.00486244, 0.04337608, 0.14555973, 0.11479035, 0.05864124, 0.0029687, 0.03505999, 0.00050062, 0.03326794, 0.09255424, 0.08363221, 0.00571254, 0.01400928, 2.15e-06, 0.0002311, 0.00075688, 0.00090921, 0.01954237, 0.1440888)),
  )
  val eyesimMultiscaleNone = ScaleValues(Vector((12.0, RValue.Finite(4.32704653210245)), (6.0, RValue.Finite(3.6186799547317117))), Vector((12.0, RValue.Finite(0.9437474202726546)), (6.0, RValue.Finite(0.7892496294489953))), Vector((12.0, RValue.Finite(2.9992801038785033)), (6.0, RValue.Finite(2.5082778079710772))), Vector((12.0, RValue.Finite(0.9437474202726549)), (6.0, RValue.Finite(0.7892496294489956))))
  val eyesimMultiscaleMean = EyesimEntropy(RValue.Finite(3.972863243417081), RValue.Finite(0.866498524860825), RValue.Finite(2.7537789559247905), RValue.Finite(0.8664985248608252))
  val eyesimMultiscaleFromGroup = EyesimEntropy(RValue.Finite(3.972863243417081), RValue.Finite(0.866498524860825), RValue.Finite(2.7537789559247905), RValue.Finite(0.8664985248608252))
  val eyesimMultiscaleFromGroupNone = ScaleValues(Vector((12.0, RValue.Finite(4.32704653210245)), (6.0, RValue.Finite(3.6186799547317117))), Vector((12.0, RValue.Finite(0.9437474202726546)), (6.0, RValue.Finite(0.7892496294489953))), Vector((12.0, RValue.Finite(2.9992801038785033)), (6.0, RValue.Finite(2.5082778079710772))), Vector((12.0, RValue.Finite(0.9437474202726549)), (6.0, RValue.Finite(0.7892496294489956))))
  val nativeMultiscale = Vector(
    (6.0, ExactEntropy(3.4982389392173543, 0.762980927034218, 2.424794457643523, 0.762980927034218)),
    (12.0, ExactEntropy(4.295249482126755, 0.9368123472004768, 2.977240068337725, 0.9368123472004768)),
  )
  val nativeMultiscaleMean = ExactEntropy(3.8967442106720545, 0.8498966371173474, 2.701017262990624, 0.8498966371173474)
  /** (sigma, weight): an eyes4s reduction eyesim does not offer. */
  val multiscaleWeights = Vector((6.0, 1.0), (12.0, 3.0))
  val nativeMultiscaleWeighted = ExactEntropy(4.095996846399404, 0.8933544921589122, 2.8391286656641745, 0.8933544921589122)

  // Supplied maps on a two-by-two lattice packaged as one multiscale object.
  val suppliedWidth = 100.0
  val suppliedHeight = 50.0
  val suppliedSigmas = Vector(3.0, 1.0, 2.0)
  val suppliedMaps = Vector(
    Vector(0.5, 0.25, 0.25, 0.0),
    Vector(0.25, 0.25, 0.25, 0.25),
    Vector(0.4, 0.3, 0.2, 0.1),
  )
  val zeroSigma = 4.0
  val eyesimSuppliedNone = ScaleValues(Vector((3.0, RValue.Finite(1.5)), (1.0, RValue.Finite(2.0)), (2.0, RValue.Finite(1.8464393446710157))), Vector((3.0, RValue.Finite(0.75)), (1.0, RValue.Finite(1.0)), (2.0, RValue.Finite(0.9232196723355078))), Vector((3.0, RValue.Finite(1.0397207708399179)), (1.0, RValue.Finite(1.3862943611198906)), (2.0, RValue.Finite(1.2798542258336676))), Vector((3.0, RValue.Finite(0.75)), (1.0, RValue.Finite(1.0)), (2.0, RValue.Finite(0.9232196723355078))))
  val eyesimSuppliedMean = EyesimEntropy(RValue.Finite(1.782146448223672), RValue.Finite(0.891073224111836), RValue.Finite(1.2352897859311587), RValue.Finite(0.891073224111836))
  val eyesimSuppliedWithZeroNone = ScaleValues(Vector((3.0, RValue.Finite(1.5)), (1.0, RValue.Finite(2.0)), (2.0, RValue.Finite(1.8464393446710157)), (4.0, RValue.NA)), Vector((3.0, RValue.Finite(0.75)), (1.0, RValue.Finite(1.0)), (2.0, RValue.Finite(0.9232196723355078)), (4.0, RValue.NA)), Vector((3.0, RValue.Finite(1.0397207708399179)), (1.0, RValue.Finite(1.3862943611198906)), (2.0, RValue.Finite(1.2798542258336676)), (4.0, RValue.NA)), Vector((3.0, RValue.Finite(0.75)), (1.0, RValue.Finite(1.0)), (2.0, RValue.Finite(0.9232196723355078)), (4.0, RValue.NA)))
  val eyesimSuppliedWithZeroMean = EyesimEntropy(RValue.Finite(1.782146448223672), RValue.Finite(0.891073224111836), RValue.Finite(1.2352897859311587), RValue.Finite(0.891073224111836))
  val exactSupplied = Vector(
    (3.0, ExactEntropy(1.5, 0.75, 1.0397207708399179, 0.75)),
    (1.0, ExactEntropy(2.0, 1.0, 1.3862943611198906, 1.0)),
    (2.0, ExactEntropy(1.8464393446710154, 0.9232196723355077, 1.2798542258336674, 0.9232196723355077)),
  )
  val exactSuppliedMean = ExactEntropy(1.7821464482236717, 0.8910732241118359, 1.2352897859311587, 0.8910732241118359)
  val suppliedWeights = Vector((1.0, 1.0), (3.0, 3.0))
  val exactSuppliedWeighted = ExactEntropy(1.625, 0.8125, 1.126364168409911, 0.8125)
// format: on
