/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.surface

import eyes4s.core.*
import eyes4s.kernel.*
import eyes4s.kernel.Unit2D.Px
import eyes4s.surface.DerivedEntropyReference as R

/** eyesim `fixation_entropy` on derived inputs, pinned at the eyesim revision in
  * `DerivedEntropyReference` (generated by
  * `tools/r-parity/generate_derived_entropy.py`), against the public
  * [[FixationEntropy]] and [[MultiscaleEntropy]] routes.
  */
class FixationEntropyConformanceSuite extends munit.FunSuite:
  private def get[E, A](value: Either[E, A]): A = value.fold(e => fail(e.toString), identity)
  private val Tolerance                         = R.tolerance
  private val RoundedMapTolerance               = R.roundedMapTolerance

  private val frame = get(Frame.screen("derived-entropy", R.frameWidth, R.frameHeight))
  private val clock = ClockId("derived-entropy")

  private def pathOf(indices: Seq[Int]): Scanpath[Px] =
    val fixations = indices.map { i =>
      get(
        Event.Fixation.withoutDispersion(
          get(
            Interval.of(
              clock,
              Instant.micros(R.onsetMs(i) * 1000L),
              Instant.micros((R.onsetMs(i) + R.durationMs(i)) * 1000L)
            )
          ),
          Pt[Px](R.x(i), R.y(i)),
          1
        )
      )
    }
    get(Scanpath.of(frame, clock, IArray.from(fixations)))

  private val path   = pathOf(R.x.indices)
  private val single = pathOf(Vector(0))
  private val grid   = get(Grid.over(frame, R.densityNx, R.densityNy))

  private def finite(value: R.RValue): Double = value match
    case R.RValue.Finite(v) => v
    case other              => fail(s"expected a finite eyesim value, got $other")

  /** Bits, relative bits, nats, relative nats, in the fixture's order. */
  private def quadruple(e: R.EyesimEntropy): Vector[Double] =
    Vector(e.bits, e.relativeBits, e.nats, e.relativeNats).map(finite)
  private def quadruple(e: R.ExactEntropy): Vector[Double] =
    Vector(e.bits, e.relativeBits, e.nats, e.relativeNats)
  private def close(actual: Vector[Double], expected: Vector[Double], tolerance: Double)(using
      munit.Location
  ): Unit =
    assertEquals(actual.length, expected.length)
    actual.zip(expected).foreach((a, b) => assertEqualsDouble(a, b, tolerance))

  private def both(run: LogBase => (Entropy, Double)): Vector[Double] =
    Vector(LogBase.Two, LogBase.E).flatMap { base =>
      val (h, relative) = run(base)
      assertEquals(h.base, base)
      Vector(h.value, relative)
    }

  private def occupancy(
      p: Scanpath[Px],
      lattice: OccupancyLattice[Px],
      weight: Weight,
      outside: OutsideLattice
  ): LogBase => OccupancyEntropy[Px] =
    base => get(FixationEntropy.occupancy(p, lattice, weight, outside, base))

  private val explicitLattice = get(
    OccupancyLattice.of(
      frame,
      get(
        Bounds.of[Px](
          R.latticeBounds(0),
          R.latticeBounds(2),
          R.latticeBounds(1),
          R.latticeBounds(3)
        )
      ),
      R.latticeNx,
      R.latticeNy,
      LatticeUpperEdge.Closed
    )
  )

  test("grid entropy on explicit bounds equals eyesim and the exact oracle, cell by cell") {
    val run = occupancy(path, explicitLattice, Weight.Uniform, OutsideLattice.ClampToEdgeCell)
    val observed = both(b => run(b).pipe(r => (r.entropy, r.relativeEntropy)))
    close(observed, quadruple(R.eyesimGridExplicit), Tolerance)
    close(observed, quadruple(R.exactGridExplicit), Tolerance)
    val result = run(LogBase.E)
    assertEquals(result.cells.toVector, R.clampedCounts)
    assertEquals(result.outside, R.outsideLattice)
    // (20, 20) sits on interior breakpoints and belongs to the upper cell on
    // both axes; (60, 40) is the closed upper corner.
    assertEquals(get(explicitLattice.cellOf(Pt[Px](20, 20)).toRight("none")), 4)
    assertEquals(get(explicitLattice.cellOf(Pt[Px](60, 40)).toRight("none")), 5)
  }

  test(
    "the grid method ignores duration weighting in eyesim; dwell weights are an eyes4s choice"
  ) {
    assertEquals(R.eyesimGridExplicitDurationWeighted, R.eyesimGridExplicit)
    val run = occupancy(path, explicitLattice, Weight.Duration, OutsideLattice.ClampToEdgeCell)
    val result = run(LogBase.E)
    val dwell  = result.cells.toVector
    close(dwell.map(_ / dwell.sum), R.durationCounts.map(_ / R.durationCounts.sum), Tolerance)
    close(
      both(b => run(b).pipe(r => (r.entropy, r.relativeEntropy))),
      quadruple(R.exactGridDuration),
      Tolerance
    )
  }

  test(
    "excluding or refusing the outside fixation are explicit alternatives to eyesim's clamp"
  ) {
    val excluded = occupancy(path, explicitLattice, Weight.Uniform, OutsideLattice.Exclude)
    assertEquals(excluded(LogBase.E).cells.toVector, R.excludedCounts)
    assertEquals(excluded(LogBase.E).outside, R.outsideLattice)
    close(
      both(b => excluded(b).pipe(r => (r.entropy, r.relativeEntropy))),
      quadruple(R.exactGridExcluded),
      Tolerance
    )
    assertEquals(
      FixationEntropy.occupancy(
        path,
        explicitLattice,
        Weight.Uniform,
        OutsideLattice.Refuse,
        LogBase.E
      ),
      Left(FixationEntropyError.FixationOutsideLattice(5, 70.0, 12.0))
    )
  }

  test("eyesim's default padded bounds reproduce its grid entropy and counts") {
    R.paddedLattices.foreach { expected =>
      val lattice = get(
        OccupancyLattice.paddedRange(
          path,
          expected.nx,
          expected.ny,
          expected.padding,
          LatticeUpperEdge.Closed
        )
      )
      close(
        Vector(
          lattice.bounds.xMin,
          lattice.bounds.xMax,
          lattice.bounds.yMin,
          lattice.bounds.yMax
        ),
        Vector(expected.xMin, expected.xMax, expected.yMin, expected.yMax),
        Tolerance
      )
      val run = occupancy(path, lattice, Weight.Uniform, OutsideLattice.ClampToEdgeCell)
      assertEquals(run(LogBase.E).cells.toVector, expected.counts)
      assertEquals(run(LogBase.E).outside, Vector.empty)
      val observed = both(b => run(b).pipe(r => (r.entropy, r.relativeEntropy)))
      close(observed, quadruple(expected.eyesim), Tolerance)
      close(observed, quadruple(expected.exact), Tolerance)
    }
  }

  test("one fixation has zero grid entropy in both implementations") {
    val lattice =
      get(OccupancyLattice.paddedRange(single, 10, 10, 0.05, LatticeUpperEdge.Closed))
    val run = occupancy(single, lattice, Weight.Uniform, OutsideLattice.ClampToEdgeCell)
    close(both(b => run(b).pipe(r => (r.entropy, r.relativeEntropy))), Vector.fill(4)(0.0), 0.0)
    close(quadruple(R.eyesimGridSingle), Vector.fill(4)(0.0), 0.0)
  }

  test("the entropy of eyesim's own density map equals eyesim's density entropy") {
    val evalFrame = get(Frame.screen("eyesim-evaluation-lattice", R.densityNx, R.densityNy))
    val lattice   = get(Grid.over(evalFrame, R.densityNx, R.densityNy))
    Vector(
      (R.eyesimDensityMap, R.eyesimDensity, R.continuousDensity),
      (
        R.eyesimDensityMapDurationWeighted,
        R.eyesimDensityDurationWeighted,
        R.continuousDensityDurationWeighted
      )
    ).foreach { case (cells, eyesim, continuous) =>
      val mass = get(
        get(
          Surface.intensity(
            lattice,
            IArray.from(cells),
            Provenance.raw(ContentHash.of(IArray.from(cells)))
          )
        ).normalised
      )
      val observed = both(b => (mass.entropy(b), mass.relativeEntropy(b)))
      close(observed, quadruple(eyesim), Tolerance)
      // eyesim's estimand is a continuous Gaussian at endpoint-inclusive
      // points, rounded by zapsmall; the unrounded oracle agrees to that rounding.
      close(observed, quadruple(continuous), RoundedMapTolerance)
    }
    assertEquals(R.eyesimDensityX.head, 0.0)
    assertEquals(R.eyesimDensityX.last, R.frameWidth.toDouble)
  }

  test("native density entropy equals a direct two-dimensional discrete-kernel oracle") {
    val sigma = get(Sigma.px(R.sigma))
    Vector(
      (
        Weight.Uniform,
        EdgePolicy.Truncate,
        R.nativeUniformTruncate,
        R.nativeUniformTruncateMass
      ),
      (
        Weight.Uniform,
        EdgePolicy.Renormalise,
        R.nativeUniformRenormalise,
        R.nativeUniformRenormaliseMass
      ),
      (
        Weight.Duration,
        EdgePolicy.Truncate,
        R.nativeDurationTruncate,
        R.nativeDurationTruncateMass
      ),
      (
        Weight.Duration,
        EdgePolicy.Renormalise,
        R.nativeDurationRenormalise,
        R.nativeDurationRenormaliseMass
      )
    ).foreach { case (weight, edges, expected, mass) =>
      def run(base: LogBase) =
        get(
          FixationEntropy.density(
            path,
            grid,
            DensityBandwidth.Fixed(sigma),
            edges,
            weight,
            base
          )
        )
      close(
        both(b => run(b).pipe(r => (r.entropy, r.relativeEntropy))),
        quadruple(expected),
        Tolerance
      )
      close(run(LogBase.E).mass.values.toVector, mass, Tolerance)
      assertEquals(run(LogBase.E).outside, Vector(4, 5))
      assertEquals(run(LogBase.E).sigma.value, R.sigma)
    }
    // The divergence is the estimator's: the native estimate is not eyesim's.
    assert(math.abs(R.nativeUniformTruncate.nats - finite(R.eyesimDensity.nats)) > 1e-3)
  }

  test("the IQR bandwidth matches eyesim's unclamped suggestion; the display clamps differ") {
    val measure = get(path.occupancy(Weight.Uniform))
    val raw     = get(IqrBandwidth.suggest(measure, IqrBandwidthClamp.Unclamped))
    assertEqualsDouble(raw.value, finite(R.eyesimSuggestedSigmaUnclamped), Tolerance)
    val chosen = get(
      FixationEntropy.density(
        path,
        grid,
        DensityBandwidth.IqrSuggested(IqrBandwidthClamp.Unclamped),
        EdgePolicy.Truncate,
        Weight.Uniform,
        LogBase.E
      )
    )
    assertEqualsDouble(chosen.sigma.value, finite(R.eyesimSuggestedSigmaUnclamped), Tolerance)
    // eyesim clamps against its padded data range; eyes4s against the frame.
    val framed =
      get(IqrBandwidth.suggest(measure, IqrBandwidthClamp.DisplayOneToFifteenPercent)).value
    assertEqualsDouble(framed, 0.15 * (R.frameWidth + R.frameHeight) / 2.0, Tolerance)
    assert(math.abs(framed - finite(R.eyesimSuggestedSigmaPadded)) > 0.5)
    assert(finite(R.eyesimDensityDefault) > 0.0)
  }

  test("one fixation: eyesim's density entropy is NA, the native entropy is defined") {
    assertEquals(R.eyesimSingleDensityDefault, R.RValue.NA)
    assertEquals(R.eyesimSingleDensityExplicitSigma, R.RValue.NA)
    val native = get(
      FixationEntropy.density(
        single,
        grid,
        DensityBandwidth.Fixed(get(Sigma.px(R.sigma))),
        EdgePolicy.Truncate,
        Weight.Uniform,
        LogBase.E
      )
    )
    assert(native.entropy.value.isFinite && native.entropy.value > 0.0)
    assertEquals(
      FixationEntropy
        .density(
          single,
          grid,
          DensityBandwidth.IqrSuggested(IqrBandwidthClamp.Unclamped),
          EdgePolicy.Truncate,
          Weight.Uniform,
          LogBase.E
        )
        .left
        .map(_.productPrefix),
      Left("Bandwidth")
    )
  }

  private def scaleValues(values: R.ScaleValues): Vector[Map[Double, R.RValue]] =
    Vector(values.bits, values.relativeBits, values.nats, values.relativeNats).map(_.toMap)

  private def perScale(result: MultiscaleEntropy[Px]): Vector[Map[Double, Double]] =
    Vector(EntropyQuantity.Raw, EntropyQuantity.Relative).map(q =>
      result.values(q).map((s, v) => s.value -> v).toMap
    )

  private def multiscaleOf(
      g: Grid[Px],
      levels: Seq[(Double, Vector[Double])]
  ): LogBase => MultiscaleEntropy[Px] =
    base =>
      get(
        MultiscaleEntropy.of(
          levels.toVector.map { (s, cells) =>
            get(Sigma.px(s)) -> get(
              get(
                Surface.intensity(
                  g,
                  IArray.from(cells),
                  Provenance.raw(ContentHash.of(IArray.from(cells)))
                )
              ).normalised
            )
          },
          base
        )
      )

  /** eyesim none (by sigma label) and mean against a multiscale result, both bases. */
  private def agreeWithEyesim(
      run: LogBase => MultiscaleEntropy[Px],
      none: R.ScaleValues,
      mean: R.EyesimEntropy
  ): Unit =
    val eyesimNone = scaleValues(none)
    val observed   = perScale(run(LogBase.Two)) ++ perScale(run(LogBase.E))
    // Fixture order: bits, relative bits, nats, relative nats.
    Vector(0, 1, 2, 3).foreach { k =>
      assertEquals(observed(k).keySet, eyesimNone(k).keySet)
      observed(k).foreach((s, v) => assertEqualsDouble(v, finite(eyesimNone(k)(s)), Tolerance))
    }
    val means = Vector(LogBase.Two, LogBase.E).flatMap { base =>
      Vector(EntropyQuantity.Raw, EntropyQuantity.Relative).map(q =>
        get(run(base).reduce(q, ScaleReduction.Mean()))
      )
    }
    close(means, quadruple(mean), Tolerance)

  test("multiscale none and mean on eyesim's own scale maps equal eyesim, by sigma label") {
    val run = multiscaleOf(
      get(Grid.over(get(Frame.screen("eyesim-scales", R.densityNx, R.densityNy)), 6, 4)),
      R.eyesimMultiscaleMaps
    )
    agreeWithEyesim(run, R.eyesimMultiscaleNone, R.eyesimMultiscaleMean)
    // The fixation-group route with a sigma vector returns only the mean.
    assertEquals(R.eyesimMultiscaleFromGroup, R.eyesimMultiscaleMean)
    // eyesim keeps the request order; eyes4s orders scales ascending.
    assertEquals(R.eyesimMultiscaleNone.nats.map(_._1), R.multiscaleSigmas)
    assertEquals(run(LogBase.E).scales.map(_.value), R.multiscaleSigmas.sorted)
  }

  test("aggregate = none is unreachable from eyesim's fixation-group route") {
    R.eyesimMultiscaleFromGroupNone match
      case R.RValue.Error(message) => assert(message.contains("aggregate"), message)
      case other                   => fail(s"expected the pinned error, got $other")
  }

  test("native multiscale entropy: per scale, mean and weighted mean equal the oracle") {
    def run(base: LogBase) = get(
      FixationEntropy.multiscale(
        path,
        grid,
        R.multiscaleSigmas.map(s => get(Sigma.px(s))),
        EdgePolicy.Truncate,
        Weight.Uniform,
        base
      )
    )
    val expected = R.nativeMultiscale.toMap
    Vector(LogBase.Two, LogBase.E).zipWithIndex.foreach { (base, b) =>
      run(base).levels.foreach { level =>
        val e = quadruple(expected(level.sigma.value))
        assertEqualsDouble(level.entropy.value, e(2 * b), Tolerance)
        assertEqualsDouble(level.relativeEntropy, e(2 * b + 1), Tolerance)
      }
    }
    assertEquals(run(LogBase.E).outside, Vector(4, 5))
    val weights =
      ScaleReduction.Weighted(R.multiscaleWeights.map((s, w) => get(Sigma.px(s)) -> w))
    Vector(
      (ScaleReduction.Mean[Px](), R.nativeMultiscaleMean),
      (weights, R.nativeMultiscaleWeighted)
    ).foreach { (reduction, expected) =>
      val observed = Vector(LogBase.Two, LogBase.E).flatMap { base =>
        Vector(EntropyQuantity.Raw, EntropyQuantity.Relative).map(q =>
          get(run(base).reduce(q, reduction))
        )
      }
      close(observed, quadruple(expected), Tolerance)
    }
  }

  private val suppliedGrid = get(
    Grid.over(
      Frame.of(
        FrameId("supplied-scales"),
        get(Bounds.sized[Px](R.suppliedWidth, R.suppliedHeight)),
        YAxis.Down
      ),
      2,
      2
    )
  )
  private val supplied = multiscaleOf(suppliedGrid, R.suppliedSigmas.zip(R.suppliedMaps))

  test("multiscale none and mean on supplied maps equal eyesim and the exact oracle") {
    agreeWithEyesim(supplied, R.eyesimSuppliedNone, R.eyesimSuppliedMean)
    val exact = R.exactSupplied.toMap
    supplied(LogBase.Two).levels.foreach { level =>
      assertEqualsDouble(level.entropy.value, exact(level.sigma.value).bits, Tolerance)
    }
    val means = Vector(LogBase.Two, LogBase.E).flatMap { base =>
      Vector(EntropyQuantity.Raw, EntropyQuantity.Relative).map(q =>
        get(supplied(base).reduce(q, ScaleReduction.Mean()))
      )
    }
    close(means, quadruple(R.exactSuppliedMean), Tolerance)
  }

  test("explicit scale weights give the weighted oracle, which eyesim cannot express") {
    val weights =
      ScaleReduction.Weighted(R.suppliedWeights.map((s, w) => get(Sigma.px(s)) -> w))
    // Weights for sigma 1 and 3 only; sigma 2 is missing.
    assertEquals(
      supplied(LogBase.E).reduce(EntropyQuantity.Raw, weights),
      Left(FixationEntropyError.MissingScaleWeight(2.0))
    )
    val two = multiscaleOf(
      suppliedGrid,
      R.suppliedSigmas.zip(R.suppliedMaps).filter((s, _) => s != 2.0)
    )
    val observed = Vector(LogBase.Two, LogBase.E).flatMap { base =>
      Vector(EntropyQuantity.Raw, EntropyQuantity.Relative).map(q =>
        get(two(base).reduce(q, weights))
      )
    }
    close(observed, quadruple(R.exactSuppliedWeighted), Tolerance)
  }

  test(
    "a scale with no mass: eyesim gives NA and drops it from the mean; eyes4s cannot hold it"
  ) {
    val none = scaleValues(R.eyesimSuppliedWithZeroNone)
    none.foreach(m => assertEquals(m(R.zeroSigma), R.RValue.NA))
    assertEquals(R.eyesimSuppliedWithZeroMean, R.eyesimSuppliedMean)
    val zero = IArray.fill(4)(0.0)
    assertEquals(
      get(
        Surface.intensity(suppliedGrid, zero, Provenance.raw(ContentHash.of(zero)))
      ).normalised,
      Left(SurfaceError.DegenerateTotal(0.0))
    )
  }

  test("the fixture records the pinned inputs") {
    assertEquals(R.eyesimRevision.length, 40)
    assertEquals(R.inputSha256.length, 64)
  }

  extension [A](a: A) private def pipe[B](f: A => B): B = f(a)

end FixationEntropyConformanceSuite
