/*
 * Copyright 2026 canardlapin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eyes4s.surface

// Generated by tools/r-parity/generate_kde.py.
// format: off
object KdeReference:
  val x: Vector[Double] = Vector(0.5,2.5,4.5)
  val y: Vector[Double] = Vector(0.5,2.5,1.5)
  val lookup_values: Vector[Double] = Vector(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0)
  val query_x: Vector[Double] = Vector(0.5,1.0,2.0,3.0,4.0,4.5,-100.0,100.0,2.5)
  val query_y: Vector[Double] = Vector(0.5,0.5,0.5,0.5,0.5,2.5,1.5,1.5,1.0)
  val onsets_us: Vector[Long] = Vector(100000L,200000L,500000L)
  val durations_us: Vector[Long] = Vector(50000L,30000L,10000L)
  val times_us: Vector[Long] = Vector(50000L,100000L,150000L,200000L,300000L,500000L,500001L)
  val lookup: Vector[(String,Vector[Double])] = Vector(("none",Vector(1.0,2.0,2.0,4.0,4.0,15.0,6.0,10.0,8.0)),("max",Vector(0.0666666666666667,0.133333333333333,0.133333333333333,0.266666666666667,0.266666666666667,1.0,0.4,0.666666666666667,0.533333333333333)),("sum",Vector(0.00833333333333333,0.0166666666666667,0.0166666666666667,0.0333333333333333,0.0333333333333333,0.125,0.05,0.0833333333333333,0.0666666666666667)),("zscore",Vector(-1.56524758424985,-1.34164078649987,-1.34164078649987,-0.894427190999916,-0.894427190999916,1.56524758424985,-0.447213595499958,0.447213595499958,0.0)))
  val timed: Vector[Option[Double]] = Vector(None,Some(0.00833333333333333),Some(0.00833333333333333),Some(0.108333333333333),Some(0.108333333333333),Some(0.0833333333333333),Some(0.0833333333333333))
  val template_sample: Vector[Option[Double]] = Vector(None,Some(1.0),Some(1.0),Some(13.0),Some(13.0),Some(10.0),Some(10.0))
  val suggested: Vector[Double] = Vector(0.975973095143934,0.6,0.04)
// format: on
